### ISSUE TITLE
Undefined property: stdClass::$name being thrown from a number of actions

### ISSUE THREAD

**Issue by mehkanik** [vichan-devel/vichan#111]
Some users have been getting this error when trying to post, stating it showed after the site told them that their posts were discarded for flood. Not only that, some ghost threads/posts are being left when viewing the site through the mod panel and attempting to view their containing thread is showing the error. To further add to the confusion, I attempted to rebuild a board to see if anything would happen, I also got the error.

We're using vichan 4.9.92.

**Comment by czaks** [comment]
Reopen if the problem still persists.
