### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by syndicute** [vichan-devel/vichan#115]
Caching on my board is way too harsh. It doesn't show up new posts on auto-updater (or takes way too long for it, like 10 minutes after the time the post was done, despite it always "updating" after 15 seconds) and doesn't show new posts on the index page while navigating, only after 3 or 4 F5.

I'm not using APC neither other caching system, but I've got Cloudflare. Doesn't seem like a problem with them, tho. Running vichan 4.5.

**Comment by czaks** [comment]
known issue, instruct your webserver to send nocache headers for .html files.

**Comment by syndicute** [comment]
that was probably it, solved moving to a VPS instead of shared hosting, tho
