### ISSUE TITLE
Whenever I try to post a image, I get error: file already exists

### ISSUE THREAD

**Issue by GooseJS** [vichan-devel/vichan#126]
Well, title says it all. Because of this I can't create a new thread (Seeing how it requires a image)

**Comment by marlencrabapple** [comment]
Sounds like vichan isn't generating md5 hashes for images properly. Check your posts table to confirm if that's the case. If so, check if md5sum (or just md5 if you're on a BSD derivative) is installed.

**Comment by czaks** [comment]
$config['bsd_md5'] = true; // if you are using BSD systems
  $config['php_md5'] = true; // windows system, or system php command is blocked
