### ISSUE TITLE
command-line ImageMagick image processing cannot be enabled

### ISSUE THREAD

**Issue by Link-Satonaka** [vichan-devel/vichan#130]
I have this issue with tinyboard too, can't figure out what's wrong. Might be that tinyboard is incompatible with archlinux's alteration to the /bin folders: https://www.archlinux.org/news/binaries-move-to-usrbin-requiring-update-intervention/

I have all of the following installed, yet I get the warnings:

There were 0 error(s) and 4 warning(s).

    Warning: (Optional) `convert` was not found or executable; command-line ImageMagick image processing cannot be enabled.
    Warning: (Optional) `identify` was not found or executable; command-line ImageMagick image processing cannot be enabled.
    Warning: (Optional) `gm` was not found or executable; command-line GraphicsMagick (faster than ImageMagick) cannot be enabled.
    Warning: (Optional) `gifsicle` was not found or executable; you may not use `convert+gifsicle` for better animated GIF thumbnailing.

**Comment by czaks** [comment]
i run vichan on fedora, which also has binmove :^)

i am sure this is not a problem with vichan, you probably have shell_exec disabled, or selinux (or other MAC) blocks your webserver to access those binaries. or maybe your php runs in a chroot.

**Comment by Link-Satonaka** [comment]
archlinux doesn't have selinux by default, how would I check for shell_exec or php in chroot?
I'm trying to follow the instructions here but pecl isn't cooperating: https://wiki.archlinux.org/index.php/PHP#imagemagick

**Comment by czaks** [comment]
this is imagick, not convert. we support imagick, but it's basically unmaintained. install /usr/bin/convert or /usr/bin/gm and maybe /usr/bin/gifsicle
