### ISSUE TITLE
Replies, topic creation broken

### ISSUE THREAD

**Issue by Link-Satonaka** [vichan-devel/vichan#132]
Fatal error: Call to undefined function iconv() in /srv/http/vichan/inc/functions.php on line 2460 Fatal error: Cannot redeclare class Twig_Autoloader in /srv/http/vichan/inc/lib/Twig/Autoloader.php on line 18

**Comment by czaks** [comment]
your php version doesn't support iconv. please comment out that line, everything should work well. i will commit a workaround

**Comment by czaks** [comment]
or install php-iconv, or whatever the package is called by your distro

**Comment by Link-Satonaka** [comment]
I'm not sure archlinux even has it.
Not in the official repo: https://www.archlinux.org/packages/?sort=&q=iconv&maintainer=&flagged=
Not in the user repo: https://aur.archlinux.org/packages/?O=0&C=0&SeB=nd&K=iconv&outdated=&SB=n&SO=a&PP=50&do_Search=Go

**Comment by czaks** [comment]
search for a file called: /usr/lib64/php/modules/iconv.so 

also would need to be included in php using /etc/php.d/iconv.so:

    ; Enable iconv extension module
    extension=iconv.so

**Comment by Link-Satonaka** [comment]
I had JUST found that on my own while investigating my other issue. In /etc/php/php.ini I uncommented
`extension=iconv.so`
is what I needed. Thanks
