### ISSUE TITLE
Noob question : no index after rebuild ?

### ISSUE THREAD

**Issue by Draky50110** [vichan-devel/vichan#136]
Hello.

Just tried to install vichan.
All ok, went to /mod.php and rebuild but nothing on root.

I though it would make index.xxx or any other index file.

Did I miss something ?

Made PHP rebuild.php from /tools/ : no error
rebuild2 gave me error...

**Comment by JasonPuglisi** [comment]
There's no root page by default, but some themes, such as RecentPosts, will make one if you go to Manage themes in the dashboard.

**Comment by Draky50110** [comment]
Ok, I understand.
I installed "Frameset" and it is ok :)
