### ISSUE TITLE
recaptcha

### ISSUE THREAD

**Issue by bush6** [vichan-devel/vichan#140]
Vichan still uses old recaptcha api. I think we should switch to the new api which has no captcha recaptcha To make posting faster while still being able to prevent spam.

**Comment by czaks** [comment]
we have a new captcha api. there are only two implementations currently:
* my private captcha for 8chan
* coolphpcaptcha integration, known as 8chan-captcha, residing in infinity repo

and there is old recaptcha support. we should support the new recaptcha api with our new api.

**Comment by AXYPB** [comment]
The implementation of reCAPTCHA V1 in vichan is no longer functional. The board returns "unknown error" for all posts and replies. According to Google, reCAPTCHA V1 is deprecated, and only by disabling reCAPTCHA in my installation is posting possible. I found that it was the only measure that reliably prevented spam on my board, so I am unwilling to disable it.

**Comment by H0K4** [comment]
https://github.com/vichan-devel/vichan/pull/224 implement this pull manually I will probably update it with 8chan's coolphpcaptcha but don't have much time.

**Comment by Circlepuller** [comment]
#241 includes an update of the reCAPTCHA code to version 2. Also purged the version 1 library out of the codebase.

**Comment by ctrlcctrlv** [comment]
Fixed in #241
