### ISSUE TITLE
threads.json is checked more often than the thread itself

### ISSUE THREAD

**Issue by bui** [vichan-devel/vichan#143]
it looks like threads.json is every 30 seconds without change. this should probably match the time the thread is updated at, or less often

**Comment by czaks** [comment]
you can use smart_build to make it compile at the time it's requested and changed

**Comment by bui** [comment]
@czaks I mean the client

**Comment by czaks** [comment]
i see, which script uses threads.json? i believe it's thread-stats.js, right? if yes, we can't tell in advance, when we should fetch that script (it checks what page the thread is on and it can change even without thread modification). this is a problem with a synchronous design of vichan
