### ISSUE TITLE
.webm:s over 2mb in size don't work

### ISSUE THREAD

**Issue by ultimatenyymi** [vichan-devel/vichan#147]
For some reason .webm:s over 2mb in size don't work, image here http://puu.sh/idOR9/29645f1175.jpg Webms smaller than 2mb and images larger than 2mb work. What do i need to do to make them work.

**Comment by ctrlcctrlv** [comment]
Your web server is probably misconfigured. This isn't a bug.

**Comment by ultimatenyymi** [comment]
It was, i was sure i had configured it properly earlier. Sorry for bothering you.
