### ISSUE TITLE
convert on windows iis

### ISSUE THREAD

**Issue by tunayuyar** [vichan-devel/vichan#148]
Hi devs,

image.php from derpyboard (https://github.com/Juze/Derpyboard/blob/master/inc/image.php) working with convert option on windows but vichan convert doesnot just throws error(no specific error). 

Im no coder but is derpychan using anyfallback for convert? 

Any comments on this?

Thanks.

**Comment by ctrlcctrlv** [comment]
"Derpy" board?

Last updated in 2012, looks like a *way* out of date Tinyboard fork.

Anyway "Derpychan" (is this a website or are you talking about the board software?) is just inc/image.php from TB, and yes there is a fallback by setting `$config['thumb_method']` to `gd`.

**Comment by tunayuyar** [comment]
How they animate gifs using gd? I thought it is only achieavable by imagick convert gifsicle. Am I mistaken?

**Comment by ctrlcctrlv** [comment]
You're not mistaken. So if they have animation they certainly aren't using the GD fallback.

**Comment by tunayuyar** [comment]
Check this out http://www.tahta.ch/meta/res/145.html  

First glitched charmanders belongs to vichan with imagick, rest belongs to derpyboard's image.php with convert option.

The most interesting thing is i cannot use convert at all with vichan.  

Any dev can compare two image.php ?

**Comment by tunayuyar** [comment]
Definitely that code works with convert, tried changing shell_path to invalid location, than it stopped working.  But why vichan not works maybe someone look into it?

**Comment by czaks** [comment]
I am not a windows user at all, but I am sure this one can work with
windows servers. Just make sure you point shell_path to a correct
directory, where you have both ImageMagick (ie. convert) and gifsicle
binaries installed.

**Comment by tunayuyar** [comment]
Hi Czaks,

Shell_path was valid since start but vichan was throwing error(not debuged but i can if you want to solve this). I was trying to modify code for imagick because it was using more than 2gb of memory and throwing error that allocated 1.9gb memory tried to allocate 2kb which is not logical. 

Then tried derpyboards image.php and it worked flawlessly. Then tested whether it uses convert or not with changing shell_path to invalid location, indeed it was using convert not any other method.

convert options needs gifsicle ? (just convert not convert plus gifsicle)
