### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by ultimatenyymi** [vichan-devel/vichan#150]
Often when someone tries to post, it shows this error with the title 403 Forbidden:

Forbidden

You don't have permission to access /post.php on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

How can i fix this?

**Comment by czaks** [comment]
this is an error of your webserver. you set your permissions wrong, or there is no php interpreter, etc.

see apache logs for help

**Comment by ultimatenyymi** [comment]
It's not about persmissions, that's for sure. Strangest thing is that it's so random, it might go away for days only to come back and make posting impossible for few hours and go away again, so it's hard to see if it's fixed.

**Comment by czaks** [comment]
it's a problem with your shared hosting then. remember: vichan runs best on
a VPS :^)

**Comment by ultimatenyymi** [comment]
Is there a way to fix that?
