### ISSUE TITLE
hex2bin(): Input string must be hexadecimal string

### ISSUE THREAD

**Issue by ghost** [vichan-devel/vichan#165]
when viewing or creating thread i got hex2bin(): Input string must be hexadecimal string.

1st installation failed because table not correctly inserted in db. so i manual import install.sql

after than i try to create thread that show me **hex2bin(): Input string must be hexadecimal string.**

**Comment by perayknox** [comment]
same problem here..

**Comment by czaks** [comment]
it should work to find the instance of hex2bin call and prefix it with @ to surpress warnings. i will commit the fix upstream later

**Comment by tunayuyar** [comment]
Tried to update from 4.9.93 to current version after git pull but this still happens.  Any fix?

**Comment by czaks** [comment]
you can either upgrade your php to 5.4, or upgrade vichan and get a support for this function with a polyfill (this is the fix i was talking about in a previous comment). in either case, i'm not sure we want to support php <5.4 anymore.

**Comment by tunayuyar** [comment]
@czaks Im using php 5.6 still having problems trying to upgrade.

**Comment by czaks** [comment]
do my tip from 11 Jan comment

**Comment by tunayuyar** [comment]
@czaks I dont understand any of this :) you know me. 

Also installation is not possible from cloning vichan from github. There are several problems i think, could you check it might be related to sql file.
