### ISSUE TITLE
Webm Upload Results in no Image

### ISSUE THREAD

**Issue by yeltsew7** [vichan-devel/vichan#167]
I have webm uploads enabled on my Vichan installation, with the following lines in my instance-config.php:
`$config['allowed_ext_files'][] = 'webm';`
`$config['additional_javascript'][] = 'js/webm-settings.js';`
`$config['additional_javascript'][] = 'js/expand-video.js';`
`$config['webm']['use_ffmpeg'] = true;`
`$config['webm']['allow_audio'] = true;`

When I attempt to upload a webm, the post seems to go through without error.  Once the post shows up afterwards though, there is no webm, as if I had not selected a file at all.

![Broken Posts](https://my.mixtape.moe/udxurt.png)

No errors are shown, and I have the max upload sizes set in php.ini, my nginx config and in instance-config.php.

**Comment by czaks** [comment]
make sure you have ffmpeg installed as well. disable this option if you are
not sure.

**Comment by czaks** [comment]
this one: $config['webm']['use_ffmpeg'] = true;

**Comment by yeltsew7** [comment]
I have ffmpeg installed, and I also have the correct paths set now. It's still not working.
I've tried disabling that option too, but it still has the same result.

**Comment by 27chan** [comment]
Get your php.ini, use upload_max_filesize=15M

**Comment by yeltsew7** [comment]
Thanks, I figured out that I was editing the wrong php.ini.

**Comment by 27chan** [comment]
Thanks, I figured out that I was editing the wrong php.ini.

**Comment by 27chan** [comment]
See ya!
