### ISSUE TITLE
Once upgraded, vichan refuses to let users post.

### ISSUE THREAD

**Issue by ciam** [vichan-devel/vichan#170]
Upon upgrading to the latest version, I am greeted with the following error when trying to post.

> Notice: Undefined index: syslog in /var/www/html/inc/display.php on line 77 Notice: Undefined index: debug in /var/www/html/inc/display.php on line 89 Notice: Undefined index: debug in /var/www/html/inc/display.php on line 93 Notice: Undefined index: password in /var/www/html/inc/display.php on line 112 Notice: Undefined index: template in /var/www/html/inc/template.php on line 22 Notice: Undefined index: template in /var/www/html/inc/template.php on line 23 Fatal error: Uncaught exception 'Twig_Error_Loader' with message 'The "" directory does not exist.' in /var/www/html/inc/lib/Twig/Loader/Filesystem.php:93 Stack trace: #0 /var/www/html/inc/lib/Twig/Loader/Filesystem.php(75): Twig_Loader_Filesystem->addPath(NULL, '__main__') #1 /var/www/html/inc/template.php(23): Twig_Loader_Filesystem->setPaths(NULL) #2 /var/www/html/inc/template.php(38): load_twig() #3 /var/www/html/inc/display.php(134): Element('error.html', Array) #4 /var/www/html/inc/functions.php(382): error('file_put_conten...', true, Array) #5 [internal function]: verbose_error_handler(2, 'file_put_conten...', '/var/www/html/i...', 145, Array) #6 /var/www/html/inc/functions.php(145): file_put_contents('tmp/cache/local...', 'en') #7 /var/www/html/inc/functions.php(534): loadConfig() #8 /var/www/html/inc/functions.php(557): setupBoard(Array) #9 /var/www/html/post.php(178): openBoard('b') #10 {main} thrown in /var/www/html/inc/lib/Twig/Loader/Filesystem.php on line 93 Notice: Undefined index: syslog in /var/www/html/inc/display.php on line 77 Notice: Undefined index: debug in /var/www/html/inc/display.php on line 89 Notice: Undefined index: debug in /var/www/html/inc/display.php on line 93 Notice: Undefined index: password in /var/www/html/inc/display.php on line 112 Fatal error: Cannot redeclare class Twig_Autoloader in /var/www/html/inc/lib/Twig/Autoloader.php on line 17

**Comment by deysu** [comment]
Well, for the Googlers out there, this error is seemingly related to permissions. I fixed it by chowning my web directory to `www-data`. Puzzling!
