### ISSUE TITLE
Spam prevention is broken

### ISSUE THREAD

**Issue by sawarineko** [vichan-devel/vichan#172]
Installed latest vichan from master branch and whenever I try to post I get "Your request looks automated" unless I'm browsing from mod.php .

Commenting lines 248 and 249 in post.php fixes it as it can't throw the error anymore and lets me post. I haven't changed any of the default config for spam and disabled all optional js. Tried with latest Firefox and Chromium.

Running nginx on Ubuntu,  is this specific to nginx ? It worked before with Apache on shared hosting.

**Comment by xDiglett** [comment]
Having the same issues

**Comment by ctrlcctrlv** [comment]
Works for me friend - you're probably not passing some headers or something. Try a different nginx config. Close old issue.
