### ISSUE TITLE
webm/mp4 files and moving threads

### ISSUE THREAD

**Issue by enoxitus** [vichan-devel/vichan#173]
So the problem is that I can't post any webm/mp4 files. GIF and other image related files work. Yes I already tried to turn ffmpeg off. Max. filesize is default 10MB. The threads show up as text only.

Also, how do I move threads to other boards? I can't find this option anywhere although I know it exists

**Comment by yanolol** [comment]
You change maximum upload file size in php.ini?

To move threads put this in your instance-config.php

```
// "Move" a thread to another board (EXPERIMENTAL; has some known bugs)
	$config['mod']['move'] = ADMIN;
```

You can change ADMIN for MOD.

**Comment by enoxitus** [comment]
> You change maximum upload file size in php.ini?
Sorry it took me so long to respond. I cannot find the php.ini file. I'm pretty sure that I was able to change it somewhere else, but I didn't because 10MB was enough for most webm/mp4 files.

**Comment by yanolol** [comment]
You can change in your apache2

/etc/php5/apache2/php.ini

upload_max_filesize
post_max_size

Restart apache.

**Comment by KebabLord** [comment]
> > You change maximum upload file size in php.ini?
> 
> Sorry it took me so long to respond. I cannot find the php.ini file. I'm pretty sure that I was able to change it somewhere else, but I didn't because 10MB was enough for most webm/mp4 files.

you can always find your php.ini by performing `php --ini` on terminal btw
