### ISSUE TITLE
Logging after installation is broken

### ISSUE THREAD

**Issue by The-Beast** [vichan-devel/vichan#175]
So, I've installed vichan today, but when I try to log in mod.php I get `Caught fatal error: Call to undefined function hash_equals() in /somewhere/board/inc/mod/auth.php on line 68`. What should I do?

**Comment by bakugo** [comment]
What PHP version are you using? `hash_equals()` doesn't exist before 5.6.
This was added in https://github.com/vichan-devel/vichan/commit/caaf741691c9d44a9a186d6ce924fecb04f4f347 but it looks like the required version in the readme wasn't updated.

**Comment by The-Beast** [comment]
Okay, thanks. I was using PHP 5.4, but I've updated to 5.6 and it works just fine.

**Comment by fatchan** [comment]
@bakugo I let czaks know about the mismatch in the readme/install.php and he said he would look at it.

**Comment by czaks** [comment]
Fixed. I backported the function.
