### ISSUE TITLE
Git pull broken my vichan

### ISSUE THREAD

**Issue by 27chan** [vichan-devel/vichan#178]
When I update the Vichan, it broke and now with this error message.

```
Error
An error has occured.
Unknown column 'version' in 'field list'
```

**Comment by 27chan** [comment]
This error message appears on the mod.php

**Comment by czaks** [comment]
run install.php, a DB upgrade is needed

**Comment by 27chan** [comment]
I'm still having problems.

**Comment by czaks** [comment]
you need to execute install.php to update your database from an earlier
schema to a newer one. your schema is definitely the older one. this won't
work if you modified an .installed file, which contains a version number,
in which case you will need to modify this file to the original value and
run install.php.

**Comment by 27chan** [comment]
I reinstalled Vichan and i create new folder with a new Vichan and still same problem.

**Comment by czaks** [comment]
https://github.com/vichan-devel/vichan/blob/master/install.sql#L136

install.sql makes a `version` field for new installations. your error tells
us, that the code looks for the `version` field, but there is none, which
is what would happen with an old-schema instalaltion. i am quite sure it's
not a problem with the codebase itself, but with your operations (for
example, an older version of file or your local modifications). if it
happens to be a fault of the installation, i would need more detailed info.
