### ISSUE TITLE
File selector enabled, gives error [Error: you must upload an image]

### ISSUE THREAD

**Issue by lmfsthefounder** [vichan-devel/vichan#180]
I had multi-image available on my site, and decided to try the file selector. When I enable file-selector.js in my instance-config.php and rebuild, the selector shows up on the imageboard form. However, when I submit my POST,  post.php gives the error [Error: you must upload an image], implying that the file(s) never posted.

I have tried variations of other scripts. Someone in the #vichan-devel IRC room, who suggested that ajax.js may be required. I want to note that, if it IS in fact required, it should be noted in the header section of file-selector.js here in the repo, which it is not. 

I have tried this with and without multi-image.js, and in varying orders, and on two separate sites that I own. 
 My additional_js is something similar to this, but all these are included in this order:
    ```
$config['additional_javascript'][] = 'js/ajax.js';
    $config['additional_javascript'][] = 'js/file-selector.js';
    //$config['additional_javascript'][] = 'js/multi-image.js';
    $config['max_images'] = 4;
    $config['multiimage_method'] = 'each';

```
```

**Comment by 1legality** [comment]
I think it is related to the anti-spam filter that put many fake fields as a anti-bot system.

I remember adding these lines in my instance config

```php   
    // Acivate antibot system... antibot system is not working with filechooser.
    $config['enable_antibot'] = false;
```
and modifying this in post.php

```php    
if (!$post['mod']) {
        $post['antispam_hash'] = checkSpam(array($board['uri'], isset($post['thread']) ? $post['thread'] : ($config['try_smarter'] && isset($_POST['page']) ? 0 - (int)$_POST['page'] : null)));
        if ($post['antispam_hash'] === true && $config['enable_antibot'])
            error($config['error']['spam']);
    }
```

Please note that this is a bad practice as it allows bots to post on your website. I am in no way a php programmer : I just didn't found a better solution than just disabling it and banning Russians/Chinese IPs.

**Comment by 1legality** [comment]
By the way, I found this by looking at infinity source code. It means that Infinity probably use another system for bots (I think they are using recaptcha only but I'm not sure)

**Comment by lmfsthefounder** [comment]
Hey I'm away right now but give me about an hour and I'll look at what you're talking about with a chance to look at it in context

**Comment by ctrlcctrlv** [comment]
Abandoned issue.
