### ISSUE TITLE
Duplicate catalog link

### ISSUE THREAD

**Issue by fatchan** [vichan-devel/vichan#183]
When catalog-link.js is enabled, a catalog link is appended to the page number links on each board. However there is already one there and you end up with 2 links.

Quick-fix: https://github.com/fatchan/vichan/commit/34ae5097eca1c2272393e5fa5f04d9253fd6113a

Any idea where the duplicate comes from?

**Comment by czaks** [comment]
$config['catalog_link'] maybe?

**Comment by fatchan** [comment]
Without $config['catalog_link'] there is a link on the page nav links, but not one below the board subtitle
With $config['catalog_link'] you end up with 2 on the page nav and one under the subtitle

**Comment by fatchan** [comment]
FOUND THE ISSUE:

in the templates:
```
		{% if config.catalog_link %}
			 | <a href="{{ config.root }}{{ board.dir }}{{ config.catalog_link }}">{% trans %}Catalog{% endtrans %}</a>
		{% endif %}
```
Then in the catalog-link.js, 
```
	pages.appendChild(link)

...
	subtitle.appendChild(link2);	
```

So essentially catalog-link creates 2 and the template is checking if the config is there and adding a second link.
Best solution is build them both into the templates. If you cbf, ill make a pull request tomorrow for it.

**Comment by fatchan** [comment]
https://github.com/fatchan/vichan/commit/d26aacf97a4b4e6cd7d38a67513cc8484722383a
https://github.com/fatchan/vichan/commit/ddfcb1791afb73b14e8122d40e2fb7a144dc5220

There's the fix. You can cherry pick those
