### ISSUE TITLE
need forum mode

### ISSUE THREAD

**Issue by metalbug** [vichan-devel/vichan#184]
Has been looking for a lightweight forum program, looking for a lot of, are not suitable for my needs, and finally I find this, this is very cool, but does not support the registered users of the normal forum model, I need user registration, user login, user avatar, reply to watch, these normal forum mode, In the setting, board type, image board, text board, file board, and bbs board, I like this program very much, I hope this program can be done better, thanks man, for the goodjob.

**Comment by czaks** [comment]
i'm open to modifying the software to supply non-standard usecase models, provided they are implemented as modules. let's try to modularize the question a bit.

#### user registration

this feature is planned to be implemented in vichan as "moderator registration", similar to what 8chan/infinity does. 

#### user login

mod login is possible. see above.

#### user avatar

i don't think it makes too much sense. it may be implemented in terms of capcode?

#### reply to watch

this is possible to be implemented as a module to a watcher system

#### normal forum mode

looking at a file board we already support, doing a "normal forum" could be possible as well

#### allowing only moderators to post

possible to do and easy

**Comment by metalbug** [comment]
okay, and I modify the thread-watcher.js have problem, Could you fix it for me?

`
var _watch = JSON.parse(localStorage.watchlist);
var is_watch = ~$.inArray(watchlist, _watch);

		$('.op>.intro').append('<i class="watchThread fa '+(is_watch ? 'fa-heart' : 'fa-heart-o')+'" data-active="'+(is_watch ? 'true' : 'false')+'" style="color: '+(is_watch ? 'pink' : 'grey')+'; "></i>');
		$('.watchThread').on('click', function(e) {
			e.preventDefault();
			if (!$(this).data('active')) {
				watchlist.add(this).render();
				$(this).css('color', 'pink');
				$(this).removeClass().addClass("watchThread fa fa-heart");
				$(this).data('active', true);
				$('#watchlist').css('display', 'block');
			} else {
				watchlist.remove(this).render();
				$(this).css('color', 'grey');
				$(this).removeClass().addClass("watchThread fa fa-heart-o");
				$(this).data('active', false);
			}
		});
	//Append the watchlist toggle button.
	//$('.boardlist').append('<span>[ <a class="watchlist-toggle" href="#">'+_('watchlist')+'</a> ]</span>');
	//Append a watch thread button after every OP.
	//$('.op>.intro').append('<a class="watchThread" href="#">['+_('Watch Thread')+']</a>');`

i follow favorites.js to modify this js, but it dont work...do you fix this? Thanks again.

**Comment by neko** [comment]
the avatar could be possible by using the email field with the [gravatar](https://en.gravatar.com/) service

**Comment by ctrlcctrlv** [comment]
As the current maintainer I am not open to making this a forum software so am closing this issue as WONTFIX.
