### ISSUE TITLE
Some error on pages.php

### ISSUE THREAD

**Issue by sambuev** [vichan-devel/vichan#186]
When I login to mod.php and see all options (Theme, Rebuild, etc) they are all translated except: _Global static pages_ and when I click on it it shows me error:

**Cannot modify header information - headers already sent by (output started at /nfs/c04/h02/mnt/34597/domains/mychan.com/html/inc/mod/pages.php:2781)**

and this on top of the page: 

Fatal error: Call to a member function execute() on a non-object in /nfs/c04/h02/mnt/34597/domains/mychan.com/html/inc/mod/pages.php on line 2781 Warning: Cannot modify header information - headers already sent by (output started at /nfs/c04/h02/mnt/34597/domains/mychan.com/html/inc/mod/pages.php:2781) in /nfs/c04/h02/mnt/34597/domains/mychan.com/html/inc/display.php on line 104

**Comment by sambuev** [comment]
How to fix it? I cannot fix it on my side. Maybe it's because I have apache server?

**Comment by sambuev** [comment]
line 2781 on pages.php
`
	$query->execute() or error(db_error($query));
`

**Comment by czaks** [comment]
try to evaluate this instruction on your db:

https://github.com/vichan-devel/vichan/blob/master/install.sql#L306

there was a bad merge before, which may have caused this problem (or not).
