### ISSUE TITLE
Embeded html5 player for .mov uploads

### ISSUE THREAD

**Issue by sambuev** [vichan-devel/vichan#187]
Hello, I want users to upload their .mov files with h.264 codec and play on some basic html5 player. Can you please make this option?

**Comment by czaks** [comment]
afaik .mov files and .mp4 files are mostly the same container format.
wouldn't it be enough to rename a .mov file to .mp4?

**Comment by sambuev** [comment]
on Mac os most of the files are h.264 mov acc, is it possible to upload them and embed simple html5 player? You don't need to convert files, just play them in player. It can be other formats too, .mov mp4 with h.264 codes.

**Comment by ctrlcctrlv** [comment]
MOV is cancer - no.
