### ISSUE TITLE
Mobile embed video support please.

### ISSUE THREAD

**Issue by sambuev** [vichan-devel/vichan#189]
hello, I have site where users posting links to youtube and vimeo, it's all working great, but when I visiting from iOS devises (Mobile Safari) I do not see any videos, just huge empty rectangle space and it's confusing visitors, they just don't see any hint of video.

Can you please update embed scripts to it can be html5 or something where youtube and vimeo can be shown? At least screenshot where users click and goes to video? 

Also it would be great to have script which takes any youtube (and vimeo) link and converts it to embed-code? Right now video is popular and this feature will be very helpful for mobile users. 

Thank you!

**Comment by sambuev** [comment]
Youtube is working right now, only problem with vimeo embed player, it only shows on desktops, not on mobile devices. 
I've found video embdeding option in config.php, but I don't know settings for html5 player, not flash player... please have a look to this code from ../config.php 

maybe it need to be updated to new? at least for Vimeo? 


`/*
 * ====================
 *  Video embedding
 * ====================
 */

	// Enable embedding (see below).
	$config['enable_embedding'] = false;

	// Custom embedding (YouTube, vimeo, etc.)
	// It's very important that you match the entire input (with ^ and $) or things will not work correctly.
	$config['embedding'] = array(
		array(
			'/^https?:\/\/(\w+\.)?youtube\.com\/watch\?v=([a-zA-Z0-9\-_]{10,11})(&.+)?$/i',
			'<iframe style="float: left;margin: 10px 20px;" width="%%tb_width%%" height="%%tb_height%%" frameborder="0" id="ytplayer" src="http://www.youtube.com/embed/$2"></iframe>'
		),
		array(
			'/^https?:\/\/(\w+\.)?vimeo\.com\/(\d{2,10})(\?.+)?$/i',
			'<object style="float: left;margin: 10px 20px;" width="%%tb_width%%" height="%%tb_height%%"><param name="allowfullscreen" value="true" /><param name="allowscriptaccess" value="always" /><param name="movie" value="http://vimeo.com/moogaloop.swf?clip_id=$2&amp;server=vimeo.com&amp;show_title=0&amp;show_byline=0&amp;show_portrait=0&amp;color=00adef&amp;fullscreen=1&amp;autoplay=0&amp;loop=0" /><embed src="http://vimeo.com/moogaloop.swf?clip_id=$2&amp;server=vimeo.com&amp;show_title=0&amp;show_byline=0&amp;show_portrait=0&amp;color=00adef&amp;fullscreen=1&amp;autoplay=0&amp;loop=0" type="application/x-shockwave-flash" allowfullscreen="true" allowscriptaccess="always" width="%%tb_width%%" height="%%tb_height%%"></object>'
		),
		array(
			'/^https?:\/\/(\w+\.)?dailymotion\.com\/video\/([a-zA-Z0-9]{2,10})(_.+)?$/i',
			'<object style="float: left;margin: 10px 20px;" width="%%tb_width%%" height="%%tb_height%%"><param name="movie" value="http://www.dailymotion.com/swf/video/$2"><param name="allowFullScreen" value="true"><param name="allowScriptAccess" value="always"><param name="wmode" value="transparent"><embed type="application/x-shockwave-flash" src="http://www.dailymotion.com/swf/video/$2" width="%%tb_width%%" height="%%tb_height%%" wmode="transparent" allowfullscreen="true" allowscriptaccess="always"></object>'
		),
		array(
			'/^https?:\/\/(\w+\.)?metacafe\.com\/watch\/(\d+)\/([a-zA-Z0-9_\-.]+)\/(\?[^\'"<>]+)?$/i',
			'<div style="float:left;margin:10px 20px;width:%%tb_width%%px;height:%%tb_height%%px"><embed flashVars="playerVars=showStats=no|autoPlay=no" src="http://www.metacafe.com/fplayer/$2/$3.swf" width="%%tb_width%%" height="%%tb_height%%" wmode="transparent" allowFullScreen="true" allowScriptAccess="always" name="Metacafe_$2" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash"></div>'
		),
		array(
			'/^https?:\/\/video\.google\.com\/videoplay\?docid=(\d+)([&#](.+)?)?$/i',
			'<embed src="http://video.google.com/googleplayer.swf?docid=$1&hl=en&fs=true" style="width:%%tb_width%%px;height:%%tb_height%%px;float:left;margin:10px 20px" allowFullScreen="true" allowScriptAccess="always" type="application/x-shockwave-flash"></embed>'
		),
		array(
			'/^https?:\/\/(\w+\.)?vocaroo\.com\/i\/([a-zA-Z0-9]{2,15})$/i',
			'<object style="float: left;margin: 10px 20px;" width="148" height="44"><param name="movie" value="http://vocaroo.com/player.swf?playMediaID=$2&autoplay=0"><param name="wmode" value="transparent"><embed src="http://vocaroo.com/player.swf?playMediaID=$2&autoplay=0" width="148" height="44" wmode="transparent" type="application/x-shockwave-flash"></object>'
		)
	);

	// Embedding width and height.
	$config['embed_width'] = 300;
	$config['embed_height'] = 246;`

**Comment by sambuev** [comment]
Also it would be amazing to have COUB support in Insert-Media field.
it has everything you need, just little embed code update here at it can work.

**Comment by sambuev** [comment]
Facing this problem again, have many videos from Vimeo, it's getting embedded as flash video, my browsers on windows doesnt have flash plugin anymore, no more option to watch videos from there. 

Same problem was with mobile, currently, it's on desktops too, only with Vimeo for now, youtube works well.

**Comment by goosehub** [comment]
If it's useful here, I've made a script for converting several urls to embeds.

https://github.com/goosehub/embedica

Here's my Vimeo convert regex:

```
function embedica_convert_vimeo(input) {
  var pattern = /(?:http?s?:\/\/)?(?:www\.)?(?:vimeo\.com)\/?(\S+)/g;
  if (pattern.test(input)) {
    var replacement = '<span class="embedica_vimeo embedica_element"><iframe src="//player.vimeo.com/video/$1" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe></span>';
    var input = input.replace(pattern, replacement);
  }
  return input;
}
```

**Comment by sambuev** [comment]
Hello, I have used your embedica.js with vichan, when I did test posting it could not convert it to embedev video, it still just a text link. How to execute your script properly?

**Comment by ctrlcctrlv** [comment]
Just change https://github.com/vichan-devel/vichan/blob/master/inc/config.php#L1077 to whatever the new embed code is for that site and submit a PR.
