### ISSUE TITLE
Board list doesn't show up on static page

### ISSUE THREAD

**Issue by Chapodalu** [vichan-devel/vichan#192]
Hi,
When I create a static page with the admin panel, the boardlist doesn't show up at the top of the page. I try to edit /templates/page.html but the boardlist tag **{{ boardlist.top }}** is already there.

**Comment by Darktrader** [comment]
Same bug report. Can you recommend a temporary solve to this problem?

**Comment by Chapodalu** [comment]
I have finaly solved this.

Open /inc/mod/pages.php and replace this line line (2748) :
`$html = Element('page.html', array('config' => $config, 'body' => $body, 'title' => utf8tohtml($page['title'])));`
By this :
`$html = Element('page.html', array('config' => $config, 'boardlist' => createBoardlist(), 'body' => $body, 'title' => utf8tohtml($page['title'])));`

You have to rebuild your page to see the boardlist.

**Comment by Chapodalu** [comment]
I have finaly solved this.

Open /inc/mod/pages.php and replace this line line (2748) :
`$html = Element('page.html', array('config' => $config, 'body' => $body, 'title' => utf8tohtml($page['title'])));`
By this :
`$html = Element('page.html', array('config' => $config, 'boardlist' => createBoardlist(), 'body' => $body, 'title' => utf8tohtml($page['title'])));`

You must rebuild your pages to see the boardlist.
