### ISSUE TITLE
Conflict with attaching image and putting video url in one post

### ISSUE THREAD

**Issue by sambuev** [vichan-devel/vichan#193]
Hello, when I making post, I attached image and put url in "Input Media" field and only video has been posted, but image was just ignored and there is no option to see it anywhere. it' just wipes. How to fix it? Maybe keep video as embed, and attach small or extra small image as thumbnail in one post?

**Comment by ctrlcctrlv** [comment]
Not possible due to deeper problems in how embeds are handled. A quite large overhaul would be required. You can either embed a video or post images/WEBMs, not both. Feel free to contribute code to fix it though - just we're not going to because we don't see it as a big deal.
