### ISSUE TITLE
Bug with attaching files .zip to post

### ISSUE THREAD

**Issue by sambuev** [vichan-devel/vichan#194]
I was posting .zip file today while doing post, it was uploading with no problem, then it posted without any .zip file. Just like post, but without attachment. Didn't even say anything, just ignored attachment. How to fix it? I can't even tell what has happen, just ignored small .zip file.

**Comment by becausewat** [comment]
The fix for this is to explicitly enable .zip archives in your instance-config.php by appending the line
`$config['allowed_ext_files'][] = 'zip';`
to the end of it.

What I don't understand, is why vichan allows you to upload files that aren't explicitly allowed to be uploaded.
