### ISSUE TITLE
Native support for video files using browser's native player?

### ISSUE THREAD

**Issue by sambuev** [vichan-devel/vichan#197]
Hello VTeam, 
Vichan works great as project management board for me, I can upload many images at the same time in one post, it's great, but I also want to store some videos sometimes, let's say I downloading .mp4 from youtube sometimes, I want to upload them to post and play in regular browser's built in player. Idea is to use simple html5 player. 

How to do it? What kind of modification it needs to be done to catch .mp4 files and make play as embeded-video on the board's page? It would be great modern addition to vichan users.

Thank you.

**Comment by ctrlcctrlv** [comment]
I have no idea what you mean - videos play in browser for me just fine with `webm-settings.js`
