### ISSUE TITLE
How to completely turn off any flood/spam detections?

### ISSUE THREAD

**Issue by sambuev** [vichan-devel/vichan#201]
Hello, Vichan is amazing,
I'm using it as RnD-Boards for projects, it works great. I have closed entire site from everybody, only for my teammates, but sometimes vichan showing: "Flood detection" on some posts, when you posting too fast or by other reasons.

How to turn off flood detection system? Since site is closed fully with password, I don't need any spam or flood detections, how to disable it in vichan?

Thank you.

**Comment by czaks** [comment]
Try: $config['filters'] = array();
This will disable all default filters.

**Comment by sambuev** [comment]
$config['filters'] = array();

still showing me that my post is automated. did not work.

**Comment by ctrlcctrlv** [comment]
Post via `mod.php`.
