### ISSUE TITLE
Reply posts have poor framing

### ISSUE THREAD

**Issue by ChristianCMcKay** [vichan-devel/vichan#204]
For some reason my reply posts have issues with their borders.
![garbage framing](https://cloud.githubusercontent.com/assets/9425050/20955101/089a09a4-bc06-11e6-97df-fb960394ddfa.png)

**Comment by Jeroen52** [comment]
I'm having the same issues.
![chrome_2017-04-16_20-00-59](https://cloud.githubusercontent.com/assets/2915526/25073111/79284ca4-22df-11e7-9167-de7cada723ab.png)

I don't think it was a problem in a previous version, but I didn't check by downgrading.

**Comment by ctrlcctrlv** [comment]
Having trouble duplicating - more info is needed. Closing due to age and lack of duplication.

**Comment by Jeroen52** [comment]
What information do you need?

**Comment by ctrlcctrlv** [comment]
Browser, OS, exact imageposted and exact text posted
