### ISSUE TITLE
Public Logs gives error

### ISSUE THREAD

**Issue by aryasone** [vichan-devel/vichan#207]
I set "$config['public_logs']" to "1" which should enable it, but when anyone goes to a public log page it gives the error "Undefined index: mod_board_log". I have no idea how to fix it, and a quick search through the code gave no help.

**Comment by bakugo** [comment]
Add this somewhere in your config:
``$config['mod']['mod_board_log'] = MOD;``

**Comment by aryasone** [comment]
Yep! That fixed it. That should really be put as a comment somewhere.
