### ISSUE TITLE
Uploads of all kinds not working (Vichan 5.1.3)

### ISSUE THREAD

**Issue by n3rt46** [vichan-devel/vichan#208]
When inserting 
`$config['additional_javascript'][] = 'js/file-selector.js';`
into the "instance-config.php", uploading files fails.

**Comment by czaks** [comment]
make sure you add its dependencies too in a correct order

**Comment by n3rt46** [comment]
Yeah, that was the problem, I was forgetting to also insert the ajax.js as well.
