### ISSUE TITLE
Some themes are not styleable

### ISSUE THREAD

**Issue by czaks** [vichan-devel/vichan#21]
Some themes are not styleable.

Styleable themes are currently:
- ukko
- catalog

A bit styleable theme:
- recent

**Comment by 7chon** [comment]
Old post, but it's currently not only styleable on my imageboard you can choose your own style as well and it saves. Sloppy implementation, but if you inspect index html you should see how I implemented it. Simple, but works.

Basically edit some changes to header in recent.html file in templates, really easy.
