### ISSUE TITLE
Keep Spam from 404ing threads

### ISSUE THREAD

**Issue by aryasone** [vichan-devel/vichan#210]
I had some trouble with manual spam over Tor a few days ago, and I was wondering what happens when a thread is bumped out of the catalog. Luckily there weren't enough threads for that to happen before I stopped it. Are they instantly gone forever, or can they be recovered and put back on the catalog when any spam threads are deleted? Because I don't want to wake up and find most of the threads on my imageboard gone and irrecoverable.

**Comment by deysu** [comment]
Early 404 is a nice feature you can enable. I'm also going to add a function in a PR later which limits threads-per-hour. BTW, if you encountered manual spam from Tor, are you sure you're on the latest commit? The old DNSBL many imageboards are still using is broken, and allows many exit nodes to post.

Sadly, there is no way to recover a thread once it has been bumped off the catalog. The best practice (currently) implemented in vichan is to keep backups, use captcha, and to use early 404.
