### ISSUE TITLE
Creating a wiki?

### ISSUE THREAD

**Issue by PenGentoo** [vichan-devel/vichan#214]
I think adding a wiki to the project would be very beneficial, considering that most of the documentation and tutorials for Vichan/Tinyboard are scattered on Wikia, the Internet archive, config.php, and the help boards set up by @czaks 

I could contribute tutorials such as:

- How to set up a banner system
- How to change your thumbnailer
- How to fix common errors
- How to enable flags for just _one_ board
- And _perhaps_ setting up the Oekaki

Thoughts?

**Comment by AdoptedUsername** [comment]
I think it's a good idea, even just moving some of the information from config.php would probably be useful for new users.

**Comment by ctrlcctrlv** [comment]
I enabled the Wiki tab, feel free to use it if you still want to.
