### ISSUE TITLE
Banned Page Redirect

### ISSUE THREAD

**Issue by n3rt46** [vichan-devel/vichan#217]
When both `$config['recaptcha'] = true;` and `$config['require_ban_view'] = true;`  redirecting to the banned page fails. Instead, users who are banned will receive a "Incorrect CAPTCHA" error, and are never redirected to banned page.

**Comment by H0K4** [comment]
i fixed that i believe is just a simple order bug in post

**Comment by ctrlcctrlv** [comment]
https://github.com/vichan-devel/vichan/commit/b3e16cfa0dc3183cb96196399d942c64be263a60 I think you're right, closing.
