### ISSUE TITLE
Ban list showing nothing

### ISSUE THREAD

**Issue by Megamilkguy** [vichan-devel/vichan#221]
My ban list shows nothing and gives me this error in my web browser console.
https://a.safe.moe/Chbc0.PNG
Is there any way to fix this?

**Comment by sxph** [comment]
That error is reporting a conflict between what your browser is expecting (gzipped JSON) and what it is getting (uncompressed JSON). Just remove this line of code from your /inc/mod/pages.php and rebuild. 

```
// Compress the json for faster loads
if (substr_count($_SERVER['HTTP_ACCEPT_ENCODING'], 'gzip')) ob_start("ob_gzhandler");
```

It will no longer attempt to GZIP the bans list and by extension will not tell the browser to expect gzipped content, removing the conflict.
