### ISSUE TITLE
Tor DNSBL is dead

### ISSUE THREAD

**Issue by animepony** [vichan-devel/vichan#225]
It would appear as though http://tor.dnsbl.sectoor.de/ is no-longer active. Because of this, several Tor IPs are still able to get through and post on the boards. How would you advise the blocking of Tor given this situation?

**Comment by Horija** [comment]
You could enable captcha. 

if you don't like the recaptcha of google you can implement this one: https://github.com/vichan-devel/vichan/pull/224

**Comment by animepony** [comment]
@horija I've tried that, but manual spammers still get through. I'm seeking a way to block all connections from the Tor network. I'll certainly keep your PR in mind though, as I'm not fond of Google's ReCAPTCHA myself.

**Comment by horija** [comment]
Yah i'm not that familiar with dnsbl but what if you replace the url with this one: 
proxies.dnsbl.sorbs.net

I don't know which one to pick though if it works: http://www.sorbs.net/general/using.shtml

other dnsbl blacklist sites: 
http://www.dnsbl.info/dnsbl-list.php

**Comment by horija** [comment]
more info how to add it: 

https://web.archive.org/web/20121003095945/http://tinyboard.org/docs/?p=Config/DNSBL

**Comment by horija** [comment]
Okay so I fixed it with one of these:

```
$config['dnsbl'][] = array('torexit.dan.me.uk', 1); //sectoor.de site is dead. 
	
$config['dnsbl'][] = array('.torexit.dan.me.uk', 1);
	
$config['dnsbl'][] = '.torexit.dan.me.uk';
	
$config['dnsbl'][] = 'torexit.dan.me.uk';

```

Problem is i don't know the correct one lol. I'll check tomorrow.

**Comment by horija** [comment]
$config['dnsbl'][] = 'torexit.dan.me.uk';

That's the correct one

**Comment by horija** [comment]
apparently there is a tor network blacklist also that i was not aware of.

**Comment by animepony** [comment]
Thanks a lot for this @horija
