### ISSUE TITLE
install.php bug

### ISSUE THREAD

**Issue by animepony** [vichan-devel/vichan#229]
How to reproduce:
Copy latest version of vichan-devel to your web directory.

1. Run install.php
2. Evaluate environment
3. Enter MySQL information
4. Click "Complete Installation"

This will return the error 

`Database error: SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)`

You can workaround the error by navigating back to the previous webpage, re-entering the password, and pressing enter while the password field is in focus.

Browsers tested:
Latest versions of Firefox, Chromium, and Pale Moon.

**Comment by antedeguemon** [comment]
Since #247 was merged, this issue should be closed.
