### ISSUE TITLE
Mod Login Issues

### ISSUE THREAD

**Issue by KillerFusky** [vichan-devel/vichan#231]
Every time I try to login to the mod panel after installing vichan I get this error:
`Caught fatal error: Uncaught Error: Call to undefined function mcrypt_create_iv() in /var/www/html/chan/inc/mod/auth.php:73Stack trace:#0 /var/www/html/chan/inc/mod/auth.php(50): generate_salt()#1 /var/www/html/chan/inc/mod/auth.php(89): crypt_password('password')#2 /var/www/html/chan/inc/mod/pages.php(38): login('admin', 'password')#3 /var/www/html/chan/mod.php(189): mod_login()#4 {main} thrown in /var/www/html/chan/inc/mod/auth.php on line 73`

`Fatal error: Uncaught Error: Call to undefined function mcrypt_create_iv() in /var/www/html/chan/inc/mod/auth.php:73 Stack trace: #0 /var/www/html/chan/inc/mod/auth.php(50): generate_salt() #1 /var/www/html/chan/inc/mod/auth.php(89): crypt_password('password') #2 /var/www/html/chan/inc/mod/pages.php(38): login('admin', 'password') #3 /var/www/html/chan/mod.php(189): mod_login() #4 {main} thrown in /var/www/html/chan/inc/mod/auth.php on line 73 `

**Comment by H0K4** [comment]
Don't use php 7.1 or replace mcrypt_create_iv() with random_bytes()

**Comment by H0K4** [comment]
This might work =

```
function generate_salt() {
	// 128 bits of entropy
	return strtr(base64_encode(random_bytes(16)), '+', '.');
}
```
Better to roll back to 7.0 or 5.6 php version though. 5.6 is most stable php version for this script.

**Comment by KillerFusky** [comment]
I use 7.0 and thanks

**Comment by KillerFusky** [comment]
After that I get this `Use of undefined constant MCRYPT_DEV_URANDOM - assumed 'MCRYPT_DEV_URANDOM'` now what?

**Comment by H0K4** [comment]
Maybe check if you have mcrypt enabled in your cpanel or php.ini

**Comment by KillerFusky** [comment]
Fixed.
