### ISSUE TITLE
Users can't post from certain browsers because of referers.

### ISSUE THREAD

**Issue by seisatsu** [vichan-devel/vichan#233]
Some of my users can't post at all from Icecat because they get the error about enabling referers. Apparently Icecat doesn't have referers as a feature, has them disabled by default, or otherwise confuses Vichan. In the first place fuck requiring referers and why do we still have this problem carried all the way from Tinyboard Alpha?

I hear this doesn't occur on Lainchan.jp because they fixed it somehow, but I can't find a relevant setting.

Edit: Nope it happens on Lainchan.jp, the user just has odd conditions somehow. It would still be great if we could use GET requests or something instead of passing information in referers.

**Comment by sambuev** [comment]
Be careful with using this CMS, many critical issues and modern technologies, such as support embedding videos from vimeo, youtube doesn't work correctly especially on mobile devices (they using Flash plugin). 

Think twice if you decide to use this chan, it's very old outdated technologies here.

**Comment by seisatsu** [comment]
What the hell does that have to do with this bug report? This is a bug tracker, it's not a place to shittalk the software in general in a totally unrelated thread.

**Comment by sambuev** [comment]
Nobody cares about your bug reports. 
I have asked 2 years ago to fix one bug with embedded videos, the bug is still there.

**Comment by goosehub** [comment]
@sambuev You could contribute to the project instead of complaining on other peoples bug reports that there's not enough people contributing to the project

**Comment by sambuev** [comment]
I would do my best, unfortunately, at this time, I can only bug report and make complaints about developing process. I really give a hope to this engine, it works well for me but critical bugs have not been fixed and probably will not.

**Comment by antedeguemon** [comment]
I guess that the problem with posting using a browser without referer is at the bot checking/CSRF protection. 
Since vichan relies on HTTP_REFERER in post.php to avoid bots and CSRF at some level, it would be kinda insecure to disable this referer checking, but it could be done by modifying two conditionals at post.php.

**Comment by ctrlcctrlv** [comment]
This will never be fixed. It is extremely insecure to enable the CSRF protection features. You might be tech savvy enough to know what a referer is, but all it takes is someone on your chan making a fake news site with a page that auto-submits to `post.php` something like "I am a pedophile and my IP is $IP".
