### ISSUE TITLE
How to fully disable bot-checks? I getting "Your request looks automated; Post discarded"

### ISSUE THREAD

**Issue by sambuev** [vichan-devel/vichan#235]
Hello, I have my borads closed from everybody, I only use it for my personal projects, no one knows URL address, but I cannot do postings 90% of the time it's showing me error:

Your request looks automated; Post discarded

How to disable this filter? Fully off, open it for bots and other things, I don't need internal checkings. I did all my best, unicode false, but still getting this error.

**Comment by ev1l0rd** [comment]
Post through mod.php . I know that bypasses any spam checks for sure. 

Also, try lowering `$config['flood_time']`, `$config['flood_time_ip']`, `$config['flood_time_same']` to 1. Those control discarded posts due to flooding.

**Comment by animepony** [comment]
NPFchan developer implemented this function in this commit:
https://github.com/fallenPineapple/NPFchan/commit/0f2aded186618fb69b40650ccb750830c974acfc

**Comment by sambuev** [comment]
I still getting it!

**Comment by ctrlcctrlv** [comment]
Follow directions.
