### ISSUE TITLE
Board doesn't exist when rebuilding

### ISSUE THREAD

**Issue by wirmwirmwirm** [vichan-devel/vichan#236]
Whenever I delete a board after a period of time and try to rebuild, I get an error that reads "Board (name) doesn't exist". It appears the only way to bypass this error is to recreate that board, but I need a way to delete a board and still rebuild the others.

**Comment by animepony** [comment]
Remove the board in question from the list of boards in the catalog theme.

For example, if you originally had the boards a, b, and c, and you deleted c, you would need to remove c from the catalog theme.

**Comment by wirmwirmwirm** [comment]
yo thanks :P
