### ISSUE TITLE
Installing with Git - "Table 'vichan.boards' doesn't exist"

### ISSUE THREAD

**Issue by wirmwirmwirm** [vichan-devel/vichan#237]
Trying to install with Git, I get an error when I use install.php afterwards: "Table 'vichan.boards' doesn't exist". Apparently, something's messed up with MySQL in the Git installation. Can anyone figure out what's causing this?

**Comment by animepony** [comment]
Odd, I've never encountered this before. If the error persists, I'd say to do something like:
`mysql -uyourname -pyourpass databasename < install.sql`

then login to mod.php and delete the auto-created /b/ board and make it again if you wish

What MySQL server are you using? Are you using MariaDB?

**Comment by wirmwirmwirm** [comment]
I'm using the standard phpMyAdmin with XAMPP

**Comment by H0K4** [comment]
Yeah I'm having it also in xampp php 7.0.18 weird thing is that it doesn't give me an error when I download the zip and extract it to my install directory. 

Anyways you can just import the sql file from the root in your database

**Comment by wirmwirmwirm** [comment]
Ah ok, so apparently the SQL file doesn't download from a git installation, odd. I'll try that out, thanks.
