### ISSUE TITLE
Many error in version 5.1.4

### ISSUE THREAD

**Issue by 27chan** [vichan-devel/vichan#243]
This version has many bugs.

1. Can't report threads and replys, retorn this error:
`strlen() expects parameter 1 to be string, array given`
I think fix this error, please check my request.

2. Autoupdate doesn't work.

3. List ban error in tables:
http://i.imgur.com/jPDBy3J.png

4. After this update, i need select several times imgs/webm for upload in posts.

**Comment by czaks** [comment]
Ok, jquery downgrade to 2.x should have fixed those. It was upgraded to 3.x
recently and there are some incompatibilities.
