### ISSUE TITLE
How to stop renaming files after upload?

### ISSUE THREAD

**Issue by sambuev** [vichan-devel/vichan#244]
Hello, I want to exchange files over the board, I want to keep the original name of the file, which files to modify to keep the names? Currently, there are random symbols in the filename.

**Comment by ev1l0rd** [comment]
Enable `download-original.js` in `instance-config.php` by adding these lines:

    $config['additional_javascript'][] = 'js/jquery.min.js';
    $config['additional_javascript'][] = 'js/download-original.js';

You may have to rebuild your board in mod.php

Those random symbols are the file hash, which is used to identify your file on the server.

**Comment by goosehub** [comment]
Keep in mind there are some potential attacks that involve unfiltered filenames. Do some research and perhaps consider stripping out certain characters.
