### ISSUE TITLE
Error - "Column count doesn't match value count at row 1"

### ISSUE THREAD

**Issue by staycomfywirm** [vichan-devel/vichan#249]
Posting as admin/anon after updating to version 5.1.4 gets me this, any fix?

**Comment by ctrlcctrlv** [comment]
Did you run `install.php` again, which would have updated your SQL schemas?

**Comment by ctrlcctrlv** [comment]
No reply.

**Comment by staycomfywirm** [comment]
oh hey HW, sorry I didn't see that you replied, I haven't done that, and yes I suppose I could try.
