### ISSUE TITLE
How to add index page with all boards showing up 

### ISSUE THREAD

**Issue by Alionides** [vichan-devel/vichan#251]
i want to add a index.php with all boards showing up.

**Comment by sambuev** [comment]
Just modify existing theme and leave only stuff you need, there are couple templates you can use for that.

**Comment by Alionides** [comment]
so i need to create it manually or in vinchan has something in the mod file to create?

**Comment by Alionides** [comment]
so where i need to upload index page or modified template index.php? can you help me plz? 


Sincerely Shikhiyev Ali.



On Tuesday, August 22, 2017, 10:48:08 PM GMT+4, sambuev <notifications@github.com> wrote:


Just modify existing theme and leave only stuff you need, there are couple templates you can use for that.

**Comment by M1D0R1** [comment]
Just install the theme you want and change the HTML file to index.html. 

if you want to add boards on a theme just add them manually with html and css code.

```
<!-- Add your boards -->
	<div class="box-wrap-board">	
			<div id="contentBox">
			<h4> 
				<div id="column" style="float:left; margin:0; width:33.33%;">
					<ul>
						<!-- Add left boards
						<li><a href="{{ config.root }}a/" title="...">Anime & Manga</a></li> -->
					</ul>
                </div>
			    <div id="column" style="float:left; margin:0; width:33.33%;">
					<ul>
						<!-- Add center boards -->
						<li><a href="{{ config.root }}b/" title="Anything you want.">Random</a></li>
					</ul>
				</div>
				<div id="column" style="float:left; margin:0; width:33.33%;">
					<ul>
						<!-- Add right boards
						<li><a href="{{ config.root }}pol/" title="...">Politically Incorrect</a></li> -->
					</ul>
				</div>
			</h4>
			</div>
	</div>	
```


```
#column1,#column2,#column3 {
	background: #efe;
	color: #060;
	float:left;
	margin:0;
	width:33.236%;
	}
/* Board Link Collumns */
.column1 {
	border-left: 1px solid #060;
	border-bottom: 1px solid #060;
	}
.column2 {
	border-bottom: 1px solid #060;
	}
.column3 {
	border-right: 1px solid #060;
	border-bottom: 1px solid #060;
	}

```

**Comment by Alionides** [comment]
I installed theme but it doesnt appear anywhere. i want when i enter main url site works. but for that i need to enter boards. can u help me? 

Sincerely Shikhiyev Ali.



On Friday, August 25, 2017, 12:12:15 AM GMT+4, M1D0R1 <notifications@github.com> wrote:


Just install the theme you want and change the HTML file to index.html.

if you want to add boards on a theme just add them manually with html and css code.

	<div class="box-wrap-board">	
			<div id="contentBox">
			<h4> 
				<div id="column" style="float:left; margin:0; width:33.33%;">
					<ul>
						
					</ul>
                </div>
			    <div id="column" style="float:left; margin:0; width:33.33%;">
					<ul>
						
						<li><a href="{{ config.root }}b/" title="Anything you want.">Random</a></li>
					</ul>
				</div>
				<div id="column" style="float:left; margin:0; width:33.33%;">
					<ul>
						
					</ul>
				</div>
			</h4>
			</div>
	</div>	
#column1,#column2,#column3 {
	background: #efe;
	color: #060;
	float:left;
	margin:0;
	width:33.236%;
	}
/* Board Link Collumns */
.column1 {
	border-left: 1px solid #060;
	border-bottom: 1px solid #060;
	}
.column2 {
	border-bottom: 1px solid #060;
	}
.column3 {
	border-right: 1px solid #060;
	border-bottom: 1px solid #060;
	}
