### ISSUE TITLE
Update mod.php for PHP 7.1 support

### ISSUE THREAD

**Issue by staycomfywirm** [vichan-devel/vichan#253]
mod.php seems to be broken when running on PHP 7.1, I suggest someone to update it to work and check out any other files on here to be sure they work on 7.1 too.

**Comment by LZZZZ** [comment]
I just had to replace the deprecated `mcrypt_create_iv(16, MCRYPT_DEV_URANDOM)` with `random_bytes(16)` in the auth.php file.

**Comment by ctrlcctrlv** [comment]
Submit a PR.
