### ISSUE TITLE
Looking for freelancer to make simple html5 mp4 player upload

### ISSUE THREAD

**Issue by sambuev** [vichan-devel/vichan#254]
Hello, I love vichan very much, unfortunately some functions are missing, I have asked for html5 player in 2015, still no progress, I have simple vichan boards, I want to be able to upload video files in mp4, mov to be able to play directly from the boards using simple html5 player, it doesn't have to convert videos, I just want to keep these videos on my page. Video size is very small, around 100Mb each. 
I looking for a freelancer who is capable to work with vichan and make me html5 player with a simple design. 

Please contact me if you can do it, thank you!

**Comment by M1D0R1** [comment]
I believe i did that in my old hokachan script. wasn't too hard. only need to remove the ffmpeg inc folder and change the image.html. it no longer creates a static image for that video though.

**Comment by sambuev** [comment]
How much would it be to send the files that I need to place in some folders? If you can, please text me!

**Comment by M1D0R1** [comment]
i'll send it for free in a pull request.  in the next couple of days. just implement it at your own risk.

**Comment by M1D0R1** [comment]
here you go. 

https://github.com/vichan-devel/vichan/pull/255

my function.php file has been altered a lot but I guess that all you need to remove from there. that's the only doubts i have with this modification. just note that this no longer makes an image file for mp4 or webm.

**Comment by ctrlcctrlv** [comment]
This is not oDesk or eLance. Almost every browser has native support for MP4. MOV is terrible.
