### ISSUE TITLE
Unique IDs

### ISSUE THREAD

**Issue by goldbolt** [vichan-devel/vichan#258]
Is there a way to assign a unique ID to a specific IP (like TOR posters)?

**Comment by ctrlcctrlv** [comment]
Redefine `poster_id` ( https://github.com/vichan-devel/vichan/blob/master/inc/functions.php#L2407 )

Or add it to the template ( https://github.com/vichan-devel/vichan/blob/master/templates/post/poster_id.html )

Or add a new config option which will be an array of `$ip => $poster_id` and refer to it in (1) or (2).

**Comment by goldbolt** [comment]
Forgive my extreme amateurishness but I am unable to figure out how to do any of that, even with slight coding knowledge. 

Adding 

`ID: <span class="poster_id">{{ 127.0.0.1|poster_id(00000) }}</span>`
`if ($id = event('poster-id', '127.0.0.1', $thread))
		return '00000';`
or anything of the like to either of those files does either nothing or just breaks everything. 
Have a solution?

**Comment by ctrlcctrlv** [comment]
The first one looks like a template edit. Look at the other templates, you have to use `{%if%}`.

The second one is an incorrect use of the `event()` function.
