### ISSUE TITLE
How to update 2 years old vichan to the newest version?

### ISSUE THREAD

**Issue by sambuev** [vichan-devel/vichan#261]
Hello, I have installed vichan 2 years ago and have modified a lot of functions in the template, how can I update only the core of vichan without hurting the modification I have made?

**Comment by M1D0R1** [comment]
backup your instance-config and board folder. export database tables. you need to alter your database so you can import your old database into the new one just add the tables that aren't added and remove the ones you no longer need..

**Comment by sambuev** [comment]
I don't know much how to work with a database, all I can do it replace the files hoping they going to catch the database again. 
Okay, for now, I can make a backup of my site (html) and probably a backup of the MySQL database. Then try to replace it if something goes wrong I can always revert back.

**Comment by M1D0R1** [comment]
you need to click on a database table. then you see a tab called structure click on that. there you see all the columns of the database. you need to compare both database structures with each other and remove or add the one from the new database.

**Comment by M1D0R1** [comment]
the rest is simple you only need to import your board folders instance config

**Comment by goosehub** [comment]
Do you have PHPMyAdmin or some other point and click interface?

**Comment by ctrlcctrlv** [comment]
"functions in the template" - what does this even mean

**Comment by sambuev** [comment]
it means, I have changed the template design and UI and added some custom code.

**Comment by ctrlcctrlv** [comment]
OK. So, unfortunately, with your level of skill (as evidenced by other issues you've opened), you have **no easy upgrade path** and I don't have time to help you upgrade for free.

For more advanced users arriving here via Google, if you have a woefully out of date instance of vichan, this is your upgrade path:

1. Back up _everything_! Copy the entire directory vichan is installed in. Copy the MySQL database.
2. If you've been committing your changes to the software in a private branch, _good, you're doing it right!_ Go to step 4.
3. If you've been lazy like I assume @sambuev is, and you've not received vichan via Git, you have a big job to do. Clone vichan directory in a new directory. Find the revision vichan was at when you started hacking and slashing it up and not committing your changes upstream, and use Git to revert to that revision. For every file you've changed, diff the file and _THE REVISION OF VICHAN THAT WAS HEAD WHEN YOU ORIGINALLY CLONED IT_. Don't diff it and the latest version. Collect the diffs in text files. These are all of your changes. Fast-forward Git to the latest revision, then apply all of your changes again manually. Next time use Git to manage your changes...seriously! Go to step 6.
5. If you've **only** made changes to `instance-config.php` and **only** added files (such as stylesheets or new templates), go to step 6.
6. `git pull`, run `install.php` to update your DB schema. If you didn't receive vichan via Git but you still followed step (5), copy your `instance-config.php` into your new directory you received via Git, along with any other files you added.
7. Hopefully everything completed OK. If not - read the source code to figure out why. Look at `install.php` to see which schema changed. Do the legwork yourself, then open an issue with the exact problem which caused your upgrade to fail.

If you don't understand everything I wrote above you're not skilled enough to pull this off and you require help. Pay someone.
