### ISSUE TITLE
Looking for the freelancer to update old vichan to the newest

### ISSUE THREAD

**Issue by sambuev** [vichan-devel/vichan#263]
Hello, I looking for somebody to update 2 vichan boards with the new versions.
Who is able to do it? I need to refresh the code and probably do some minor adjustments.
Please help! 
Thank you.

**Comment by deysu** [comment]
...You were already told this wasn't eLance before. I'll help you out for free but I can't make any promises about things working. Do you have an IRC channel I can contact you in? 

If you need freelancing, use eLance or something, not the Github issue tracker. It is for tracking issues with the software.

**Comment by ctrlcctrlv** [comment]
Indeed. If you open another issue for the same topic as an issue I previously closed, I will ban you from this bugtracker.
