### ISSUE TITLE
Certain webm files fail to upload.

### ISSUE THREAD

**Issue by deysu** [vichan-devel/vichan#265]
Here is an example of an effected file. I suspect this to be an issue with encoding, although I haven't looked into that (a bit outside of my technical knowledge)
https://my.mixtape.moe/tknvbz.webm

If you attempt to upload this webm file as a reply, the board software will seemingly ignore it - If there is any text, it will be posted. If you attempt to upload this webm as the opening post's file, vichan will output the following error: `You must upload an image.`

Many webm files upload fine. Here is my instance-config.php's values related to webm files. I have reproduced this on 3 completely clean vichan installations, with various different configurations. This most recent one was for the testing of this issue in particular.
```
        $config['allowed_ext_files'][] = 'webm';
        $config['additional_javascript'][] = 'js/webm-settings.js';
        $config['additional_javascript'][] = 'js/expand-video.js';
        $config['webm']['use_ffmpeg'] = true;
        $config['webm']['allow_audio'] = true;
```

**Comment by ctrlcctrlv** [comment]
`ffprobe` doesn't show any obvious problem with the WEBM 

```
$ ffprobe.exe tknvbz.webm
ffprobe version N-84348-gdb7a05d Copyright (c) 2007-2017 the FFmpeg developers
  built with gcc 6.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-zlib
  libavutil      55. 50.100 / 55. 50.100
  libavcodec     57. 83.101 / 57. 83.101
  libavformat    57. 66.105 / 57. 66.105
  libavdevice    57.  3.100 / 57.  3.100
  libavfilter     6. 78.100 /  6. 78.100
  libswscale      4.  3.101 /  4.  3.101
  libswresample   2.  4.100 /  2.  4.100
  libpostproc    54.  2.100 / 54.  2.100
Input #0, matroska,webm, from 'tknvbz.webm':
  Metadata:
    title           : IMG_2598
    encoder         : Lavf55.36.101
  Duration: 00:00:03.37, start: 0.033000, bitrate: 6169 kb/s
    Stream #0:0(eng): Video: vp8, yuv420p, 720x720, SAR 1:1 DAR 1:1, 30 fps, 30 tbr, 1k tbn, 1k tbc (default)
```

I'll try to find time to debug this in more detail to find the problem.

**Comment by ctrlcctrlv** [comment]
Bug confirmed with HEAD on FreeBSD 11.1-RELEASE-p2. I'll patch it shortly.

**Comment by ctrlcctrlv** [comment]
**[40 minutes later]**

You've found an extremely interesting edge case - the software really doesn't like this file, the error happens much earlier in post handling than I expected. . .

**Comment by ctrlcctrlv** [comment]
I figured it out...it's still a bug in our code for not catching the error returned by PHP properly though.

**Comment by ctrlcctrlv** [comment]
You need to increase your `upload_max_filesize` to above the maximum size in `inc/instance-config.php`. I added an error message to catch all errors in the `$_FILES` array.

![screenshot at 2017-11-03 21-44-51](https://user-images.githubusercontent.com/838783/32377576-1cfc45f0-c0e3-11e7-839f-0b5d0d04f49f.png)
![screenshot at 2017-11-03 21-45-02](https://user-images.githubusercontent.com/838783/32377578-1d3c68ec-c0e3-11e7-89bb-96f3345a6e91.png)
