### ISSUE TITLE
Error outputted randomly on thread creation and replies -- Filter related?

### ISSUE THREAD

**Issue by deysu** [vichan-devel/vichan#271]
`array_filter() expects parameter 1 to be array, string given`
On new threads and replies, occasionally. It seems to happen completely randomly, and is hard to reproduce. My full `inc/instance-config.php` is over [here](https://pastebin.com/AMLYhLrw) and I'm running on commit  c2f7073. I don't *think* it's related to filters, as I've both cleared out the filters array and I've bypassed the antibot by posting via `mod.php`, where this still appears for some reason. I'm stumped.

**Comment by ctrlcctrlv** [comment]
Can you get the filename & line number for me?

**Comment by H0K4** [comment]
Might have something to do with the updated Jquery that Czaks did. messed up with a bunch of JS files. Not sure though. try to upload jquery 2.1.1. and see if that fixes it. Don't use filters personally.

**Comment by deysu** [comment]
And here I thought those JavaScript issues I was running into were related to my load order...
I'm currently trying to reproduce this, potentially not related to this bug but I did find this error outputted when exiftool isn't installed (which was the case for my host). Need to do further debugging.

Error outputted to user: Illegal string offset 'backtrace'
Expected behaviour: "Could not strip EXIF metadata! Install exiftool."

```
Array
(
    [file] => /var/www/html/inc/display.php:94
    [errno] => 2
    [error] => Illegal string offset 'backtrace'
    [backtrace] => Array
        (
            [0] => Array
                (
                    [file] => /var/www/html/inc/functions.php
                    [line] => 387
                    [function] => error
                    [args] => Array
                        (
                            [0] => Illegal string offset 'backtrace'
                            [1] => 1
                            [2] => Array
                                (
                                    [file] => /var/www/html/inc/display.php:94
                                    [errno] => 2
                                    [error] => Illegal string offset 'backtrace'
                                    [backtrace] => Array
                                        (
                                            [0] => Array
                                                (
                                                    [file] => /var/www/html/post.php
                                                    [line] => 959
                                                    [function] => error
                                                    [args] => Array
                                                        (
                                                            [0] => Could not strip EXIF metadata!
                                                            [1] => 
                                                            [2] => sh: 1: exiftool: not found
                                                        )

                                                )

                                        )

                                )

                        )

                )
```

**Comment by deysu** [comment]
Hmm... It appears the installation of exiftool solved my problem. I'll close this issue, and if I run into it again I'll re-open it with any relevant information I discover.
