### ISSUE TITLE
Deprecated bans.php page

### ISSUE THREAD

**Issue by antedeguemon** [vichan-devel/vichan#272]
It seems that the file [inc/mod/ban.php](https://github.com/vichan-devel/vichan/blob/master/inc/mod/ban.php) is no longer necessary, as it is an empty file apart from a integrity check to avoid direct requests.
There are only two references to this file in the whole project. Both are requires at [inc/mod/pages.php](https://github.com/vichan-devel/vichan/blob/master/inc/mod/pages.php):
- [Line 899 in mod_ban()](https://github.com/vichan-devel/vichan/blob/master/inc/mod/pages.php#L899)
- [Line 1470 in mod_ban_post()](https://github.com/vichan-devel/vichan/blob/master/inc/mod/pages.php#L1470)

There will be no implication at inc/mod/pages.php if ban.php and its references are deleted since pages.php itself has a integrity check.

**Comment by ctrlcctrlv** [comment]
I see no reason to fix this.

If it ain't broke, don't fix it.
