### ISSUE TITLE
Feature request - email notification

### ISSUE THREAD

**Issue by sambuev** [vichan-devel/vichan#277]
Hello, I want users to be able to subscribe to the board. I have created board to constantly update with some new posting and stuff, but I also want some visitors who left their email send them posts once a day with all board updated and ability to unsubscribe. 

Please add this functions, this way many users will come back to the board and easily follow the thread. 

Thank you.

**Comment by ctrlcctrlv** [comment]
Feature request rejected as a feature to be added to core - this is an imageboard software, not a blogging software.

Nevertheless, if you want to implement this for your own private use, it should not be so hard to do. 

Add an `event_handler('post-after')` in your `inc/instance-config.php` to send email. Probably not much harder than using [PHP's `mail` function](http://php.net/manual/en/function.mail.php).
