### ISSUE TITLE
Default name in russian language is invisible

### ISSUE THREAD

**Issue by Darktrader** [vichan-devel/vichan#280]
When I tried to change the default name _Anonymous_ to any russian name, it has become absolutely invisible in those new posts with this new name.

**Comment by ctrlcctrlv** [comment]
Post your config. Make sure you are saving the config file in UTF-8 and not any codepage (such as Windows-1251).

**Comment by Darktrader** [comment]
> you are saving the config file in UTF-8
This. Sorry, my mistake. I forgot to save it in UTF-8 codepage.
