### ISSUE TITLE
Importing some extra features from OpenIB

### ISSUE THREAD

**Issue by Darktrader** [vichan-devel/vichan#281]
According to my knowledge, OpenIB has at the moment more configurable features than vichan. For instance it can automatic bumlock threads after certain amount of time (which you set in board config) or even give you a possibility to hide thread directly from catalog. So, maybe we need to import those changes from OpenIB?

**Comment by ctrlcctrlv** [comment]
Feel free to backport any changes from OpenIB/infinity.
