### ISSUE TITLE
Cannot redeclare imagecreatefrombmp()

### ISSUE THREAD

**Issue by ba3bous** [vichan-devel/vichan#282]
i am getting this error "Fatal error: Cannot redeclare imagecreatefrombmp() in vichan/inc/image.php on line 584" with php 7.2 any known fix?

**Comment by ba3bous** [comment]
also mcrypt_create_iv is removed in 7.2.0

**Comment by mateuszosuch** [comment]
Can't run script at the moment to check it out, but let me ask you first:

Isn't it indicated where it has been declared already?
Have you checked if image.php is required once all over?
Have you tried to work with function_exists() and override_function()?

**Comment by ctrlcctrlv** [comment]
Sorry this took so long to get fixed. I thought you were just missing `gd` so ignored your bug because I thought you were just doing something wrong. This is fixed in https://github.com/vichan-devel/vichan/commit/b078ffb1e4d310b188bc2f440c06567e1ffd3a5a
