### ISSUE TITLE
install.php generates insecure salts

### ISSUE THREAD

**Issue by ctrlcctrlv** [vichan-devel/vichan#284]
_Note: My last write-up was deleted because the user who created the issue rudely deleted the issue which contained the parent comment. When they deleted the issue, my announcement, a child comment, was also deleted. @ipleak102392 acted extremely obnoxiously and trollishly in this regard, so I apologize for his lack of etiquette._

On January 11, 2018, a reporter named Joseph Cox was contacted by Einar Otto Stangvik (@einaros), who via an unnamed source, received a large cache of user IDs from Anon-IB. He discovered a weakness in vichan's code, dating back to 2012, commit https://github.com/vichan-devel/vichan/commit/c9423a2c34a5b93bf9cf2c506acca713781e60b6.

https://www.thedailybeast.com/top-us-government-computers-linked-to-revenge-porn-site
>But Einar Otto Stangvik, a security analyst at Norwegian newspaper VG, provided The Daily Beast with a large cache of hundreds of thousands of Anon-IB users’ IP addresses—numerical codes that can show where a user is posting from. A source showed Stangvik a trick for pulling IP addresses from Anon-IB, and Stangvik subsequently wrote a series of scripts to optimize the process and successfully grab the data. Stangvik said the data was obtained legally, and he also helped The Daily Beast analyze the results.

Thanks partly to Moore's law, and the use of an insecure PHP randomness function (`rand`), @einaros was able to use, I assume, rainbow tables to figure out the salt, then he was able to simply check the SHA1 hashes of the salt he figured out appended to all IP addresses (all 32-bit values), and he was able to get the IPs attached to all posts on Anon-IB. 

I contacted him asking how he did it, and at first got no response, but after some insistence he, along with his mysterious source "M", helped me figure out the above.

I will soon:tm: push a commit which will patch this issue for new installations of vichan. However, it is impossible for me to do this in a clean way for existing vichan users, because if I have `install.php` overwrite your tripcode salt, all tripcodes on your board will change; and it's quite possible that you have a secure tripcode salt.

So, therefore, I advise all administrators of vichan imageboards to immediately do any of the following *if they are using the secure tripcode salt generated by install.php, which is the default. If you don't know what this means, you are affected.*

1. In `inc/instance-config.php`, reset `$config['cookies']['salt']` and `$config['secure_trip_salt']` to a long random string. You can generate this string via many methods: just make sure it is cryptographically secure. The best thing to do is use the command `< /dev/random tr -dc [:print:] | head -c${1:-128};echo;`. If that is unavailable to you, perhaps use random.org or `pwgen -s`.
2. If you do not want to do (1), because it will make all secure tripcodes (trips starting with ##) on your board change, you must disable user IDs on all boards on your site. Note that because of this bug it is now much easier to crack secure tripcodes, so I really recommend (1).

If you are a user of a vichan imageboard, please show your admin this warning. Infinity based imageboards, because they do not have `install.php`, and expect users to set their salts manually as shown above, are not affected. But this is a good reminder to them to use secure salts - don't just use the default in `inc/config.php`!

**Comment by Cipherwraith** [comment]
For anybody curious, 8chan uses a long random string for a salt and should be unaffected by this security bulletin.

**Comment by StephenLynx** [comment]
Sorry for crashing here with a completely unrelated comment, but how would be a reliable way to contact both or you?

**Comment by odilitime** [comment]
openib isn’t affected I take it since it’s based on infinity?

**Comment by ctrlcctrlv** [comment]
@StephenLynx My email can be found in README.md.

@odilitime Correct - infinity has a very different install procedure than vichan. vichan installation is based on version numbers, while infinity is rolling release, and you install it by initializing the database yourself, installing all the configs yourself and generating the salts yourself (as advised in the comments of infinity's `inc/secrets.php`). Infinity and OpenIB have no `install.php`, because I removed it years ago from infinity since I did not want to maintain a stable release.

**Comment by ctrlcctrlv** [comment]
I'm going to leave this issue open for 30 more days because https://github.com/vichan-devel/vichan/commit/693fa1bdfae32bb610a28c38794e7a43e7680c48 is only a partial fix. After that, I will assume that all existing users have seen this, and I will close it.

**Comment by ev1l0rd** [comment]
So for clarification, this does not affect me if it's for a private instance of vichan? Like a vichan install that is only exposed to my local network.

**Comment by goosehub** [comment]
@ev1l0rd if it's only on your local network, and your local network is secure, then security vulnerabilities in software should almost never matter, in theory at least, and unless the software itself is malicious of course.

**Comment by ev1l0rd** [comment]
@Goose - Thanks for clarifying. That said, I do prefer to keep up-to-date with having it secure. Although I do keep track on what devices are on it most of the time, you never know who shares the WiFi password to their friends.

**Comment by ctrlcctrlv** [comment]
@ev1l0rd I have no idea why you would run vichan on your local network, but you are not affected, no. Only instances which are online are affected, since this is an IP leak issue.
