### ISSUE TITLE
dude help me, pls

### ISSUE THREAD

**Issue by 3cbb53c73415ba373448c11dacc69b05** [vichan-devel/vichan#285]
# **Forbidden**

You don't have permission to access / on this server.
Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by 3cbb53c73415ba373448c11dacc69b05** [comment]
I put the correct /

/home/userx/public_html/

**Comment by ctrlcctrlv** [comment]
Vichan does not create a home page by default. There is no `index.html`, and you have directory indexes disabled, that's why you receive the error.
