### ISSUE TITLE
MultiDelete feature request for Mods/Admin

### ISSUE THREAD

**Issue by Darktrader** [vichan-devel/vichan#286]
Hi. Can you add a feature for staff which give a possibility to delete several posts or/and threads at the same time. Like it was in outdated kusaba script. Please, **not** confused with "delete all posts from same IP" button. Thanks.

**Comment by ctrlcctrlv** [comment]
>Can you add a feature 

No, you can and submit a PR, though. If you don't know how you can pay someone. I only work on security patches at this late date.
