### ISSUE TITLE
You don't have permission to access /post.php on this server

### ISSUE THREAD

**Issue by RaySajuuk** [vichan-devel/vichan#292]
Hi,
I am having issue with my newly installed vichan. I am unable to post new topic on the board. tried to created new board, but every time when I click "New Topic" it shows me:
Forbidden

You don't have permission to access /post.php on this server.
Additionally, a 400 Bad Request error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by AirForce11** [comment]
did you chmod every file to 777? try that.

**Comment by RaySajuuk** [comment]
yes I tried it

**Comment by RaySajuuk** [comment]
Originally all directories are 775 and files are 664.

**Comment by RaySajuuk** [comment]
oh, forgot to mention that my domain is in HSTS list. So everything is accessed via https. and I have valid wildcard SSL certificate.

**Comment by AirForce11** [comment]
what errors did you get while you ran install.php? Make sure that you have installed any dependencies. also, try a restart. completely delete the user and database, make a brand new database. re- upload vichan from scratch after you delete everything. also if you have cpanel make sure you are running php version 7.0 if possible. the current install seems to work best on 7.0, not 7.1 or 7.2

**Comment by AirForce11** [comment]
if you have this error:::
You don't have permission to access /ib/b/ on this server.
Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.

the.htaccess file can cause this error. Specifically, the following code will cause the above error.

in the.htaccess---  
<Files ~ "\.html$">
Order allow,deny
Deny from all
</Files>
what that .htaccess file does is if you are not logged in as a mod or admin, you get the error message and are unable to see the page.

**Comment by AirForce11** [comment]
ill keep checking in. need to know php version, mysql version, and the exact error messages when you run install.php.   also what company hosting are you on?

**Comment by AirForce11** [comment]
oah wait, ----------if files are 664 like you say, thats the prob. php files have to be 755 or to be safe make every single file 777

**Comment by RaySajuuk** [comment]
OK, I have just changed my PHP version back to 7.0. I reinstalled the application. The only thing showing in the environment check is:
" Warning: (Optional) `gifsicle` was not found or executable; you may not use `convert+gifsicle` for better animated GIF thumbnailing.

" Warning: (Optional) `/sbin/md5` was not found or executable; file hashing for multiple images will be slower. Ignore if not using BSD. 


Sincerely,

Boran Li
arbalest@me.com

**Comment by RaySajuuk** [comment]
PHP Version	5.4.45
MySQL Version	10.1.31-MariaDB-cll-lve

No error message when running install.php, only 2 warnings:

" Warning: (Optional) `gifsicle` was not found or executable; you may not use `convert+gifsicle` for better animated GIF thumbnailing.

" Warning: (Optional) `/sbin/md5` was not found or executable; file hashing for multiple images will be slower. Ignore if not using BSD. 


Sincerely,

Boran Li
arbalest@me.com

**Comment by RaySajuuk** [comment]
I have changed everything to 777. Still not working.

Sincerely,

Boran Li
arbalest@me.com

**Comment by AirForce11** [comment]
oah i forgot to mention there is stuff posted about mod security conflicting with vichan. also if you make a .htaccess containing the following code it re creates the error code unless one is signed in as a mod...

<Files ~ "\.html$">
Order allow,deny
Deny from all
</Files>

**Comment by RaySajuuk** [comment]
I tried to add the htaccess file, and I got 500 error after that.
BTW the hosting I'm using is Namecheap. I don't think I can change the mysql version tho.
From installation, all the tables are there and no errors.

**Comment by AirForce11** [comment]
sorry, i never used namecheap for hosting so i cant tell you if vichan works on namecheap. How did it work out, did you get it installed?

**Comment by RaySajuuk** [comment]
No, installation is fine. The only problem is I can post new topic. Everything else including mod.php are working fine.

**Comment by RaySajuuk** [comment]
The server is running LiteSpeed V6.11

Server API	LiteSpeed V6.11
Virtual Directory Support	disabled
Configuration File (php.ini) Path	/opt/alt/php70/etc
Loaded Configuration File	/opt/alt/php70/etc/php.ini
Scan this dir for additional .ini files	/opt/alt/php70/link/conf
Additional .ini files parsed	/opt/alt/php70/link/conf/alt_php.ini
PHP API	20151012
PHP Extension	20151012
Zend Extension	320151012
Zend Extension Build	API320151012,NTS
PHP Extension Build	API20151012,NTS
Debug Build	no
Thread Safety	disabled
Zend Signal Handling	disabled
Zend Memory Manager	enabled
Zend Multibyte Support	provided by mbstring
IPv6 Support	enabled
DTrace Support	disabled
Registered PHP Streams	https, ftps, compress.zlib, compress.bzip2, php, file, glob, data, http, ftp, zip, phar
Registered Stream Socket Transports	tcp, udp, unix, udg, ssl, sslv3, tls, tlsv1.0, tlsv1.1, tlsv1.2
Registered Stream Filters	zlib.*, bzip2.*, convert.iconv.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk, mcrypt.*, mdecrypt.*


Sincerely,

Boran Li
arbalest@me.com

**Comment by ctrlcctrlv** [comment]
Vichan is still accepting patches, but there is at the moment no active development besides fixing security problems as they emerge. *Given the lack of active development, we strongly urge you to consider other imageboard packages. It is the opinion of the vichan development team that no new vichan imageboards should be deployed, and other imageboard packages, such as lynxchan, used instead.*

You're obviously doing something wrong, since other vichan boards are working fine. Try learning about how Unix permissions work, setting folders 777 willy nilly is insecure.
