### ISSUE TITLE
`$config['board_locked']` has no effect

### ISSUE THREAD

**Issue by ghost** [vichan-devel/vichan#293]
when i set the board lock to true in the config file, it locks all boards and one has 2 b signed in. When i put a config file per board that says borard lock false, the board is still locked. I tried every variable i could think of, like unlocking the boards then trying to lock a single one with a the config.php on a per board basis. Is it possible to lock some boards and not all??? it does not seem to be working. thanks

**Comment by ctrlcctrlv** [comment]
User deleted own account. I'm not even really sure if what this issue is about is possible, if it's possible to lock a single board.

**Comment by Hisu0** [comment]
Actually, there's been a problem with that setting for me as well. Including the $config['board_locked'] = false; into a /board/config.php doesn't seem to work, non-mods still can post in that board.

**Comment by ctrlcctrlv** [comment]
@athene-noctua Like I said, it's not possible to lock a single board. It's all boards or nothing.

**Comment by ctrlcctrlv** [comment]
@athene-noctua Obviously setting `board_locked` to _false_ wouldn't work, you must set it to _true_.

**Comment by athene-noctua** [comment]
@ctrlcctrlv Yes, sorry, I meant setting it to true.

**Comment by ctrlcctrlv** [comment]
Got it. It doesn't work for me either. Reopening.

**Comment by Circlepuller** [comment]
It's because it checks for `$config['board_locked']` before `$board` is set.
Calling `loadConfig()` after doing an `openBoard()` should fix this.

**Comment by OrcasIsland** [comment]
I am the original op on this... did anyone fix it? It would be so cool to lock some boards to only mod posting and leave other boards open.

**Comment by Circlepuller** [comment]
Since my fork of this software at this point varies quite a bit from vichan, I have my fix for this repo here: https://gist.github.com/Circlepuller/7dc270ae69c81d036dd6051736a2d2b8

In a nutshell, it's just moving the conditional directly after the `openBoard` calls that should fix it since the configuration settings for the board would be correct.

**Comment by ctrlcctrlv** [comment]
Sorry, can't do much with a gist, need a PR or at the very least a diff

For me this issue is low priority so without that I'm not going to exert the effort to make my own diff and test it

Without payment or something that is :wink:

**Comment by OrcasIsland** [comment]
@Circlepuller Cool, thanks! So that updated file should work with the latest public version of vichan? Also, what do you mean by your fork of vichan?

**Comment by OrcasIsland** [comment]
@ctrlcctrlv If you are for hire, how much to make sure vichan works with php 7.3? That would be awesome as it would be faster and a bit more secure.

**Comment by Circlepuller** [comment]
The Github Gist I created is for the latest public version of vichan. I maintain a fork of vichan/Tinyboard that varies from the source of vichan.

Also, vichan should work on 7.3, but as with any other software, I'd test your setup in a development environment before deploying it to production. 

If you for any reason encounter issues with my fix to post.php, please bring it to my attention and I'll do my best to help you out.

**Comment by ctrlcctrlv** [comment]
@Circlepuller OK fine, I committed it for you (`EDITOR=vim git commit --author="Circlepuller <dsaunders@dansaunders.me>"`) since *I* downloaded your `post.php`, ran `diff` against the `post.php` in HEAD, and found the diff to contain no conflicting changes, but you really should have made a PR instead of a Gist so I don't have to haphazardly check your changes into Git.
