### ISSUE TITLE
Can't post images!

### ISSUE THREAD

**Issue by 73james93** [vichan-devel/vichan#294]
Everytime I  try to post my image to a board it says **"Fatal Error: Cannot redeclare imagecreatefrombmp() in vichan/inc/image.php on line 584"** 

How can I fix it??

**Comment by 73james93** [comment]
I also get:   count(): Parameter must be an array or an object that implements Countable in the mod dashboard

**Comment by ctrlcctrlv** [comment]
OP is duplicate of #282. Post #2 must be in separate thread.
