### ISSUE TITLE
Can't post to my borad - Your post looks automated

### ISSUE THREAD

**Issue by sambuev** [vichan-devel/vichan#297]
Hello, I'm admin of my own board, but I cannot post anything to my borad. Always show Your post look automated. Please help!

**Comment by M0NSTR1S** [comment]
has something to do with your settings. been a while I used this script but try to $config['bsd_md5'] = true; and $config['gnu_md5'] = false;
not sure what setting it is though.

**Comment by ctrlcctrlv** [comment]
PEBKAC
