### ISSUE TITLE
Issues with PHP 7.2 on Ubuntu 18.04

### ISSUE THREAD

**Issue by tunayuyar** [vichan-devel/vichan#298]
I know the post about using and maintaining vichan for php7.2 but here is the list of issues with php 7.2 on ubuntu 18.04:

1- Error at moderation panel "count(): Parameter must be an array or an object that implements Countable"
2-Custom capcodes
3-Report queue at mod panel, reporting system works, I can see reports in mysql db but cannot reach them through mod panel, "Error and error has occured, Table 'dbname.posts_0' doesn't exist"
4-Bans: I was able to ban posts and ips with 1d 3d 5d 30d etc but now it doesnt work, I need to do 1 day 2 days 5 days 30 days inorder to avoid errors. Without days it simply bans ip in seconds.
5-I added one space before Click reply to view in expand.js to make it work but I dont know if this is related to php 7.2

Also vichan seems to work very very very very very fast compared to php 7.0 on ubuntu 16.04. Mass deleting posts in one board or across website is very very very very fast compared to php 7.0

I know it is not feasible to maintain vichan anymore but could you at least take a look at reports and customs capcodes?

**Comment by ctrlcctrlv** [comment]
@tunayuyar Make sure you have the latest version because a lot of these issues are supposed to be fixed. After ensuring you have the HEAD of the master branch, make one new issue for each bug.

**Comment by tunayuyar** [comment]
@ctrlcctrlv I pulled it from git using 'git clone git://github.com/vichan-devel/vichan.git' , do I need to do something else?

**Comment by ctrlcctrlv** [comment]
@tunayuyar Vichan does not auto-update. If you cloned before May 10 (https://github.com/vichan-devel/vichan/commit/0aa4e3badc346aba27edbaa71da5966642ab060a), you must `git pull` in the latest changes. If you're not sure when you cloned the repo, do it anyway.

**Comment by tunayuyar** [comment]
@ctrlcctrlv this is clean installation from couple of days ago.

**Comment by ctrlcctrlv** [comment]
So then _make one new issue for each bug_, as stated.
