### ISSUE TITLE
Cannot reach reports on mod panel // Issues with PHP 7.2 on Ubuntu 18.04

### ISSUE THREAD

**Issue by tunayuyar** [vichan-devel/vichan#300]
Cannot reach/manage reports from mod panel. Error:"Error and error has occured, Table 'dbname.posts_0' doesn't exist" 

I can see reports from mysql db.

**Comment by tunayuyar** [comment]
@ctrlcctrlv i think problem is related with reports.php 

https://stackoverflow.com/questions/18603250/php-shorthand-for-isset

**Comment by ctrlcctrlv** [comment]
Congrats, another bug confirmed.

This one tells me a table which shouldn't exist doesn't exist:

```
Table 'vichan.posts_0' doesn't exist
```

**Comment by ctrlcctrlv** [comment]
OK this one is really weird. Not nearly as simple as #301. I'm not sure I'll be able to fix it easily tonight.

**Comment by ctrlcctrlv** [comment]
Nevermind, got it. Yet another type error. You'll have to delete all reports submitted before applying this patch for it to work. Just issue `DELETE FROM reports` at the MySQL command line.
```diff --git a/post.php b/post.php
index a446e32b..3851dadb 100644
--- a/post.php
+++ b/post.php
@@ -332,7 +332,7 @@ if (isset($_POST['delete'])) {
                $query = prepare("INSERT INTO ``reports`` VALUES (NULL, :time, :ip, :board, :post, :reason)");
                $query->bindValue(':time', time(), PDO::PARAM_INT);
                $query->bindValue(':ip', $_SERVER['REMOTE_ADDR'], PDO::PARAM_STR);
-               $query->bindValue(':board', $board['uri'], PDO::PARAM_INT);
+               $query->bindValue(':board', $board['uri'], PDO::PARAM_STR);
                $query->bindValue(':post', $id, PDO::PARAM_INT);
                $query->bindValue(':reason', $reason, PDO::PARAM_STR);
                $query->execute() or error(db_error($query));

```

**Comment by tunayuyar** [comment]
Thanks @ctrlcctrlv
