### ISSUE TITLE
Option to reset thread `bump` after last post deleted

### ISSUE THREAD

**Issue by tunayuyar** [vichan-devel/vichan#303]
I think this will be beneficial in the purpose of dealing with spam that is encountered long time in our board.

tinyboard/vichan is good for dealing with spam with deleting all post by ip in same board or accross website. 

But there is one kind of spam that is a problem that I cannot deal within tinyboard mod panel. One spammer that posts one post starting from the last thread in board and keeps bumping old threads to first page. When all the spammers posts deleted old threads still stay at first page(by design I suppose). 

Is it possible to add some option to deal with this? I was dealing this with incremental backups but it is time consuming and not the exact solution to this problem.

**Comment by ctrlcctrlv** [comment]
@tunayuyar I edited your title to make more sense and to better fit with the actual implementation details.

**Comment by tunayuyar** [comment]
@ctrlcctrlv yes, thank you. hope this is implemantable?

**Comment by ctrlcctrlv** [comment]
@tunayuyar It is, apparently it's one of 8chan's board options, but as far as vichan goes:

>Vichan is still accepting patches, but **there is at the moment no active development besides fixing security problems and other serious bugs as they emerge.** Given the lack of active development, we strongly urge you to consider other imageboard packages. It is the opinion of the vichan development team that no new vichan imageboards should be deployed, and other imageboard packages, such as lynxchan, used instead.

You're free to open a PR, or pay someone to open a PR, what you'd want to do is add an `event_handler` on the `delete` event that would query the database to reset the thread's `bump`.

So I tagged this with `enhancement`, which I'm not writing any right now.

**Comment by tunayuyar** [comment]
@ctrlcctrlv can 8chan be used like vichan(disabling user board creation and other options)? Im willing to give it a try because I dont want to deal with this spam anymore.

**Comment by ctrlcctrlv** [comment]
@tunayuyar The current administration of 8chan no longer posts source code I'm afraid. There are some old branches floating around but they aren't regularly updated.

**Comment by tunayuyar** [comment]
@ctrlcctrlv oh, i thought you meant OpenIB, well couldnt make it work in virtual environment either(i think it needs domain name to work properly).

Whatever thank you @ctrlcctrlv I guess Im on my own.

**Comment by OrcasIsland** [comment]
Incremental backups seem an easy way to deal with this. The behavior would cease if the malicious bumper realized that for every 200 clicks of his time you could undo it with one click. (restore backup)

**Comment by tunayuyar** [comment]
@OrcasIsland  I have incremental backups but it is not an exact solution to this problem. A spammer can keep doing this while other people using web sites and incremental backups will take website to certain time when nothing is posted. Also it is in no way one click solution(at least for me)

I thought vichan already has similiar function embedded in itself and doable easily but nobody is working on vichan anymore except @ctrlcctrlv which is providing bare minimum(thanks).

**Comment by OrcasIsland** [comment]
@tunayuyar Yes, it is dark times for php imageboards lol. Some moved on to node.js boards like lynxchan, or the golang imageboards like meguca. Oah and fyi not sure if it would help but tinyib is a board that allows moderation in sql mode.

**Comment by tunayuyar** [comment]
@OrcasIsland Im perfectly happy with tinyboard + vichan due to speed and flexibility it provides(with php7). Also each and every one of them falls short compared to vichan.

**Comment by OrcasIsland** [comment]
@tunayuyar Well, npfchan (a fork of vichan) has amazing features.... the ability to encrypt all ip's, the 4chan style "Create new thread" link to make boards look totally awesome in even mobile phones, archiving- full archiving and other things. There is no question, npfchan has the most advanced features. Sadly, npfchan breaks...totally, after php 7.1   Vichan on the other hand has updated code to run fine on php 7.2, and guess what? I am running vichan on php 7.3 and so far it is working awesome!!!! So i will stick to vichan.

**Comment by hawkoon** [comment]
This feature has been merged and the issue can be closed.

**Comment by tunayuyar** [comment]
I dont know if this is the reason but after updating vichan to fix this. I can't seem to get expand.js to work, it seems something is changed and I can't seem to find it.

**Comment by tunayuyar** [comment]
Never mind. Found it.

https://github.com/vichan-devel/vichan/blob/63b0b92690b0f8aefbdab14450b3e3d7da977a1e/templates/post_thread.html#L84

has extra "omitted." added it to 

https://github.com/vichan-devel/vichan/blob/63b0b92690b0f8aefbdab14450b3e3d7da977a1e/js/expand.js#L22

Fixed issue.
