### ISSUE TITLE
Error in mod.php?/users/new

### ISSUE THREAD

**Issue by foxishholo** [vichan-devel/vichan#304]
The following error will be emitted if you browse to the page:
`count(): Parameter must be an array or an object that implements Countable`

The page still functions correctly, and users can be added. Though this error does make the page display strangely, effecting the font-size and so on.

Output of `php -v`

```
PHP 7.2.9-1 (cli) (built: Aug 19 2018 06:56:13) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.9-1, Copyright (c) 1999-2018, by Zend Technologies
```
I believe other errors of this type have been cropping up due to changes to type conversion in PHP7. I may be incorrect, however.

**Comment by ctrlcctrlv** [comment]
You are correct that many PHP 7.2 regressions have been happening. Do you test this against the latest version of vichan?

**Comment by foxishholo** [comment]
Yes. This was tested against the latest version of vichan.
Also seems to be break the config editor. Error:
```count(): Parameter must be an array or an object that implements Countable```
And none of the fields appear as they should.

I pulled vichan the standard way, with:
```git clone https://github.com/vichan-devel/vichan .```

**Comment by ctrlcctrlv** [comment]
Fixed
