### ISSUE TITLE
Files don't get posted along with images in certain cases (mixed file/embed)

### ISSUE THREAD

**Issue by athene-noctua** [vichan-devel/vichan#306]
Pretty much what it says.
```
$config['max_images'] = 4;
$config['allowed_ext_files'][] = 'mp3';
```
Then if you upload an image and after that an mp3 file, the file will be processed (size counted, name converted, thumbnail generated), but will not be present in /src/ or anywhere else.
Posting several mp3s will work without a hitch, but if the first file is an image, others will vanish. Posting the file first and the image second works okay.

To clarify:
2+ files: ok
2+ images: ok
file first, image second: ok
image first, file second: file gets lost

**Comment by athene-noctua** [comment]
To clarify:
- 2+ files: ok
- 2+ images: ok
- file first, image second: ok
- image first, file second: file gets lost

**Comment by OrcasIsland** [comment]
try posting a pic and an embed! Only one shows up, there is no error checking and the poster is never told that the board can not handle both at once. Retarded, unprofessional and an easy bug that should have been fixed when this board was made.

**Comment by ctrlcctrlv** [comment]
@OrcasIsland This is an open source, community-maintained project. There is no active development. Complain all you want, since this bug is not a security issue it's not part of my charter as maintainer to fix it. Feel free to submit a PR.
