### ISSUE TITLE
Reply links to thread

### ISSUE THREAD

**Issue by lambright** [vichan-devel/vichan#307]
Do we have this feature of reply links next to thread?  See this photo.  Thank you.
 
![screen shot 2018-09-03 at 9 36 23 am](https://user-images.githubusercontent.com/435028/44996459-e3e3a880-af5c-11e8-8944-808461d9fa11.png)

It's the links I want to have next as a visual.
![screen shot 2018-09-03 at 9 37 14 am](https://user-images.githubusercontent.com/435028/44996490-0d9ccf80-af5d-11e8-81a6-0a16862792fd.png)

**Comment by ctrlcctrlv** [comment]
`show-backlinks.js`, probably.
