### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable in /mod.php?/config

### ISSUE THREAD

**Issue by H1K1CH4N** [vichan-devel/vichan#309]
Same error as previous ones in php 7.2. 
For now i switched 	$config['mod']['config_editor_php'] = true;  
that removes the error.
`{% for var in conf if var.type != 'array' %}`
it is an issue on line 27 in templates/mod/config-editor.html

**Comment by H1K1CH4N** [comment]
I kind of fixed this but you need to disable verbose errors.  so the errors still shows up if you enable it. I think you don't need to enable it when debug is set to false though?
`
// For development purposes. Displays (and "dies" on) all errors and warnings. Turn on with the above.
	$config['verbose_errors'] = false;
`

**Comment by H1K1CH4N** [comment]
I renamed count to length as said here: https://github.com/twigphp/Twig/issues/2382
I assume it does the same as count ?
line 27 or 25 in templates/mod/config-editor.html

`	{% for var in conf if var.type != 'array' %}
			{% if var.name|length == 1 %}
				{% set name = 'cf_' ~ var.name %}
			{% else %}
				{% set name = 'cf_' ~ var.name|join('/') %}
			{% endif %}
			
			<tr>
				<th class="minimal">
					{% if var.name|length == 1 %}
						{{ var.name }}
					{% else %}
						{{ var.name|join(' &rarr; ') }}
					{% endif %}
				</th>
`

**Comment by ctrlcctrlv** [comment]
should be fixed in https://github.com/vichan-devel/vichan/commit/7514f31b366bd76597c5825b1c3eb753744ebcbd
