### ISSUE TITLE
What Permissions does vichan need

### ISSUE THREAD

**Issue by milan60** [vichan-devel/vichan#312]
What of these Database-Permissions/Rights do I need to give to the Database-User I use for my vichan instance and what could be left out (for security reasons)?

Select, Insert, Update, Delete, Create, Drop, Grant, References, Index, Alter, Lock_tables, Create_view, Show_view, Create_tmp_table, Event, Trigger, Create_routine, Alter_routine, Execute

**Comment by ctrlcctrlv** [comment]
I have no idea. Figure it out yourself via trial and error if it's important to you. Probably at least create routine, grant and execute aren't needed at all.
