### ISSUE TITLE
install

### ISSUE THREAD

**Issue by krvam** [vichan-devel/vichan#313]
hi, when i install and put the credencials of my database says this: Database error: SQLSTATE[HY000] [1045] Access denied for user 'hidden'@'localhost' (using password: YES)

**Comment by sardach** [comment]
You are getting Access denied Exception Error because your mysql credentials are invalid.

First check if the user really exists. ¿Can you log to phpmyadmin?

Oh! and check if really your user mysql host is localhost, some host can assign you a special port or different direction.
