### ISSUE TITLE
Moving boards

### ISSUE THREAD

**Issue by outrunning** [vichan-devel/vichan#314]
Sorry if the question sounds stupid but i couldn't find a answer anywhere else.

In case my hosting ends and i want to move to another host and keep the board, how do i move all my board with all the data intact to another host?

**Comment by sardach** [comment]
No much science. Export all your sql (using phpmyadmin is the easy way), and import in the new server. 

Transfer your files from old-server to new-server: If you have SSH, rsync is a good option. If not, throught FTP download the files and re-upload to new server.

The borad just works with nothing more to do. Just check the dependencies of vichan to avoid problems. Use the install.php checklist or use the error messages as your guide (this is my favorite way)

**Comment by outrunning** [comment]
Thank you for your answer.
