### ISSUE TITLE
Table 'boardname.posts_b' doesn't exist

### ISSUE THREAD

**Issue by Swennet** [vichan-devel/vichan#316]
I have deleted the /b/ board on my vichan install, but now every time I post a new thread I get this error. (Even though the thread still gets posted) Also, several other actions give the same or a similar error.

Is it impossible to have a vichan install without a /b/ board?

**Comment by ctrlcctrlv** [comment]
How exactly did you delete the board, what other actions cause the error, and what line number in post.php is raising the error?

**Comment by ctrlcctrlv** [comment]
No reply in over seven days, closing.

**Comment by Swennet** [comment]
Sorry for the long wait. I deleted the board through mod.php -> edit -> delete board.

When I post a new thread it doesn't show any PHP errors, it just shows me a page with the title "Error" and with the following content:

> Error
> An error has occured.
> Table 'mychan.posts_b' doesn't exist
> 
> Go back

I will reinstall the board and go through the same process to see if it fixes anything.

**Comment by Swennet** [comment]
Alright so I reinstalled the board, create a new board called /q/, then went ahead and deleted the /b/ board using the method described above.

Upon the deleting /b/, I get the following message:

> Error
> An error has occured.
> Truncated incorrect DOUBLE value: 'q'
> Go back

Now when I posted in /q/ I don't get any errors. So it seems that the issue was resolved?

I will update this if I run into the issue later.
