### ISSUE TITLE
ImageMagick / GraphicsMagick on Windows

### ISSUE THREAD

**Issue by Gladuin** [vichan-devel/vichan#317]
Hi,

I am installing vichan in XAMPP to try it out but I can't seem to get ImageMagick or GraphicsMagick to work...

Is this impossible or am I doing something wrong?

Thanks!

**Comment by goosehub** [comment]
Not enough information.

**Comment by Gladuin** [comment]
What information do you need?

**Comment by ctrlcctrlv** [comment]
Vichan is not supported on any version of Windows. 

Thank you for drawing the fact that this is not in the README to my attention.
