### ISSUE TITLE
Textboard-style links to a certain posts in a thread

### ISSUE THREAD

**Issue by xenu** [vichan-devel/vichan#32]
I would love to see textboard-style links in Tinyboard. It can (and should) be implemented in client-side javascript.

Some example URLs:
http://pl.vichan.net/b/res/123456.html#P2-4,10,11 - links to 2nd, 3rd, 4th, 10th and 11th post in the thread 123456, all other posts are hidden
or
http://pl.vichan.net/b/res/123456.html#P6 - links to 6th post in the thread 123456, all other posts are hidden

**Comment by czaks** [comment]
WONTFIX
