### ISSUE TITLE
Can't upload webm/mp4

### ISSUE THREAD

**Issue by SuriAttacker** [vichan-devel/vichan#324]
Hey there, unfortunately I can't upload any mp4/webm due to some error message :
filesize(): stat failed for b/thumb/1550591436688.jpg

![image](https://user-images.githubusercontent.com/7907213/53028385-0adc5b00-3467-11e9-86bc-721faf39ccba.png)

I'm running PHP 7.2 + Apache2, if more information is needed let me know.
Any solution to fix this issue?
Thank you in advance.

**Comment by OrcasIsland** [comment]
for sure, that is a prob with either a dependency, or a simple editing of a .ini or config file. Make sure your thumbs directories are all writable, and see if it works with a smaller filesize. If so, its just the max post size or max filesize in php.ini. I am by no means an expert, but honestly, its your settings, that is not a vichan bug. Like in the install process, you know how you can switch it from gd to imagemagic to gifsicle if everything is installed properly? Like when you run install php did you get any warnings? that tells you what image handling dependencies are installed.  try editing the instance-config.php the line that says $config['thumb_method'] = 'gm+gifsicle';   is the key here. try changing gm+gifsicle to another supported dependancy. Try removing the line completely. If you are just on a new install, delete all files, delete your db, and re-install. Make sure you have no warnings in install.php that have to do with image processing. Try going down a single php verison, sometimes, depending on what you installed or how your system is set up, that can make vichan work much better. Sorry, its a lot of shit to try, but honestly, it does not sound like a vichan bug.

**Comment by SuriAttacker** [comment]
> 
> 
> @SuriAttacker for sure, that is a prob with either a dependency, or a simple editing of a .ini or config file. Make sure your thumbs directories are all writable, and see if it works with a smaller filesize. If so, its just the max post size or max filesize in php.ini. I am by no means an expert, but honestly, its your settings, that is not a vichan bug. Like in the install process, you know how you can switch it from gd to imagemagic to gifsicle if everything is installed properly? Like when you run install php did you get any warnings? that tells you what image handling dependencies are installed. try editing the instance-config.php the line that says $config['thumb_method'] = 'gm+gifsicle'; is the key here. try changing gm+gifsicle to another supported dependancy. Try removing the line completely. If you are just on a new install, delete all files, delete your db, and re-install. Make sure you have no warnings in install.php that have to do with image processing. Try going down a single php verison, sometimes, depending on what you installed or how your system is set up, that can make vichan work much better. Sorry, its a lot of shit to try, but honestly, it does not sound like a vichan bug.

Hey there @OrcasIsland , first of all thanks for your time. 
I did check PHP .ini file and increased both max post size and max filesize, and tried to upload a smaller .webm and .mp4 file, but still no luck.

Here's how my install page looks :
![image](https://user-images.githubusercontent.com/7907213/53037744-4aad3d80-347b-11e9-88b1-bfa45220c7ec.png)

I tried to remove the following line : $config['thumb_method'] = 'gm+gifsicle'; in instance-config.php and then again with no success. (I keep getting the same error "filesize(): stat failed for b/thumb/1550601170466.jpg")

So yeah, I've no clue what the problem might be...
I've also tried reinstalling it, however still

**Comment by OrcasIsland** [comment]
did you install ffmpeg and also did you reboot apache?  https://github.com/vichan-devel/vichan/tree/master/inc/lib/webm

**Comment by SuriAttacker** [comment]
I solved it!
I just copied the example "_$config['webm']['ffmpeg_path'] = '/path/to/ffmeg';_" and didn't notice that the "p" was missing. :P 
Thank you!

**Comment by OrcasIsland** [comment]
@SuriAttacker  awesome! Also, check out http://spacechan.xyz/  and upload a mp4 or webm... that shit works quite well on lynxchan.
