### ISSUE TITLE
mod logs security

### ISSUE THREAD

**Issue by OrcasIsland** [vichan-devel/vichan#325]
Can someone make a script in the /tools directory to erase the mod logs? Having the moderator logs show up for over 350 entries is not necessary. If someone malicious gets in to mod.php, they can easily see where the mods live, ect. This is a security concern. Yes, i know, all that data is on regular server logs, and that is fine. Vichan itself should not pose a security risk of leaking the mod's ip and hometown though. I am actually going to get serious about vichan, and if someone can write the script or otherwise tell me how to clear the mod logs from the db efficiently, i would pay you for your work. Thanks.

**Comment by ctrlcctrlv** [comment]
Duplicate of #321, already answered.

**Comment by OrcasIsland** [comment]
yeah but it wasnt working. i got it finally thanks
