### ISSUE TITLE
Database error: Cannot assign requested address

### ISSUE THREAD

**Issue by idzharbae** [vichan-devel/vichan#326]
I tried to host this app on my local server, my database server was running at localhost on port 13306. On the configuration page (install.php?step=2) I set the "server" field to localhost:13306 and then the app responded with an error as the title specified. When I changed the server field to just localhost the error was "SQLSTATE[HY000] [2002] No such file or directory" instead.
My guess is localhost:13306 is not a valid url the app was expecting, is it because I added a port to the url? I also tried changing localhost to 0.0.0.0 and 127.0.0.1 and got "connection refused" error.

**Comment by ctrlcctrlv** [comment]
Not a bug, user just bad at configuring MySQL.

**Comment by idzharbae** [comment]
yeah my bad I used docker to run the app and should've use the service name instead of localhost.
