### ISSUE TITLE
Vichan breaks special characters

### ISSUE THREAD

**Issue by milan60** [vichan-devel/vichan#336]
When i post this:
<img width="259" alt="20190419145312_1" src="https://user-images.githubusercontent.com/32370325/56425067-0b507100-62b3-11e9-924c-b3ddb83f636f.png">
for some odd reason, the generated posts looks like this:
<img width="177" alt="20190419145324_1" src="https://user-images.githubusercontent.com/32370325/56425092-20c59b00-62b3-11e9-89e5-88c391ee589d.png">

I searched the code as good as i could but could not find what breaks the post. Also when i check the Database, body_nomarkup is completely fine, bu body is already the broken text.

Any ideas or fixes?

**Comment by lolicatgirl** [comment]
Just don't post those symbols then, problem solved lmao

**Comment by swupd** [comment]
yeah just dont, its that simple.

**Comment by ctrlcctrlv** [comment]
Either the database, the web server or PHP is misinterpreting the data as Latin1 encoded when it's actually UTF8. This is a configuration error on your part, not a bug affecting everyone.
