### ISSUE TITLE
Delete post bug

### ISSUE THREAD

**Issue by Shekko7** [vichan-devel/vichan#338]
I have a bug that tells me when I'm going to delete a post that the password is wrong

**Comment by ctrlcctrlv** [comment]
This is not actionable. There's no traceback, information about installation, etc. I'll close it in a few days if you can't provide helpful technical information.

**Comment by Shekko7** [comment]
![imagen](https://user-images.githubusercontent.com/49597653/57191069-b99a1e80-6f21-11e9-9e0a-eff1348ee354.png)
![imagen](https://user-images.githubusercontent.com/49597653/57191077-cfa7df00-6f21-11e9-8dce-670475a89357.png)
![imagen](https://user-images.githubusercontent.com/49597653/57191081-e2baaf00-6f21-11e9-8c62-27a865c6525d.png)

What more do you need?

**Comment by Shekko7** [comment]
> 
> 
> This is not actionable. There's no traceback, information about installation, etc. I'll close it in a few days if you can't provide helpful technical information.

?

**Comment by ctrlcctrlv** [comment]
I think you are fundamentally misunderstanding how the software works. You're trying to use the _user_ deletion to do a _`mod.php`_ deletion. Just press `[D]` while logged in through `mod.php`, on the page `mod.php?/b/`, no password required.

The _user_ deletion method relies on: &#x249C; password being entered during post; &#x249D; board itself allowing deletions; &#x249E; password matching when pressing `Delete`.

**Comment by Shekko7** [comment]
I'm sorry, I don't know what I did. I don't control the github or the english xD well.

**Comment by Shekko7** [comment]
to see, but I'm still in the same inside the mod works but outside not

**Comment by ctrlcctrlv** [comment]
So what is broken: ⒜ mod deletion; or ⒝ user deletion?

**Comment by Shekko7** [comment]
What breaks is the password outside the mod.php, it just doesn't work.

**Comment by ctrlcctrlv** [comment]
It works on other vichan installations, including my local one, so it's probably a problem with cookies, or you're not entering a password, or your password is not being saved properly in the DB. Since I can't reproduce your problem, I cannot help you, sorry.

**Comment by Shekko7** [comment]
> 
> 
> It works on other vichan installations, including my local one, so it's probably a problem with cookies, or you're not entering a password, or your password is not being saved properly in the DB. Since I can't reproduce your problem, I cannot help you, sorry.

Here http://skyog.co.nf/

**Comment by Shekko7** [comment]
Contact me via Discord for passwords Gngax#1344

**Comment by ctrlcctrlv** [comment]
I only fix reproducable bugs for free. Your problem is unique to your installation, therefore I will not fix it for free. However, you may pay me for support. Email me for details, my email is on my profile.

**Comment by Shekko7** [comment]
![imagen](https://user-images.githubusercontent.com/49597653/57191371-10552780-6f25-11e9-88bf-9170c2cb793c.png)

**Comment by ctrlcctrlv** [comment]
Oh, also:

> Vichan is still accepting patches, but there is at the moment no active development besides fixing security problems and other serious bugs as they emerge. Given the lack of active development, we strongly urge you to consider other imageboard packages. It is the opinion of the vichan development team that no new vichan imageboards should be deployed, and other imageboard packages, such as lynxchan, used instead.

**Comment by ZykLopKillErR** [comment]
where I put the password to enter the mod, I say in the config and in the mod.php there is nothing. at the beginning installation is the database password. Right? help me
