### ISSUE TITLE
Same Unique IDs

### ISSUE THREAD

**Issue by OfficialUniversalCoders** [vichan-devel/vichan#340]
Unknown reason as too getting different posters with same IDs.

**Comment by OfficialUniversalCoders** [comment]
// When true, the sage won't be displayed
	$config['hide_sage'] = false;

	// Don't display user's email when it's not "sage"
	$config['hide_email'] = false;

	// Attach country flags to posts.
	$config['country_flags'] = true;

	// Attach forceflag flags to posts (if set for IP).
	$config['country_flags_use_forceflags'] = false;
	
	// Allow the user to decide whether or not he wants to display his country
	$config['allow_no_country'] = false;

	// Load all country flags from one file
	$config['country_flags_condensed'] = true;
	$config['country_flags_condensed_css'] = 'static/flags/flags.css';

	// Allow the user choose a /pol/-like user_flag that will be shown in the post. For the user flags, please be aware
	// that you will have to disable BOTH country_flags and contry_flags_condensed optimization (at least on a board
	// where they are enabled).
	$config['user_flag'] = false;
	
	// List of user_flag the user can choose. Flags must be placed in the directory set by $config['uri_flags']
	$config['user_flags'] = array();
	/* example: 
	$config['user_flags'] = array (
		'nz' => 'Nazi',
		'cm' => 'Communist',
		'eu' => 'Europe'
	);
	*/

	// Allow dice rolling: an email field of the form "dice XdY+/-Z" will result in X Y-sided dice rolled and summed,
	// with the modifier Z added, with the result displayed at the top of the post body.
	$config['allow_roll'] = false;

	// Use semantic URLs for threads, like /b/res/12345/daily-programming-thread.html
	$config['slugify'] = false;
	
	// Max size for slugs
	$config['slug_max_size'] = 80;

**Comment by ctrlcctrlv** [comment]
Probably misconfigured server not getting correct IP, not a bug
