### ISSUE TITLE
help me install

### ISSUE THREAD

**Issue by Kwweep** [vichan-devel/vichan#342]
when ever i go to install.php and fill out the stuff when i click complete installation it always says Database error: SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it. i did every did i did all the phpmyadmin stuff i reinstalled it and kept saying it can somebody help me

**Comment by Kwweep** [comment]
also i use mamp

**Comment by ctrlcctrlv** [comment]
Free support is not provided.
