### ISSUE TITLE
Error 1045 in install.php

### ISSUE THREAD

**Issue by Konsedin** [vichan-devel/vichan#343]
When I opened the install.php in browser, I have an error 1045:
`Database error: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)`

I use a hosting, therefore, I have quite a little opportunities. 
I saw that the subject about this error already was, but I specifically didn't understand the solution of this problem.

**Comment by ctrlcctrlv** [comment]
I don't provide free tech support. This is not a bug in the code but rather your faulty configuration.
