### ISSUE TITLE
In my index appears the directory.

### ISSUE THREAD

**Issue by TheiNorbit** [vichan-devel/vichan#346]
![20190822_043650](https://user-images.githubusercontent.com/54335981/63500075-2a485500-c497-11e9-885a-6f202117aee8.png)

Already finished the installation, everything worked, but does not appear the final index. What is missing to appear the index in html? I am using cPanel.

**Comment by ctrlcctrlv** [comment]
This bug is invalid. We cannot help you figure out third party software, at least for free.
