### ISSUE TITLE
`delete-stray-images.php` is totally broken as of c483e12

### ISSUE THREAD

**Issue by ctrlcctrlv** [vichan-devel/vichan#350]
Apparently we forgot about this script when we added multi image posting...in 2013.

https://github.com/vichan-devel/vichan/commit/c483e1258cb5d168812a6e509e982a172f6c36c6

No one noticed until @tunayuyar opened #345, which is an as yet unknown bug probably in `post.php`, where it calls `clean($pid)`.

I'm not going to be fixing this (for free anyway), but am opening an issue so people are aware.

**Comment by hawkoon** [comment]
Does this fix the issue? https://github.com/fallenPineapple/NPFchan/pull/236
cc @Couchy

**Comment by Couchy** [comment]
That fix prevents a lot of orphaned files, but I still get them regularly for whatever reason, mostly with multi-image uploads. I threw together a script to move the orphan files that you can try.
[orphan.zip](https://github.com/vichan-devel/vichan/files/3802439/orphan.zip)

**Comment by Couchy** [comment]
@tunayuyar Did you change the variables at the start with your root directory, database, and credentials? I can't test this because I don't use vichan anymore.

**Comment by tunayuyar** [comment]
@Couchy yes i did. if i run it from browser it shows just 1 image moved and gives link(which not moved to orphan directory)

if i run it through cli, see below

<br/><br/><br/>Board: /b/<br/>PHP Warning:  Undefined property: stdClass::$thumb in /orphan.php on line 33

<br/>Source files<a href='b/orphan/src/1560509946012.jpg'>1560509946012.jpg</a><br/>PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string / string in /orphan.php:49
Stack trace:
#0 {main}
  thrown in /orphan.php on line 49

**Comment by Couchy** [comment]
@tunayuyar Ah, in the rename calls, put quotes around the second argument. Not sure how that happened.

**Comment by tunayuyar** [comment]
@Couchy i think that worked. Also line 58 thumbnails was missing the quotes around second argument too, that fixed everything.
