### ISSUE TITLE
Invalid webm uploaded. ffmpeg.php and streams

### ISSUE THREAD

**Issue by KOSSOII** [vichan-devel/vichan#351]
If upload webm with streams in the wrong sequence, like this:

>  Stream #0:0: Audio: vorbis, 44100 Hz, stereo, fltp (default)
    Stream #0:1: Video: vp9 (Profile 0), yuv420p(tv), 640x360, SAR 1:1 DAR 16:9, 24 fps, 24 tbr, 1k tbn, 1k tbc (default)

Audio stream in 0 position 

ffmpeg.php return error based on this Conditions

> ffmpeg.php line:38 
`  if (empty($ffprobe_out['streams'][0]['width']) || (empty($ffprobe_out['streams'][0]['height'])))`

It posible to add webm support with mixed streams?

I try to avoid this  by editing ffmpeg.php like this:
in is_valid_webm add
`if (empty($ffprobe_out['streams'][0]['width']) || (empty($ffprobe_out['streams'][0]['height']))){
          if(empty($ffprobe_out['streams'][1]['width']) || (empty($ffprobe_out['streams'][1]['height'])))
                    return array('code' => 2, 'msg' => $config['error']['invalidwebm']);}`

and in get_webm_info
`if(empty($webminfo['error'])) {
	  if(empty($ffprobe_out['streams'][0]['width']) || (empty($ffprobe_out['streams'][0]['height'])))
	  {
		$webminfo['width'] = $ffprobe_out['streams'][1]['width'];
		$webminfo['height'] = $ffprobe_out['streams'][1]['height'];
	  }
	  else
	  {
		$webminfo['width'] = $ffprobe_out['streams'][0]['width'];
		$webminfo['height'] = $ffprobe_out['streams'][0]['height'];
	  }
    $webminfo['duration'] = $ffprobe_out['format']['duration'];
  }`

this make error

> Parse error: syntax error, unexpected 'default' (T_DEFAULT) in /var/www/board/inc/lib/webm/ffmpeg.php on line 72

**Comment by ctrlcctrlv** [comment]
Feel free to submit a PR.

**Comment by KOSSOII** [comment]
Fixed by adding two checks one only for video stream second for audio stream.

is_valid_webm_audio($ffprobe_a_out) and is_valid_webm_video($ffprobe_v_out)

Run two ffprobe (slower but fix any problem with stream mix) and add 
> -select_streams
with v and a parameters.

`exec("$ffprobe -v quiet -print_format json -show_format -show_streams -select_streams v $filename", $ffprobe_v_out);`
`exec("$ffprobe -v quiet -print_format json -show_format -show_streams -select_streams a $filename", $ffprobe_a_out);`

for get ony one stream in array.

All code:
[ffmpeg.php.txt](https://github.com/vichan-devel/vichan/files/3697254/ffmpeg.php.txt)

Maybe there are more correct solutions to this problem?

**Comment by ctrlcctrlv** [comment]
Yes, use "codec_type" in ffprobe output.
