### ISSUE TITLE
file-selector.js does not work on iOS/Safari

### ISSUE THREAD

**Issue by ghost** [vichan-devel/vichan#358]
It works on other platforms however. I suppose it has something to do with `<input type="file">` not being added to the element tree. You can append this line to file-selector.js as a temp fix:

```javascript
if (/iPad|iPhone|iPod/.test(navigator.platform)) localStorage.file_dragdrop = 'false';

**Comment by 27chan** [comment]
Tested in 15.5 (17613.2.7.1.8)
