### ISSUE TITLE
Index theme not showing most recent images if OP has multiple images

### ISSUE THREAD

**Issue by hawkoon** [vichan-devel/vichan#365]
If you have the Index theme installed and you post an OP containing multiple images, it will only show the first image of OP at Recent Images on the homepage. This is probably due to multiple images being a hacked-in feature of vichan.

**Comment by ctrlcctrlv** [comment]
Software working as intended. Multiple images has been remarkably stable over the years, and I wrote it, nothing was "hacked in". Feel free to submit a PR which will use an option, _off by default_, to regulate the current behavior.
