### ISSUE TITLE
Centos 8 - GraphicsMagick

### ISSUE THREAD

**Issue by joshuaalayon** [vichan-devel/vichan#370]
Trying to install vichan on Centos 8 but it can't find the 'gm' or 'gifsicle' command.

I have installed GraphicsMagick. If I run the 'gm' command in the command line, it finds it fine and it works. Command 'gifsicle' does not work in the command line. Vichan's install.php can not find either the 'gm' command or the 'gifsicle' command.

Any idea what I'm doing wrong here? Thank you all

**Comment by joshuaalayon** [comment]
Update: I installed gifsicle using the instructions here 

> https://briansnelson.com/How_to_install_gifsicle_for_CentOS 

but I used the rpm located here 

> https://centos.pkgs.org/7/epel-x86_64/gifsicle-1.91-1.el7.x86_64.rpm.html

I can now execute both 'gm' and 'gifsicle' from the command line.

I checked "install.php" to see what it needed exactly from those two commands, but it looks like all it does is check "which gm" and "which gifsicle" and then returns an error if those two don't work. I can execute both 'which' commands successfully myself. The results are: 

```
which gm
---> /usr/bin/gm
```


```
which gifsicle
--->/usr/bin/gifsicle
```

I'm guessing the issue is probably SELINUX blocking access to these two, but I really have no idea.

**Comment by joshuaalayon** [comment]
Also just wanna add, shell_exec is enabled in php.ini so that's not the issue here, as far as I can tell.

**Comment by joshuaalayon** [comment]
Nothing in my SELINUX log, and I tried temp disabling SELINUX, so I don't think that's the issue there either... this is a weird one, lol. Everything else is fine, but here are the only errors I have. I'm gonna go ahead with install anyways, but I'd love to know why they're failing if anyone has any ideas:


    Warning: (Optional) `convert` was not found or executable; command-line ImageMagick image processing cannot be enabled.
    Warning: (Optional) `identify` was not found or executable; command-line ImageMagick image processing cannot be enabled.
    Warning: (Optional) `gm` was not found or executable; command-line GraphicsMagick (faster than ImageMagick) cannot be enabled.
    Warning: (Optional) `gifsicle` was not found or executable; you may not use `convert+gifsicle` for better animated GIF thumbnailing.
    Warning: (Optional) `/sbin/md5` was not found or executable; file hashing for multiple images will be slower. Ignore if not using BSD.
    Warning: You will not be able to enable the additional caching system, designed to minimize SQL queries and significantly improve performance. APC is the recommended method of caching, but XCache, Memcached and Redis are also supported.

**Comment by ctrlcctrlv** [comment]
Probably just a `PATH` environment variable error. You checked everything except the basics. Log in as the WWW user and check the PATH. Or echo it out... Whatever shell is running PHP is doing something wrong.

**Comment by joshuaalayon** [comment]
Wonderful! You were absolutely correct, the PATH settings for Centos 8 are located in 
`/etc/php-fpm.d/www.conf` 
in the line 
`env[PATH] =`

Now the only errors are the md5 which says disregard if not BSD, and the APC warning which it appears APC is turned on by default in PHP7? So I'm guessing it's not needed.

Thank you!

**Comment by mikwee** [comment]
For future people looking at this and perhaps being confused like I was:
You need to delete the semicolon at the start for the env line to work, otherwise it's just a comment.
