### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by HoleySmokesBatman** [vichan-devel/vichan#371]
count(): Parameter must be an array or an object that implements Countable

Comes up on mod.php defunct image board?

**Comment by ctrlcctrlv** [comment]
Are you using the latest Git master, and not a release? What PHP version?

**Comment by HoleySmokesBatman** [comment]
> Are you using the latest Git master, and not a release? What PHP version?

Hi.
I downloaded directly from the git and it should be the latest as i am using a fresh copy of xammp

**Comment by ctrlcctrlv** [comment]
What mod.php page does it come up on?

**Comment by HoleySmokesBatman** [comment]
> What mod.php page does it come up on?

Read the OP

**Comment by ctrlcctrlv** [comment]
The OP makes no sense. I am the maintainer of Vichan, so I think I can read. *What `mod.php` page does it show up on?*

**Comment by HoleySmokesBatman** [comment]
"Comes up on mod.php"
To clear any confusion: 
https://i.gyazo.com/c421f5061d174a3e1e76b520e6dd49c7.png

**Comment by ctrlcctrlv** [comment]
And the PHP version is?

**Comment by HoleySmokesBatman** [comment]
Apache Version | Apache/2.4.41 (Win64) OpenSSL/1.1.1c PHP/7.2.27

**Comment by ctrlcctrlv** [comment]
When did you clone our repository?

**Comment by HoleySmokesBatman** [comment]
Yesterday but tried a fresh copy today

**Comment by ctrlcctrlv** [comment]
Sorry, I'm not sure what the problem is. I disabled such warnings recently, and also fixed that specific issue in 2018 according to the log. It's not happening on my machine.

I should warn you that we no longer officially support Windows, or XAMMP. It's just too much hassle.

**Comment by HoleySmokesBatman** [comment]
What software would you suggest other then xammp

**Comment by ctrlcctrlv** [comment]
We don't support Windows so I really don't think it matters, does it?
