### ISSUE TITLE
Installing a theme returns error

### ISSUE THREAD

**Issue by godhandgriffith** [vichan-devel/vichan#373]
![resim](https://user-images.githubusercontent.com/64000371/80844189-cfaeed80-8c0e-11ea-9d99-81af7f0e3734.png)
No other theme is installed. I can only install frameset and catalog themes. What can I do?

**Comment by hawkoon** [comment]
>Vichan **4.9.92**

Why did you install such an ancient version? No wonder it doesn't work. Just install the latest version by cloning the master branch (5.1.4).
