### ISSUE TITLE
Why the homepage is shit?

### ISSUE THREAD

**Issue by soylm** [vichan-devel/vichan#381]
https://imgur.com/Ydzo8h2
The image says it all.

**Comment by ctrlcctrlv** [comment]
No clue. What is your PHP version?

**Comment by soylm** [comment]
> No clue. What is your PHP version?

versión 7.4

**Comment by soylm** [comment]
> No clue. What is your PHP version?

I was thinking that I probably have to copy some file from the "templates" folder in order to have the home page correctly, is that right?

**Comment by ctrlcctrlv** [comment]
No. Closing for now; no one else has reported this. Something's wrong with your installation. Per the README:

> **It is the opinion of the vichan development team that no new vichan imageboards should be deployed, and other imageboard packages, such as lynxchan, used instead.**
