### ISSUE TITLE
How to change timezone? $config['timezone'] doesn't work. 

### ISSUE THREAD

**Issue by GW170817** [vichan-devel/vichan#382]
1. Having set ` $config['timezone'] = 'Asia/Shanghai'; $config['post_date'] = '%Y-%m-%d(%A) %H:%M:%S %Z';` in instance-config.php, but timestamp is always displyed in UTC.
![image](https://user-images.githubusercontent.com/16441873/91702636-96ca5980-ebab-11ea-9a85-7bc9a0346972.png)

2. Change php default timezone to UTC+8 using `date.timezone = 'Asia/Shanghai'` in php.ini, timestamp is still displyed in UTC.

3. Add `$config['additional_javascript'][] = 'js/local-time.js';` in instance-config.php. Timezone seems in UTC+8, but timestamp is displyed in timeago format, and $config['post_date'] doesn't work.
![image](https://user-images.githubusercontent.com/16441873/91702748-c24d4400-ebab-11ea-8e1a-72d10e147888.png)

Then how can I change timezone and display timestamp as ’Y-m-d(l) H:i:s‘ ? 

update:
The problem seems solved by changing `return gmstrftime($format, $date);` to `return strftime($format, $date);` in inc/lib/Twig/Extensions/Extension/Tinyboard.php
![image](https://user-images.githubusercontent.com/16441873/91747680-33631a80-ebf1-11ea-9064-7b39c72f5255.png)
But I'm not sure if there is a better and simpler solution.

**Comment by ctrlcctrlv** [comment]
You can't. Vichan assumes browser JavaScript will do this, and that all sites should be UTC. The config timezone deals with the timezone of the database, IIRC.
