### ISSUE TITLE
Post.php file takes 30 seconds to execute

### ISSUE THREAD

**Issue by KOSSOII** [vichan-devel/vichan#383]
Everything worked fine, but today all users suddenly had a "delay" in publishing. The text is sent in 30 ~ 35 seconds. Posts with files are sent ~ 30 + the usual upload time of such a file to the server.
change

> $ config ['db'] ['timeout'] = 30;

on the

> $ config ['db'] ['timeout'] = 3;

gave no results

However, uploading files to the server using a simple file upload form showed that the server's reception rate was correct. Restarting the services and completely restarting the server did not help. Rolling back mysql a few months ago had no results. And also removing all boards.

Rolling back the post.php file to the original one also did not give any results
Post without file, text "test123":
![TD](https://user-images.githubusercontent.com/43784013/92985606-e159a900-f4bc-11ea-966f-bf60e6e5440e.jpg)

Simple php fileupload form filesize 10mb:
![smp](https://user-images.githubusercontent.com/43784013/92985691-ac9a2180-f4bd-11ea-88b4-b412de30d687.jpg)

Adding a post directly from mysql looks ok
![sql jjpg](https://user-images.githubusercontent.com/43784013/92986130-57f8a580-f4c1-11ea-914d-2f4b6a98cf2b.jpg)

Temp was cleared.

What could have happened to cause this effect and how to fix it?

**Comment by ctrlcctrlv** [comment]
No evidence of a bug in Vichan.
