### ISSUE TITLE
Can't post new threads

### ISSUE THREAD

**Issue by ChiefSuzuha** [vichan-devel/vichan#384]
When trying to post a thread, I (everyone) get(s) an error:

"in_array() expects parameter 2 to be array, boolean given"

But I can't find any error logs to tell me what line or whatever could point me in the right direction. I'm fairly clueless when it comes to these things.

**Comment by ChiefSuzuha** [comment]
Sorry- Forgot to add, using PHP 5.4.

**Comment by JimothyWatkins** [comment]
> Sorry- Forgot to add, using PHP 5.4.

>using an extremely outdated and insecure version of PHP
Y tho?

**Comment by ctrlcctrlv** [comment]
Vichan is basically abandonware, so it works best with old versions of PHP.

**Comment by ctrlcctrlv** [comment]
By the way, I'm not saying it's secure to run PHP 5.4 in 2020. I'm sure a lot of the issues can be mitigated with reverse proxies and clever firewalls to insulate buggy network daemons like PHP5, but I've been recommending people migrate away from Vichan for three to four years at this point.

**Comment by ChiefSuzuha** [comment]
I see... I had the option to change to PHP 7.3 and recently did so (though that did nothing for my problem as well). If I do migrate away from vichan, do you have any suggestions for something that isn't abandonware too?

**Comment by ctrlcctrlv** [comment]
Lynxchan

**Comment by ChiefSuzuha** [comment]
I will look into it, thank you. I did see there was a migration tool from vichan to Lynxchan, but I suppose a fresh reinstall is probably best.

**Comment by JimothyWatkins** [comment]
To be fair, Vichan still runs perfectly fine without any errors on PHP 7.3. You do need to install it and its dependencies and set it up correctly, of course.

**Comment by ChiefSuzuha** [comment]
> 
> 
> To be fair, Vichan still runs perfectly fine without any errors on PHP 7.3. You do need to install it and its dependencies and set it up correctly, of course.

Initially, I was able to make threads, but now I can't. Even when logged in under the mod panel as an admin. I was told that it looks like my post.php keeps converting to Windows from Unix (mentioned to me because that actually had an 'in_array', but we're all clueless as to what the problem is.

**Comment by isaacimran** [comment]
I don't know why but `$config['allowed_ext_op'] = true;` creates this error, it is false by default.
