### ISSUE TITLE
When moving post to another board the image sometimes disappears ?

### ISSUE THREAD

**Issue by panfu28** [vichan-devel/vichan#392]
I moved a thread from a board to another and then moved it back to the original board and after reloading the page, the image and thumbnail weren't there anymore, I know the moving threads feature is buggy but I wanted to open an issue in case someone wants to fix it.
PHP7.0
Mysql 5.7.23

**Comment by 27chan** [comment]
Hi,
I tried to reproduce this error and without success, is there anything else I can try to do to try to catch this error?

PHP 7.2
MySQL 5.7.32

**Comment by panfu28** [comment]
Weird, I can't replicate it either, IDK if I can do this but heres the thread where it happened https://28chan.org/board/mod.php?/pol/res/16.html just so I don't sound crazy lol

**Comment by ctrlcctrlv** [comment]
Closing. This is a known issue though. Usually it means that the process got interrupted somehow.
