### ISSUE TITLE
Captcha won't check for valid input

### ISSUE THREAD

**Issue by PVNFU-28** [vichan-devel/vichan#393]
My /inc/instance-config.php is as follows:
 
        $config['captcha'] = array();
        $config['captcha']['enabled'] = true;
        $config['new_thread_capt'] = true;
        $config['captcha']['provider_get'] = 'https://28chan.org/board/inc/captcha/entrypoint.php';
        $config['captcha']['provider_check'] = 'https://28chan.org/board/inc/captcha/entrypoint.php';
        $config['captcha']['extra'] = 'abcdefghijklmnopqrstuvwxyz';
        $config['additional_javascript'][] = 'js/captcha.js';

And my /inc/captcha/config.php :

        $pdo = new PDO("mysql:dbname=[dbname];host=[host]", "[user]", "[password]", array(PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8'));
        $expires_in = 120;
        $width = 250;
        $height = 80;
        $length = 6;

After configuring it I rebuilt the page and reloaded it many times, the database information I put in the captcha config is correct though I won't make it public for obvious reasons.
The captcha shows up but no matter the input the post gets posted, even if its invalid.
There are no errors or mention of it in the debug information.

Vichan is running on PHP 7.0 and MySQL 5.7.32 under Linux

**Comment by panfu28** [comment]
I found this issue where a similar thing happens https://github.com/vichan-devel/vichan/issues/323

**Comment by ctrlcctrlv** [comment]
Use a real CAPTCHA, vichan's is deprecated.
