### ISSUE TITLE
New maintainer 

### ISSUE THREAD

**Issue by ctrlcctrlv** [vichan-devel/vichan#394]
@h00j is now Vichan's lead maintainer. 

He is Polish like @czaks. He purchased the Vichan domain and it seems like he is planning to restore the community that used to be there. 

Hopefully he will have time for actual development, not to mention interest. I was lacking either. 

Given how many lead maintainers the project has had, I think @h00j should add a timeline to the README.

**Comment by h00j** [comment]
Definitely a good idea to include the timeline in readme. Will do.

**Comment by moon9snow** [comment]
YAY make it work on php 8 that is all we want :)

**Comment by h00j** [comment]
I've added the maintainer timeline under the History section in README ([7a42158](https://github.com/vichan-devel/vichan/commit/7a4215817783311f2f2070f6837ab2b171035b62)), cheers

**Comment by ctrlcctrlv** [comment]
Sigh. Cf. #474.
