### ISSUE TITLE
IP cloaking in mod panel

### ISSUE THREAD

**Issue by h00j** [vichan-devel/vichan#395]
Sometimes (most of the times) you don't want to expose your users' IP addresses to the moderators. Optional IP cloaking would preserve the usability of a mod panel while hiding users' real IP addresses.

Since I already have a working solution for this. I'd like to make a pull request then merge it later this week.

**Comment by h00j** [comment]
IP cloaking makes it difficult to choose a correct network mask for bans, so I'd like to provide an anonymized whois-like output about the cloaked IP's network too. This will open a possibility to add another feature - a "ban the whole network" checkbox which will guess the CIDR automatically.

**Comment by ctrlcctrlv** [comment]
You might be able to backport this from OpenIB
