### ISSUE TITLE
possibility to ban the whole network easily

### ISSUE THREAD

**Issue by h00j** [vichan-devel/vichan#396]
currently you need to provide a valid CIDR when banning IP ranges. It's a good idea to add a "ban the whole network" checkbox or something along the lines, which will query the whois database for network size and insert the CIDR automatically

**Comment by PVNFU-28** [comment]
does CIDR for banning IP ranges work? I tried 5.143.0.0/16 and it throws a huge error:
`Fatal error: Uncaught Error: Call to undefined function Lifo\IP\bcmod() in /var/www/html/board/inc/lib/IP/Lifo/IP/BC.php:58 Stack trace: #0 /var/www/html/board/inc/lib/IP/Lifo/IP/CIDR.php(463): Lifo\IP\BC::bcdecbin('93257728', 32) #1 /var/www/html/board/inc/lib/IP/Lifo/IP/CIDR.php(276): Lifo\IP\CIDR::cidr_to_range('5.143.0.0', '16') #2 /var/www/html/board/inc/lib/IP/Lifo/IP/CIDR.php(327): Lifo\IP\CIDR->getRange(false) #3 /var/www/html/board/inc/lib/IP/Lifo/IP/CIDR.php(172): Lifo\IP\CIDR->getBroadcast() #4 /var/www/html/board/inc/lib/IP/Lifo/IP/CIDR.php(54): Lifo\IP\CIDR->setCidr('5.143.0.0/16') #5 /var/www/html/board/inc/bans.php(30): Lifo\IP\CIDR->__construct('5.143.0.0/16') #6 /var/www/html/board/inc/bans.php(105): Bans::calc_cidr('5.143.0.0/16') #7 /var/www/html/board/inc/bans.php(252): Bans::parse_range('5.143.0.0/16') #8 /var/www/html/board/inc/mod/pages.php(901): Bans::new_ban('5.143.0.0/16', '', '', false) #9 /var/www/html/board/mod.php(189): mod_ban() #10 {main} thrown in /var/www/html/board/inc/lib/IP/Lifo/IP/BC.php on line 58`

**Comment by PVNFU-28** [comment]
Nevermind, for IP range ban to work you need to install the php-bcmath extension it seems.

**Comment by ctrlcctrlv** [comment]
Probably you should add that to the Composer configuration.

**Comment by ctrlcctrlv** [comment]
@h00j died.
