### ISSUE TITLE
Quick Reply box can be made wider but not narrow after

### ISSUE THREAD

**Issue by PVNFU-28** [vichan-devel/vichan#398]
tried it on two different imageboards and its the same, you can drag the bottom-right corner to make the box wider but after that you can't make it narrow again, vertical resizing does work.
Minor issue really

**Comment by isaacimran** [comment]
Can confirm. I tested on Mozilla Firefox 85.0.1 and Chromium 88.0.4324.152. On Firefox resizing works just fine but on Chromium doesn't. I found these issues while searching:
https://bugs.chromium.org/p/chromium/issues/detail?id=560747
https://bugs.chromium.org/p/chromium/issues/detail?id=94583
TL;DR this is a Chrome bug.

**Comment by ctrlcctrlv** [comment]
> TL;DR this is a Chrome bug.
