### ISSUE TITLE
isolate webroot from the rest of the project

### ISSUE THREAD

**Issue by h00j** [vichan-devel/vichan#403]
only banned.php, mod.php, post.php, install.php, player.php, log.php, report.php, search.php, smart_build.php and the static files should be available within httpd

**Comment by ctrlcctrlv** [comment]
I don't see how you could do this without breaking backwards compatibility. You may have to make something like $config[webroot] and default it to being `"."`

**Comment by h00j** [comment]
Yeah, that's probably how I'll do it

**Comment by adelia8** [comment]
I would do it like that too. Of course I have no idea what you are talking bout, however doing it that way seems the best way to go by far. In comparison to the other alternatives, it seems that doing it that way is the most logical choice. So go ahead and do it that way, I give you my blessing. (lol)

**Comment by ctrlcctrlv** [comment]
@h00j died.
