### ISSUE TITLE
error webm too long shows max length set in config.php and not instance-config.php

### ISSUE THREAD

**Issue by PVNFU-28** [vichan-devel/vichan#404]
I set the webm max length to 300 seconds on my instance-config.php file  but when a user uploaded a webm longer than 300 seconds it still said "The uploaded webm is longer than 120 seconds"
So I thought maybe I have to copy the error config to instance-config.php so it detects the new length cap but even after that and a rebuild it still said 120 seconds, so I went to the config.php file and changed the 120 seconds cap to 300 seconds and now it works but I don't think this is intended as the config.php file says "WARNING: This is a project-wide configuration file and is overwritten when upgrading to a newer version of Tinyboard. Please leave this file unchanged"

**Comment by ctrlcctrlv** [comment]
Are you using the new Composer-enabled version? I have a feeling this line:

https://github.com/vichan-devel/vichan/blob/0daf03c3605ae26d0a451dd5b21a16f071d9faae/composer.json#L16

Is causing your problem. Config file loading order shouldn't be left up to composer.

**Comment by h00j** [comment]
@panfu28, do you only have this problem with `$config['webm']['max_length']`, or is the whole `inc/instance-config.php` file not loading? The composer autoload doesn't affect how the configs are loaded - the logic is still the same in `loadConfig()`:

https://github.com/vichan-devel/vichan/blob/0daf03c3605ae26d0a451dd5b21a16f071d9faae/inc/functions.php#L147

**Comment by PVNFU-28** [comment]
I haven't tested on the composer-enabled version.

**Comment by PVNFU-28** [comment]
Okay, tested and replacing
`$config['error']['webmtoolong'] 	= _('The uploaded webm is longer than ' . $config['webm']['max_length'] . ' seconds.');`
with
`$config['error']['webmtoolong'] = _('The uploaded webm is longer than %d seconds.');`
Fixes the issue, will make PR
