### ISSUE TITLE
What does the comment on line 203 of config.php mean

### ISSUE THREAD

**Issue by PVNFU-28** [vichan-devel/vichan#414]
What does the following mean exactly? https://github.com/vichan-devel/vichan/blob/master/inc/config.php#L203

> // $config['dnsbl'][] = array('tor.dnsbl.sectoor.de', 1); //sectoor.de site is dead. the number stands for (an) ip adress(es) I guess. 

The comment about the number I mean, someone who knows what the number stands/stood for consider working on this comment or just delete it tbh, or if the assumption that it stands for an IP address (which I doubt) is right, delete the "I guess" to make it more clear.

Also if you know what the number on that line and line 206 means pls explain.

**Comment by isaacimran** [comment]
It blocks tor connections, You can read more about it in [their site](https://rbl.efnetrbl.org/)
```
An example BOPM usage is here:

blacklist {
           name = "rbl.efnetrbl.org";
           type = "A record reply";
           ban_unknown = no;
           reply { 
   		   1 = "Open Proxy";
		   2 = "spamtrap666";
		   3 = "spamtrap50";
---------------->  4 = "TOR";
		   5 = "Drones / Flooding";
   	   };
    	   kline = "KLINE 1440 *@%h :Blacklisted Proxy found.  Visit http://rbl.efnetrbl.org/?i=%i for info.";
};
```

**Comment by PVNFU-28** [comment]
oh cool, so if you change the number for one of the others you can block other types?

**Comment by isaacimran** [comment]
Yup :)
