### ISSUE TITLE
question on max pages

### ISSUE THREAD

**Issue by adelia8** [vichan-devel/vichan#415]
// Maximum number of pages. Content past the last page is automatically purged.
	$config['max_pages'] = 10;

Hi, is there a way to set it so there is no max pages limit? That way someone can not spam the board to clear out all the posts.

**Comment by PVNFU-28** [comment]
You could set it to a really high number I think, something like 9999

**Comment by adelia8** [comment]
Yeah, I figured, was wondering if setting it to zero disabled it. I guess there is no built in function to deal with it,  I know npfchan had the archiving which was cool. Too bad the old posts couldn't be saved to even a text file, so it would be impossible for people to get rid of a thread by pushing it off the bump limit. Anyways, thanks for the reply!
