### ISSUE TITLE
Here is the js code to easily include the [create new thread] link 

### ISSUE THREAD

**Issue by ghost** [vichan-devel/vichan#416]
Here is code to instantly make a nice looking [create new thread] link instead of showing the post form. Maybe you want to ad it to the mainstream JS directory? ? The original  link to this code is  https://github.com/Circlepuller/Tinyboard/blob/master/js/hide-post-form.js

**Comment by adelia8** [comment]
![hideform](https://user-images.githubusercontent.com/79071568/109290148-3b44f580-77f5-11eb-9d7e-7efd5504487a.jpg)

**Comment by ctrlcctrlv** [comment]
No.
