### ISSUE TITLE
mod

### ISSUE THREAD

**Issue by ZykLopKillErR** [vichan-devel/vichan#419]
where I put the password to enter the mod, I say in the config and mod.php has nothing. at the beginning of the installation is the database password. Yep? Help me

**Comment by ZykLopKillErR** [comment]
I just wanted to know how to log in to mod.php

**Comment by adelia8** [comment]
the url of mod.php is at your board root. For example if vichan in installed at yoursite.com/board then you go to yoursite.com/board/mod.php and the default is admin / password  once in first thing to to is edit your password.

**Comment by adelia8** [comment]
ctrlcctrlv or h00j you both have my permission to close this issue. I will let you know what other issues to close out as I deem necessary. (lol)  K thanks! :)
