### ISSUE TITLE
How to get a hompage like 4chan?

### ISSUE THREAD

**Issue by soylm** [vichan-devel/vichan#425]
The title says it, I would like to have a hompage with the description of the site, a menu with the boards and the statistics, is this possible with vichan or tinyboard?

**Comment by borkform2555** [comment]
Some parts, try with global static page and html, css. Copy some stuff from recent.html

**Comment by FunWithAlbiYT** [comment]
You can just go to mod.php, login as admin, manage themes and install the index theme.
