### ISSUE TITLE
gif

### ISSUE THREAD

**Issue by darkscared** [vichan-devel/vichan#427]
How to activate automatic Gif vichan has? If so, you need imagemagick

**Comment by 27chan** [comment]
You need imagemagick and set this config in your inc/instance-config.php
`
        $config['thumb_ext'] = '';
	$config['thumb_keep_animation_frames'] = 300;
	$config['thumb_method'] = 'convert+gifsicle';
`

You can see more information in inc/config.php

**Comment by darkscared** [comment]
It worked thanks ^^
