### ISSUE TITLE
convert error

### ISSUE THREAD

**Issue by darkscared** [vichan-devel/vichan#428]
This is the error. Did I download wrong?I saw a correct tutorial?

**:(**
![capture-screen-01-57](https://user-images.githubusercontent.com/80937395/112095847-03269d80-8b7c-11eb-85ba-ba2420eed56c.png)

**Comment by darkscared** [comment]
I alrewady downloaded ghostscript even so it doesn’t work, it’s in PATH, all extensions, gmagick and imagemagick, and it’s also giving graphicsmagick an error as well. I give up :/

**Comment by darkscared** [comment]
No one has ever had a problem with convert vichan Linux ??? 😔

**Comment by 27chan** [comment]
We need more details about, your PHP version, SQL, imagemagick and your instance-config.php settings

**Comment by darkscared** [comment]
I had forgotten to edit the excuse policy. already solved thanki ^^

**Comment by darkscared** [comment]
Bro besides that. You can help me with image expansion. I wanted it not to open and stay fixed. As in VHS

**Comment by 27chan** [comment]
Try to change thumbnailing method.

**Comment by darkscared** [comment]
Try to change thumbnailing method.
