### ISSUE TITLE
Your browser sent an invalid or no HTTP referer.

### ISSUE THREAD

**Issue by al1ce23** [vichan-devel/vichan#433]
Tried reloading browser, mysqld, php-fpm, nginx - no clue and no solution so far

**Comment by GarfieldsPipe** [comment]
Sort of a ghetto "fix" for this: uncomment/remove line 425, 426 and 427 in [post.php](https://github.com/vichan-devel/vichan/blob/master/post.php#L425) and save the file.

**Comment by nethersynth** [comment]
An updated fix to this would be commenting or removing lines 435, 435 and 437 in [post.php](https://github.com/vichan-devel/vichan/blob/master/post.php#L435) (The HTTP referer block).

**Comment by ctrlcctrlv** [comment]
“Ghetto” fixes above are insecure, this is a well known PEBKAC error. You've misconfigured something. If you attempt to use the “fixes” above, trolls can make third-party websites with forms that auto-submit to your imageboard, thus weaponizing your own users as spambots. Fix it the right way.
