### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by skrb1c** [vichan-devel/vichan#435]
I have an InfinityFree website with empty /htdocs/ and I uploaded the latest Tinyboard code downloaded only about two minutes before.
I ran the install.php and the error showed up immediately. It reads "Database error: SQLSTATE[HY000] [2002] No such file or directory". I only have GUI (cpanel) access to the site and no terminal or ssh. Pls help.
![image](https://user-images.githubusercontent.com/71565371/117990990-f33a6700-b33d-11eb-8ac5-1b0bad5a0adb.png)

**Comment by ctrlcctrlv** [comment]
You screwed up the SQL server configuration during the setup, or the SQL server isn't running.

You're pretty naïve if you think you're going to be able to run any sort of even vaguely popular imageboard on free hosting though, lol. Also the footer is wrong, that's not Vichan, it's some ancient (seemingly even developer) build of Tinyboard.

You're gonna have to git gud, and fast, to make this work.
