### ISSUE TITLE
mysql_version() returns false for MariaDB versions

### ISSUE THREAD

**Issue by discomrade** [vichan-devel/vichan#441]
In inc/database.php, the mysql_version() function expects a specific, simple version format, such as 5.6.10.
MariaDB version numbers are too cool for that shit:
- 5.5.5-MariaDB-10.2.8+maria~xenial
- 5.5.5-10.0.28-MariaDB-2+b1
- 5.7.24-0ubuntu0.18.04.1

These all return the misleading version number 'false', causing the code to variably assume three-byte utf8 instead of utf8mb4, and erasing four-byte characters from $post['body_nomarkup'].

**Comment by GarfieldsPipe** [comment]
I've installed Vichan with the (currently) stable MariaDB **10.6** version and it works fine.

**Comment by discomrade** [comment]
> I've installed Vichan with the (currently) stable MariaDB **10.6** version and it works fine.

What do you mean by "it works"? Does this mean the mysql_version function returned a number larger than 50503 ?

**Comment by GarfieldsPipe** [comment]
> > I've installed Vichan with the (currently) stable MariaDB **10.6** version and it works fine.
> 
> What do you mean by "it works"? Does this mean the mysql_version function returned a number larger than 50503 ?
> If that is the case, then it may depend on how certain package managers label the version, cause the version numbers look like the ones listed above on the Ubuntu derivatives I've used.

I misunderstood you. Yeah the latest stable version of MariaDB is partially incompatible because of the '50503' code entries. What I did was simply remove as many lines relating to 50503 possible in the relevant php files and then it works fine and installs as utf8mb4.

**Comment by ctrlcctrlv** [comment]
Try #491.

**Comment by ctrlcctrlv** [comment]
No response. Assuming fixed by merger of #491.
