### ISSUE TITLE
multiple issues

### ISSUE THREAD

**Issue by omsmada** [vichan-devel/vichan#442]
When not logged in as mod through mod.php, I continuously get the error "Your request looks automated; Post discarded." when trying to post. I've lowered every flood/spam setting to 1 second, both in the specific board's config file as well as the board configuration through mod.php, and it changes nothing - I still get the error.

Additionally, when logged in as a mod, I get the error "Cannot modify header information - headers already sent by (output started at /home/staffaso/public_html/info.php:1)" - uncertain of what that means, as I've not done anything whatsoever with that file.

**Comment by omsmada** [comment]
Actually did just notice that the db user and database field in the config have randomly become blanked - which may or may not have something to do with them... and when I attempt to fill them back in, I'm now given the error "invalid security token". I get the same error if I attempt to delete the board - was going to attempt to delete and re-create it, but that appears to not be an option.

**Comment by omsmada** [comment]
So, I sort of solved this on my own -- it's due to the board-specific config file I created -- but I'm still getting the "cannot modify header information" error referring to "info.php:1" exactly the same as above. What about this config file is causing this?
[config.txt](https://github.com/vichan-devel/vichan/files/6766536/config.txt)

**Comment by GarfieldsPipe** [comment]
Sounds like you have a lot of double entries in your config(s). Reminder that most config stuff (especially the basics) is actually in `instance-config.php`, not config.php
