### ISSUE TITLE
most things in js folder don't seem to work?

### ISSUE THREAD

**Issue by omsmada** [vichan-devel/vichan#443]
I've added the ability to hide threads and hide images perfectly easily... but anything else I try doing doesn't seem to work right. Are some of these just dated? When I added all of the lines from oekaki, it added the option, but nothing ever loaded when I clicked it. When I tried allowing multiple images, I saw the + sign added next to "choose file"... but nothing happened upon clicking it. I'd really like to add a lot of these things -- I'm adding exactly what is stated in the "usage" part in my config file.

**Comment by GarfieldsPipe** [comment]
A lot of the JS features need other .js files to function. For example, you can see in the "main" Oekaki js file which other .js files it needs: https://github.com/vichan-devel/vichan/blob/master/js/wpaint.js#L12
In general it's always a good idea to have at least  'js/jquery.min.js' and 'js/ajax.js' enabled. For multiple images you can see here what's needed: https://github.com/vichan-devel/vichan/blob/master/js/multi-image.js#L6

**Comment by discomrade** [comment]
Are any errors appearing in your browser console when you try to load it?
As GarfieldsPipe said, some scripts list dependencies like jQuery, ajax or other additional Javascript (and I suspect a couple that don't list dependencies still need them).

**Comment by omsmada** [comment]
Actually figured out that some apparently were having issues due to some of my browser extensions, and others just wouldn't update immediately for some reason, and would randomly be working, like, an hour later.
