### ISSUE TITLE
mp4 "not a webm"

### ISSUE THREAD

**Issue by ApSoFtA** [vichan-devel/vichan#444]
Anyone know why I might be getting this error while posting an mp4? I'm not able to use ffmpeg, so I don't have that enabled in my instance-config or anything. I can't even post them, even though I have "$config['allowed_ext_files'][] = 'mp4';" and webm posts and plays just fine, and I see that it looks like it should be able to posted/played inline on post.php. I've scoured config to see if there's anything else I might need to do but I can't find anything.

Also curious if anyone could point me in the direction of allowing mp3s to play inline? They seem to post ok, but obviously they open in another window.

**Comment by GarfieldsPipe** [comment]
Too bad, kid.

> MP4 support is available only if you use FFmpeg thumbnailing (see above).

https://github.com/vichan-devel/vichan/tree/master/inc/lib/webm

**Comment by ApSoFtA** [comment]
> Too bad, kid.
> 
> > MP4 support is available only if you use FFmpeg thumbnailing (see above).
> 
> https://github.com/vichan-devel/vichan/tree/master/inc/lib/webm

but you're still supposed to be able to post mp4s as files, similar to zip, txt, mp3 can, right?

anyway, mp4 is native to html5 so getting it to work shouldn't really be an issue if i can just figure out how to allow it to be posted without the nonsensical webm error.

**Comment by ctrlcctrlv** [comment]
> but you're still supposed to be able to post mp4s as files, similar to zip, txt, mp3 can, right?

I don't think this is a logical assumption. File types get handled separately in vichan.
