### ISSUE TITLE
Some PNGs fail to post

### ISSUE THREAD

**Issue by GarfieldsPipe** [vichan-devel/vichan#445]
`Failed to resize image! Details: gm convert: iCCP: cHRM chunk does not match sRGB (/tmp/phpiYTfmm).`

**Comment by ctrlcctrlv** [comment]
It should work to add `-strip` to the GraphicsMagick command line, per https://trac.wildfiregames.com/ticket/2184

This will strip out embedded color profiles in PNG images. Most of the time these aren't used for anything.

**Comment by GarfieldsPipe** [comment]
> It should work to add `-strip` to the GraphicsMagick command line, per https://trac.wildfiregames.com/ticket/2184
> 
> This will strip out embedded color profiles in PNG images. Most of the time these aren't used for anything.

I see. A somewhat crude solution I found was to uncomment/delete lines 366-370 in [image.php.](https://github.com/vichan-devel/vichan/blob/master/inc/image.php#L366)

**Comment by ctrlcctrlv** [comment]
You could also add a third `strpos` check for `cHRM chunk does not match sRGB`.
