### ISSUE TITLE
Renaming Directories.

### ISSUE THREAD

**Issue by psychosoundwave** [vichan-devel/vichan#446]
Hi there!

Is there a procedure to rename (for example) /b to /boom on an existing board?
If there isn't, can you let me know what I need to change per board?
I'm assuming a lot of db changes?

Thanks!

**Comment by ctrlcctrlv** [comment]
A lot of DB changes, most of which aren't documented anywhere. You should document it as you go and then you can contribute to this project's documentation. It's unlikely anyone's gonna do that work for you for free.

Basically, you can just make a new board and delete the old one. Inserting all the posts from the original board into the new one, and copying the media directory, should work. But, more complicated things, like moderator assignments, logs, etc., will not change. You are going to have to look at every table and change all board-related columns.

**Comment by psychosoundwave** [comment]
Thanks ctrlcctrlv!
I figured it'd be a nightmare. So it sounds like the easiest way is to create new boards, and somehow import the old data and files?
Is there a script to import that stuff?

Cheers!

**Comment by ctrlcctrlv** [comment]
There is no script.

**Comment by bashl** [comment]
The easiest way to do it is to change the table posts_newboard, board (you need to do rename the old board to the new board to appear in the dashboard) and copy src and res to the folder. html and json will be generate

Maybe I did something dumb, but the way I followed was: 
alter the name of posts_%s table, dump the database and edit by "hand" replies and thread i.e: ":%s/old_board/newboard/g" to change file and thumb path

**Comment by bashl** [comment]
Maybe I did something dumb, but the way I got it right was: 
alter the name of posts_%s table, dump the database and edit by "hand" replies and thread i.e: ":%s/old_board/newboard/g" to change file and thumb path (you need to be carefully here) and then insert the name of the new board into boards table, create a folder of the new board, copy src and thumb. But I only had 1 board, so I didn't test it how tracked cites will be and logs in general.

**Comment by ctrlcctrlv** [comment]
That's basically right yes. Cross-board cites will break, you'd need to dump all posts tables to fix those. Mod log table would also need a manual update. This is really a PITA which is why 8chan's software considered board names unchangeable, and even if a board went through created → deleted due to inactivity → recreated, it would be considered "the same" board as before.
