### ISSUE TITLE
country flags dont work

### ISSUE THREAD

**Issue by ultimaatti** [vichan-devel/vichan#447]
tried to get the country flags to work, just getting this error.

![kuva](https://user-images.githubusercontent.com/89255747/130230215-52b95a3b-9f68-4a2e-8cb2-eae133b93c26.png)

**Comment by 27chan** [comment]
There was no error in dev, could you explain better?

**Comment by ultimaatti** [comment]
I tried again a while later and it started working. No idea what happened.
