### ISSUE TITLE
RSS related inquiry 

### ISSUE THREAD

**Issue by 153** [vichan-devel/vichan#450]
Every forum can benefit from these RSS (or better, Atom) feeds:

- **Thread:** 
  - new comments within a thread
- **Board:**
  - new threads within a board
  - new comments within a board (across all threads)
- **Site:**
  - new threads within a site (across all boards)
  - new comments within a site (across all threads and boards) 

Only the last 20 items need to be shown, but this could be toggled in config. 

I know that some vichan boards I use have `//site/board/index.rss` -- it seems to be an undocumented feature. Are any of these other feeds I mention present and hiding? The benefits of these feeds should be obvious.

**Comment by ctrlcctrlv** [comment]
It's not undocumented and is part of the `rss` theme. (See `templates/themes/rss/`)

Up to admins to enable.
