### ISSUE TITLE
File hash ban

### ISSUE THREAD

**Issue by borkform2555** [vichan-devel/vichan#456]
Add file hash deletion and ban.
https://github.com/fallenPineapple/NPFchan/commit/31b3cec5f3fc19615b8a5984387dcae4d999f1a0#diff-2c73b6b4b85142aaba3df2dc0b60ad8c1b5c7e35b7316cff8080beba27fb6368R1331

**Comment by ctrlcctrlv** [comment]
The NPF fork is not very professional: https://github.com/fallenPineapple/NPFchan/commit/31b3cec5f3fc19615b8a5984387dcae4d999f1a0#r60236723

**Comment by bashl** [comment]
Since we are already using composer, there's imagehash aswell.
https://github.com/jenssegers/imagehash

**Comment by borkform2555** [comment]
> Since we are already using composer, there's imagehash aswell.
> https://github.com/jenssegers/imagehash

great now have to implement file hash banning to mod tools, to composer installer and some lines of code.

**Comment by KebabLord** [comment]
you can already ban users through matching md5 filehashes if that's what you needed.
```php
// BAN THROUGH FILEHASH
$config['filters'][] = array(
     'condition' => array(
                'custom' => function($post) {
                        if ( array_key_exists('filehash',$post) && in_array($post['filehash'],array(
'c787c84e8134daa266a554cb54752bdd',
'88410434c47dacad0a175759eb35c45e',
'8371bbad602f4bd3e87e5caac027f030'
)))
                                return true;
                        else
                                return false;}),
     'action' => 'ban','add_note' => true,
     'expires' => 60 * 60 * 24, // 24 hours
     'reason' => 'You are banned for posting a forbidden image.'
);
```
