### ISSUE TITLE
When a user goes to my site it gives them a file structure

### ISSUE THREAD

**Issue by Lexian-droid** [vichan-devel/vichan#457]
Hello, Ihad downloaded vichan, however whenever a user goes to the site's root directory (/) it will resolve with a 403 error (from my server) or if you're connected locally, it'll resolve with 200 and give the directory structure.

There doesn't seem to be an index file, and i don't know why this is.
Is it suppose to be this way? and are there any ways to fix it?

I would appreciate some assistance, thanks.

**Comment by ctrlcctrlv** [comment]
It's supposed to be that way yes. You're supposed to make your index, there's no logical index that'd work for everyone. You can choose a template and output it to index.html if you wish.
