### ISSUE TITLE
Anti-bot stores negative values of thread id.

### ISSUE THREAD

**Issue by discomrade** [vichan-devel/vichan#462]
I don't even know

https://github.com/vichan-devel/vichan/commit/a3fbff225927469e68efc7ab31977736f34c7480#diff-f3a2689b39e6a1a9532d63ed0bc25e99cafc51ae5d7486c07b1e68e5a9681a3fR1293

```
if ($config['try_smarter']) {
			$antibot = create_antibot($board['uri'], 0 - $page);
			$content['current_page'] = $page;
		}
```

My understanding of antibot is vague but I'm pretty sure it shouldn't be adding negative page numbers as thread numbers. It's been doing this since Aug 16, 2013 (try_smarter default to true) so I have no idea what will happen if it's fixed.

Additionally, on the lines after they make one with no thread number and the function seems designed to handle that. What is the benefit of a NULL thread being in antispam?

**Comment by ctrlcctrlv** [comment]
Your understanding is wrong. Read the code.
