### ISSUE TITLE
Vichan returns different error depending on which max filesize user violates

### ISSUE THREAD

**Issue by rosemash** [vichan-devel/vichan#468]
When a file violates the max file size, it only returns the user-friendly vichan message if the size is between `config['max_filesize']` and the max size configured for the web server or for PHP.

If the file surpasses the max request size for the web server or for PHP, it will serve an ugly error that doesn't communicate the board's configured max file size. If ajax is enabled, the HTML for the ugly PHP- or server-supplied error message will be displayed raw in a text box accompanied by the "server took too long to submit your post" message.

**Comment by ctrlcctrlv** [comment]
not fixable
