### ISSUE TITLE
Referrer whitelist

### ISSUE THREAD

**Issue by borkform2555** [vichan-devel/vichan#473]
There is problem with I2P sending invalid referrer, only way to fix this is commenting referrer check lines in post.php.
I was wondering what if there was an array to whitelist referrers?

**Comment by ctrlcctrlv** [comment]
Copy these lines into your `instance_config.php`:

https://github.com/vichan-devel/vichan/blob/52321abc7b2037f81dafbed5ba2f85c6eebec34c/inc/functions.php#L167-L188

Change whatever it is that is not working.

This is how referrer matching works. If you think your change is broadly useful could PR it I guess.
