### ISSUE TITLE
Once again a new maintainer is sought

### ISSUE THREAD

**Issue by ctrlcctrlv** [vichan-devel/vichan#474]
To refresh memories:

In #266, I took the necessary step of removing @czaks due to inactivity, and other accounts I did not recognize.

Although it has been five years, he still remains welcome to return. This was not a *coup d'application*, more like a bureaucratic Politburo reshuffle (_перестановках_).

In #394, I appointed @h00j, a Polish man who sought to found re-establish Marcin's Polish imageboard and took a step back (inb4 "you can't take a step anywhere", yes we know this, yet my impact is still as oversized as I am overweight, deal with it).

@h00j is now inactive.

On January the 31st, I sent this to @h00j:

> Greetings!
> 
> I notice [pl.vichan.net](https://github.com/vichan-devel/vichan/issues/pl.vichan.net) remains online and you even restored the spinning «6» cube. However, you seem to have abandoned the repository.
> 
> Please don't leave it for me to maintain, if you are going to say you're maintaining it. Overall I think we both benefit from your maintainership—you get the connection to original vichan codebase/etc, I get to work on other things.
> 
> Please come back and deal with the issues I've tagged you in, so I don't have to write something like “the current domain owner of vichan.net is not actively involved in this project's maintenance and this project is dormant. we aren't sure why he abandoned us”…and then archive the repository, okay? I really don't want to do it.
> 
> PS: Things were going well, what happened? Did I do something to make you leave the repo for so long?
> 
> ----
> Best,
> Fred Brennan

He didn't reply.

PR's continue stacking up. Issues keep being ignored. I have downgraded him to a "Member" in case he attempts a hostile takeover due to my posting of this overture, but clearly people can see I'm not looking to start drama here. I've waited six months.

If @kebablord, @bebyx, @discomrade, _et al._, want their patches merged, one needs to take his place. Please reply here or email me.

**Comment by 27chan** [comment]
Maybe I would help vichan, I wouldn't be able to dedicate myself 100%, but I will be able to follow the improvements and redo the tests so that no more broken patch comes.

PM me If I can help with anything!

**Comment by KebabLord** [comment]
I'm glad that the repo is reviving after a long period of inactivity and after lots of bugs.

**Comment by ctrlcctrlv** [comment]
@27chan I waited 10 days and no one else responded. I'd like to assign you maintainer. 

>  You've invited @27chan to @vichan-devel! They'll be receiving an email shortly. They can also visit https://github.com/vichan-devel to accept the invitation. 

Please accept the invitation. Once you do you can decide direction.

**Comment by ctrlcctrlv** [comment]
By the way @27chan, there's no problem with you merging your own fork [バズーカ🚀ちゃん (bazūka🚀chan)](https://github.com/27chan/bazukachan) up here, but I suggest being careful. Vichan is very old and people expect it to be somewhat stable. All of the update scripts you have in that repo are _probably_ not appropriate, you probably want to just add them to `update.php` and do a version update.

**Comment by ctrlcctrlv** [comment]
Is everything OK @27chan ? Why haven't you unpinned this?
