### ISSUE TITLE
mod login suddenly stopped working correctly

### ISSUE THREAD

**Issue by sewercide** [vichan-devel/vichan#480]
for some reason, logging into the mod panel started to only work about a tenth of the time, requiring you to re-login over and over again. is this a known problem? is there a fix?

**Comment by borkform2555** [comment]
Check, maybe you changed these
https://github.com/vichan-devel/vichan/blob/master/inc/config.php#L175
https://github.com/vichan-devel/vichan/blob/master/inc/config.php#L1342

**Comment by sewercide** [comment]
as the issue has resolved on its own, somehow, i wasn't able to see if changing those settings would have made a difference. currently, they are set to their default values. interestingly, this was affecting all my devices as well as someone else on the mod team. if it happens again i'll experiment and report with findings

**Comment by sewercide** [comment]
> This really looks like a problem with your server configuration, try using this [article](https://support.cloudflare.com/hc/en-us/articles/200170786-Restoring-original-visitor-IPs).

this is exactly what the problem was. furthermore, the login issues coincided with a cloudflare outage. i think this issue can be closed now.

**Comment by perdedora** [comment]
> > This really looks like a problem with your server configuration, try using this [article](https://support.cloudflare.com/hc/en-us/articles/200170786-Restoring-original-visitor-IPs).
> 
> this is exactly what the problem was. furthermore, the login issues coincided with a cloudflare outage. i think this issue can be closed now.
this also happens when you activated lock_ip as @borkform2555 said. I had this issue because sometimes i logged in with ipv4, and then suddenly changed to ipv6 so I had to log in again because of lock_ip.
