### ISSUE TITLE
Empty replies are possible with javascript disabled

### ISSUE THREAD

**Issue by GarfieldsPipe** [vichan-devel/vichan#493]
When you're in a thread and simply hit the New Reply button without filling in any text, you get the error message "The body was too short or empty.". However, **disable javascript in your browser** and do the exact same action and an empty reply gets posted successfully.

Seems like the software is checking the minimum text (or image) reply requirement only on the front end and not the back end.

**Comment by ctrlcctrlv** [comment]
outside mod.php?

**Comment by ctrlcctrlv** [comment]
**outside mod.php?**

**Comment by ctrlcctrlv** [comment]
Thank you. Illogical default. Closed in https://github.com/vichan-devel/vichan/commit/1e19e75bf5a8edafba82fb6d1e753b8d685b246d.

**Comment by ctrlcctrlv** [comment]
Right again. Yes. If someone cares enough, the templates system is used to build main.js, one could use it to catch the config item and not do the body check if force_body is false.

I don't know why anyone would ever do that but it is indeed possible.
