### ISSUE TITLE
here is the code to hide post form - also thanks for making vichan great again on php 8.1 !!!! :) 

### ISSUE THREAD

**Issue by ghost** [vichan-devel/vichan#498]
in the config.....
 $config['additional_javascript'][] = 'js/jquery.min.js';
   $config['additional_javascript'][] = 'js/hideform.js';

$(document).ready(() => {
    if (active_page !== 'index' && active_page !== 'thread')
        return;

    let form_el = $('form[name="post"]');
    let form_msg = active_page === 'index' ? 'Start a New Thread' : 'Post a Reply';

    form_el.hide();
    form_el.after(`<div id="show-post-form" style="font-size:200%;text-align:center;font-weight:bold">[<a href="#" style="text-decoration:none">${_(form_msg)}</a>]</div>`);
    $('div#show-post-form').click(() => {
        $('div#show-post-form').hide();
        form_el.show();
    });
});

here is the working js to make the "create new thread" link instead of the post form showing by default. Maybe someone could add it to the js directory? I called it hideform.js in the above example.

**Comment by aamm2** [comment]
sorry, git splits up the code wrong even when i try to use the code function--- its all there in order tho.

**Comment by aamm2** [comment]
![hideform](https://user-images.githubusercontent.com/112229963/188357961-0afdcb71-b78c-4fd4-882e-5dfd4baf2a59.png)

**Comment by aamm2** [comment]
![demp](https://user-images.githubusercontent.com/112229963/188358303-8af3072c-fb2b-44ce-aa77-f6c19b142c33.png)

**Comment by aamm2** [comment]
There are a few issues with php 8.2 beta that prevent vichan from running. It can jog and walk tho, at slower paces. Strftime is deprecated and withered away to nothingness, for one.  Php 8.2 enters the scene in 2 months. As a vichan end user, I would fully expect vichan to be compatible with php 9 by like a month or so. Thank you!

**Comment by ctrlcctrlv** [comment]
PR-qua-issues are pointless.
