### ISSUE TITLE
Every new post redirects to this page

### ISSUE THREAD

**Issue by ToriDevz** [vichan-devel/vichan#500]
![image](https://user-images.githubusercontent.com/42628431/188774772-fb06030f-7e06-48af-a60a-98f398de51e1.png)

is there a way I can disable this and just have it redirect back to the post or imageboard..?

It redirects to /post.php and i'd rather it just redirect to something else

**Comment by ctrlcctrlv** [comment]
I have no clue how you've broken things so badly. What even is the URL of that page lmao? Your webserver is probably woefully misconfigured.

**Comment by ToriDevz** [comment]
the page for that info stuff is /info.php

I'm guessing I may need to remake everything because of how bad i've broken it?

**Comment by am4ib** [comment]
> I'm guessing I may need to remake everything because of how bad i've broken it?

Yes, ctrlcctrlv is an expert, when he gives you advice it ls like the advice from a paid technical support. I would also highly suggest going to php 8.1 as that is supported!! Not sure of your situation, but on a vps use the FREE cloudpanel.io control panel- omg it goes from a bare vps to having vichan on multiple sites so easily!!! It is the best free control panel I know of, blows the other free control panels out of the water. Using something like that gives you a more professional install and saves a great deal of time and configures your server properly. It works GREAT on vichan.

**Comment by ctrlcctrlv** [comment]
A few things.

1. Vichan does not come with a file called `info.php`. So this bug is _per se_ invalid.
2. @am4ib needs to stop shilling his service on this repo.

**Comment by am4ib** [comment]
"@am4ib needs to stop shilling his service on this repo." cloudpanel.io is not "my service", it is a free control panel made across the globe from where I am. Have a nice day.

**Comment by ctrlcctrlv** [comment]
don't care dude you too, as a general rule of thumb just don't shill anything

**Comment by am4ib** [comment]
So I guess you would not be interested in hearing about a new crypto currency I am starting or my get rich quick scheme I am working on huh? Oah well,,,, yeah, vichan is pretty cool tho, lots of people use it.

**Comment by am4ib** [comment]
Oah and I was nice to you and supported you when you did ur rant vid about php deprecations yon youtube. So you should prolly try to be nice to people who support you :) Like I say, its cool, I understand, I get in bad moods like that, too. Now go ahead and yell at me some more if you want.

**Comment by ToriDevz** [comment]
how did a whole ass argument start from this issue what the fuck

**Comment by ctrlcctrlv** [comment]
@ToriDevz he deleted his account lmao over like nothing… "don't advertise paid services on a free software project's bugtracker" is such a basic rule of etiquette i didn't even bother answering
