### ISSUE TITLE
Control Panel works!! 

### ISSUE THREAD

**Issue by am4ib** [vichan-devel/vichan#501]
VICHAN game changer-- how to EASILY run multiple instances of vichan on a vps.

 FREE control panel that works great with vichan- its cloudpanel.io   Anyone wanting to have multiple websites with vichan on them and the use of a control panel, this is a gem! (i tried to install vichan on plesk, for example and it did not quite work) So that is quite exciting, it makes vichan very easy to run multiple sites on the same server!!!!! Im on ubuntu 22.04 LTS, php 8.1, and use the cloudpanel.io free control panel and vichan works GREAT!!! So happy about that! edit/// not sure, maybe mention cloudpanel.io in the readme??? Like have a list of known control panels that work with VICHAN. It makes it incredibly EASY to go from a bare vps to having multiple instances of vichan running- it greatly helps people to use vichan , having a list of control panels that work with vichan.
 >>>>>ALSO thank you so much to the devs who made vichan relevant again!!!!!!!!!!!!!!!!<<<<<<

by the way, the other free control panels are lame. aapanel and stuff like that, none are good. I had cloudpanel.io installed a bunch of times and un-installed it. It takes a while to appreciate its genius I guess lol. It is hands down the most modern, easy to use free control panel, and seriously, it works GREAT with vichan, makes it EASY. There is one simple ssh command (found on the website) to install cloudpanel.io control panel.

**Comment by 27chan** [comment]
Having a control panel is useful, but not necessary for vichan. There are several boards that are hosted in free instances or panels like CloudPanel and even cPanel, however it is not necessary for it to work, but it is a great tip for people.
