### ISSUE TITLE
Is it possible to reset Vichan admin password if you forget it?

### ISSUE THREAD

**Issue by kaguy4** [vichan-devel/vichan#515]
Hi,

I am restoring an old vichan archive from an older imageboard. I don't know what the admin password was, but I do have root/mysql access. Is there any way that I change it?

Thanks

**Comment by ctrlcctrlv** [comment]
`UPDATE` the `mods` table.

```mysql
  `password` varchar(256) CHARACTER SET ascii NOT NULL COMMENT 'SHA256'
```
