### ISSUE TITLE
Config UI appends to inc/instance-config.php leak through post.php

### ISSUE THREAD

**Issue by smolten** [vichan-devel/vichan#516]
Example leakage on post.php
![1670610479534](https://user-images.githubusercontent.com/22565842/206814610-f2e6e48d-f0ce-4330-a0e6-49da5e67672d.png)

The end of instance-config.php has some php brackets, and I was too lazy to find where it actually saves/writes to the file
secrets.php has php start brackets with no end brackets, and appends there do not leak data

For now I've changed my `vichan/inc/pages.php` line 2447 from
`$config_file = $board_config ? $board['dir'] . 'config.php' : 'inc/instance-config.php';`
to
`$config_file = $board_config ? $board['dir'] . 'config.php' : 'inc/secrets.php';`

**Comment by ctrlcctrlv** [comment]
Thanks. Your patch is right.
