### ISSUE TITLE
$config['flood_cache'] undefined by default, causes error on config page in PHP 8.x

### ISSUE THREAD

**Issue by discomrade** [vichan-devel/vichan#525]
The flood_cache config was introduced in this 2013 commit: https://github.com/vichan-devel/vichan/commit/f309e4037c and has been unchanged since.

I believe was is left commented and undefined intentionally. This is the only place it is used, where it changes code behavior if it has been set:
https://github.com/vichan-devel/vichan/blob/fa198e207f44c56a9ae48bbc432ea2303dd0deee/inc/filters.php#L191-L198
However, newer PHP versions will raise an error if this config option is undefined, because this line doesn't check if the value exists before assigning it: https://github.com/vichan-devel/vichan/blob/70222e8c2dd8e82f2b85d25bced751a4b6ab9d44/inc/mod/pages.php#L2495

I'd like a second opinion on the best way to solve this.
- Is it valid to have an unset config variable and just check before use?
- Should it have a default value of 0 [disabled] to avoid creating a second config variable?

**Comment by ctrlcctrlv** [comment]
if this  is now invalid you'll want to change its behavior yes. e.g. you can set it by default to `-1`.

**Comment by discomrade** [comment]
> You can fix using:
> 
> ```
> $c = array_key_exists($var['name'], $config) ? $config[$var['name']] : null;
> ```

I was thinking of doing a check similar to that, although it may be more useful to have the code throw an error if it's trying to read a config key which doesn't exist.  flood_cache is the only one.
I think in this case, setting it to 0 is the same as disabling it, so I'm tempted to use that as the default disabled value instead of having an unnecessary check for -1 just to set `$max_time` to 0 instead of the given value of -1.

**Comment by ctrlcctrlv** [comment]
I suggested -1 because it's a horrible code smell to have config keys which cause different behavior when set vs unset, all config keys should be required to have some value. E.g. in Rust most of the time configuration is a struct so removing keys isn't even possible.

Also I really think my role with this project is just teaching people how to code better these days lol. So I just always suggest the best thing to do not necessarily easiest.
