### ISSUE TITLE
New posts & replies don't show unless page is reloaded in browser.

### ISSUE THREAD

**Issue by psychosoundwave** [vichan-devel/vichan#532]
Has anyone seen this happen?
New posts & replies don't show unless page is reloaded in browser.

For example, post a new thread or a reply and the page is the same as it was before the post, until you do a refresh in the browser.

**Comment by assada** [comment]
same issue

**Comment by psychosoundwave** [comment]
My server isn't running any cache as far as I'm aware, and I set the following in the config for vichan:

```
	$config['cache']['enabled'] = false;
	// $config['cache']['enabled'] = 'xcache';
	// $config['cache']['enabled'] = 'apc';
	// $config['cache']['enabled'] = 'memcached';
	// $config['cache']['enabled'] = 'redis';
	// $config['cache']['enabled'] = 'fs';

	// Timeout for cached objects such as posts and HTML.
	$config['cache']['timeout'] = 60 * 60 * 48; // 48 hours
```
I figured that setting $config['cache']['enabled'] = false; would kill any cache.
I can try setting the cache timeout to zero and see if that works....

**Comment by ctrlcctrlv** [comment]
not a bug.

**Comment by psychosoundwave** [comment]
> not a bug.

Can you explain?
If this isn't a bug, why don't posts appear immediately?

**Comment by assada** [comment]
if u are use nginx as http server try to add in your `/etc/nginx/sites-available/<name or default>`.conf 
```nginx
location ~* \.(html)$ {
	expires -1;
}
```

**Comment by ctrlcctrlv** [comment]
because chans did not always support this

you need auto-reload.js

**Comment by psychosoundwave** [comment]
> if u are use nginx as http server try to add in your /etc/nginx/sites-available/<name or default>.conf
Ah, using Apache here. Thanks anyway!

> you need auto-reload.js

I would love to use that. It loads, and counts down, but never actually reloads the page.  At least that's what it looks like. Clicking "Update" doesn't do anything either.

**Comment by psychosoundwave** [comment]
A couple of workarounds:

auto-reload.js works if I force the browser to reload HTM/HTML files in .htaccess

```
# DISABLE CACHING
<IfModule mod_headers.c>
    Header set Cache-Control "no-cache, no-store, must-revalidate"
    Header set Pragma "no-cache"
    Header set Expires 0
</IfModule>

<FilesMatch "\.(css|flv|gif|htm|html|ico|jpe|jpeg|jpg|js|mp3|mp4|png|pdf|swf|txt)$">
    <IfModule mod_expires.c>
        ExpiresActive Off
    </IfModule>
    <IfModule mod_headers.c>
        FileETag None
        Header unset ETag
        Header unset Pragma
        Header unset Cache-Control
        Header unset Last-Modified
        Header set Pragma "no-cache"
        Header set Cache-Control "max-age=0, no-cache, no-store, must-revalidate"
        Header set Expires "Thu, 1 Jan 1970 00:00:00 GMT"
    </IfModule>
</FilesMatch>
```

Another sort of workaround is to set the following to "true":

```
	// Always act as if the user had typed "noko" into the email field.
	$config['always_noko'] = true;
```

...which returns the poster to the thread they posted in, showing their most recent post.

**Comment by ctrlcctrlv** [comment]
oh so your webserver is misconfigured..

**Comment by ctrlcctrlv** [comment]
le epic downboats will not convince me to reopen this

![image](https://user-images.githubusercontent.com/838783/213841687-f65045cf-9bff-4cc9-854f-85123d775080.png)

**Comment by psychosoundwave** [comment]
> oh so your webserver is misconfigured..

This is not helpful at all.
Despite being unhelpful and making me feel about as welcome as a fart in a spacesuit, I have eventually figured out my problems.

**Comment by ctrlcctrlv** [comment]
> > oh so your webserver is misconfigured..
> 
> This is not helpful at all. Despite being unhelpful and making me feel about as welcome as a fart in a spacesuit, I have eventually figured out my problems.

because you're suing 10 year old abandoned imageboard software and bugging me about it when it's been made very clear that it is, indeed, abandoned 10 year old imageboard software, and so all the users should by now be expert users, all working on migration _away_, so it's a bit annoying when a fart in a spacesuit turns up and wants help doing something simple like configuring webserver.

**Comment by psychosoundwave** [comment]
You know, that's fair enough.
Apologies.

**Comment by ctrlcctrlv** [comment]
it's fine :) welcome to free software, very few people feel as free to be straightforward as i do
