### ISSUE TITLE
Problem with Ban Appeals

### ISSUE THREAD

**Issue by tunayuyar** [vichan-devel/vichan#533]
This happens on php 8.2.

This is from nginx server error log

"PHP message: PHP Fatal error:  Uncaught TypeError: json_decode(): Argument #1 ($json) must be of type string, array given in (display.php:402)
Stack trace:
#0 /display.php(402): json_decode()
#1 inc/mod/pages.php(1145): Thread->__construct()
#2 /mod.php(196): mod_ban_appeals()
#3 {main}

Also throws below one in the ban appeals page from mod.php

Caught fatal error: Uncaught TypeError: json_decode(): Argument #1 ($json) must be of type string, array given in /inc/display.php:402Stack trace:#0 /inc/display.php(402): json_decode()#1 /inc/mod/pages.php(1145): Thread->__construct()#2 /mod.php(196): mod_ban_appeals()#3 {main} thrown in /inc/display.php on line 402

**Comment by ctrlcctrlv** [comment]
regression from #530/#528?

**Comment by tunayuyar** [comment]
@perdedora confirmed this fixes it on php 8.1

**Comment by ctrlcctrlv** [comment]
Closed in #534.

I also made it so that the last infinity master is available as a branch of this repository: https://github.com/vichan-devel/vichan/tree/infinity

There are of course no plans to reconcile the two, but it just makes finding history easier to have them in one repo.
