### ISSUE TITLE
b.php not displaying banners

### ISSUE THREAD

**Issue by bigbullyist** [vichan-devel/vichan#537]
On my site, I have a 300x100 banner in /static/banners/, but b.php is not displaying it for some reason.

https://619chan.org/static/banners/0.png
As you can see here, the file is present in the proper directory.

However, https://619chan.org/b/ does not display anything at the top.
It worked for a separate file, but when I switched it around, it started happening.

**Comment by bigbullyist** [comment]
I should also include this since I realized this looking through /static/.

The spoiler, lock, video, deleted, etc image files all had 0777 file permissions (which they shouldn't be since they're image files).

Dunno if STI or czaks overlooked this, nor do I know how long that's been in there.

**Comment by SevenSevenSeven-dot** [comment]
Replace b.php with this.
```
<?php
$dir = "static/banners/";
$files = scandir($dir, SCANDIR_SORT_NONE);
$images = array_diff($files, array('.', '..'));
$name = $images[array_rand($images)];
// open the file in a binary mode
$fp = fopen($dir . $name, 'rb');

// send the right headers
header('Cache-Control: no-cache, no-store, must-revalidate'); // HTTP 1.1
header('Pragma: no-cache'); // HTTP 1.0
header('Expires: 0'); // Proxies
$fstat = fstat($fp);
header('Content-Type: ' . mime_content_type($dir . $name));
header('Content-Length: ' . $fstat['size']);

// dump the picture and stop the script
fpassthru($fp);
exit;
?>
```

**Comment by bigbullyist** [comment]
Thanks.
This should really be updated in the repo if the code for it is broken.
