### ISSUE TITLE
Emojis?

### ISSUE THREAD

**Issue by monsickzapasowe** [vichan-devel/vichan#539]
I've been looking for a way to add emojis for a long time now, i know its possible but dont know how

i thought of using wordfilters for it, for example the wordfilter is [cool] and it changes to https://example.com/emojis/cool.png, but i dont know how to auto embed it, or i dont know if theres another way.

I've been scrolling thru polish vichan archive and i saw a thread where an emoji was used so i know its possible.

**Comment by ctrlcctrlv** [comment]
There are emoji in Unicode that work just fine.

Otherwise you're looking for a raw word filter.

**Comment by basedgentoo** [comment]
If you copy over Twemoji from Infinity, that should work.
After you copy it over, append
```	$config['additional_javascript'][] = 'js/twemoji/twemoji.js';```

to your inc/instance-config.php. Now emojis will display a friendly image.

Might add it to the repo for convenience.
