### ISSUE TITLE
Error when trying to rebuild everything or just index theme.

### ISSUE THREAD

**Issue by Dead4rm** [vichan-devel/vichan#544]
When I try to rebuild either of those is says 

Unable to open file for writing: index.html

Ideas? 

Everything in it currently is all stock and it's still saying this.

**Comment by Dead4rm** [comment]
Update on this. I guess putting the fresh index file into the server helped the theme rebuild because that's working now.  Only thing I can see now is that when I go to do a site rebuild. If I toggle all it will throw that error.  But If I do them in small groups. Or one by one it will rebuild them.

**Comment by basedgentoo** [comment]
Reopening closed issues -- will look into this soon.

**Comment by RealAngeleno** [comment]
stale issue. reopen if this is still happening
