### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by ctrlcctrlv** [vichan-devel/vichan#545]
_Originally posted by @pepeenjoyer in https://github.com/vichan-devel/vichan/issues/543#issuecomment-1482335016_:

>>> It looks like Kuz and his team will be writing the bulk of the future code. I think they should choose between MIT and AGPL for their commits. Or perhaps a license which requires linking back to soyjak.party like how STI wanted people to link back to his site. Such a license would be included, and it would probably include a footer at every page linking back to soyjak.party. If the software gets better, more people will use it, and sites will upgrade to it. And soyjak.party will get more users as a result of this. I think this is the best winning move for everyone involved.
>> 
>> @kuz-sysadmin Thoughts on this?
>
>I think linking back to a site is a dumb idea. I could demand the same for my changes, and so could other altchans.
>Just a standard AGPL3 license will ensure that all forks must make their changes public and keep drama to a minimum.

**Comment by ctrlcctrlv** [comment]
I want to give historical context for this question to @jvrtychud and the ones above quoted.

Yes, if you want my opinion, the clause is onerous. However, Michael and Marcin both invoked it, and so, in terms of license compatibility, you can in general, legally, only make a license _stricter_ not _looser_.

It's not even up to me whether the project goes for a license that is _legally_ valid, however. The new maintainers may decide on that whatever they want. I'm just saying that getting out of this licensing term may not be possible _from a legal perspective_.

One possible avenue is to use the fact that in 2014, _far after the fork_, @seisatsu pushed a commit which changed the license to GPLv3 with no extra requirements. If you figure out which commits @czaks wrote _after that_, or, in the alternative, get his consent, then you can do away with the requirement legally.

For the record I consent to the GPLv3.

**Comment by pepeenjoyer** [comment]
I'm no expert on licensing, but wouldn't it be possible to leave the initial copyright clause in and release any future modifications under AGPL3?
If it's not possible to change the license, then I guess that's fine. I'd prefer AGPL, but it's not a hard requirement. 
In any case, if a clause is added to link soyjak.party, then I will not be contributing, and this project will most likely die, because altchans won't want to have an advertisement for another altchan at the bottom of every page.

**Comment by basedgentoo** [comment]
I don't think the license will be changing. Until we need to revisit this issue, I'm going to close it.
