### ISSUE TITLE
Fatal Error / Display.php Line 352

### ISSUE THREAD

**Issue by tunayuyar** [vichan-devel/vichan#549]
This occurs when trying to check ban appeals

Caught fatal error: Uncaught TypeError: json_decode(): Argument #1 ($json) must be of type string, array given in display.php:352
Stack trace:#0 display.php(352): json_decode()#1 /inc/mod/pages.php(1143): Post->__construct()#2 /mod.php(196): mod_ban_appeals()#3 {main} thrown in display.php on line 352

**Comment by basedgentoo** [comment]
Can you please post output of `php -v`?
Are you running vichan from it's current `master` branch? Please make sure you're not running an older version/fork.
I've tested php 8.2.2 on vanilla vichan and I cannot replicate this issue. On my end, ban appeals are working fine.

Once I get this info, we can go from there.

**Comment by tunayuyar** [comment]
PHP 8.1.2 with Nginx and on ubuntu  22.04

This was working actually but i think someone put Turkish characters in appeal so that might be the reason it is broken now. 

Yes I'm using master branch

**Comment by basedgentoo** [comment]
So I've tested ban appeal functionality with turkish chars, and it seems to work fine.
Could you inspect your ban appeals table and tell me what you find there?

**Comment by tunayuyar** [comment]
@perdedora yes seems similiar and patch is applied. And it can be seen it is different lines. This issue giving error from another line. 

I have a cron job for backups so, below is what's inside of ban appeal   in the sql file

INSERT INTO `ban_appeals` VALUES (1232,16663,1677793792,'Nigger',1),(1233,16668,1679850336,'dostum... not cool.\r\nAyrıca \r\nArtık kereste ve tahta üvey kardeş oldular \r\nDuymuşsundur vichan artık kolyma\'nın altında ',0);

**Comment by ctrlcctrlv** [comment]
I suggest @basedgentoo not allow people to write the gamer word on here, if only because it breaks GitHub's TOS.

**Comment by basedgentoo** [comment]
I had to remove an offensive word. The sql statement was this, for debugging:
`INSERT INTO ban_appeals VALUES (1232,16663,1677793792,'REDACTED',1),(1233,16668,1679850336,'dostum... not cool.\r\nAyrıca \r\nArtık kereste ve tahta üvey kardeş oldular \r\nDuymuşsundur vichan artık kolyma'nın altında ',0);`

**Comment by tunayuyar** [comment]
$this->files = @json_decode($this->files);

**Comment by tunayuyar** [comment]
Strange i was sure i did the patch earlier and fixed the problem but now this is different than what is on the github

**Comment by tunayuyar** [comment]
Sorry for wasting your time, i remember applying the patch but maybe something messed up with my backups that caused this.

**Comment by basedgentoo** [comment]
PEBKAC
