### ISSUE TITLE
Changing some defaults - discussion

### ISSUE THREAD

**Issue by basedgentoo** [vichan-devel/vichan#551]
Most of the JS when you install for the first time is disabled, and requires editing `inc/instance-config.php` with all of it.
Pretty much every live site makes use of most of the scripts, why not enable them by default and spare users the trouble of configuring it?

Could also do these things:
- Use `gm+gifsicle` as the default thumbnailing method (enable animated gif thumbnails by default) [Note: This makes graphicsmagick and gifsicle hard dependencies]
- Enable WEBM/MP4 support with sound out of the box
- Expand details on how to setup Redis and make caching with Redis the default setting
- Set default max file upload from installation to 5mb
- Enable image spoiler by default
- Allowing users to appeal their ban through vichan is disabled by default. Is this a good practice?
- Use exiftool to strip metadata from images by default. Not sure why this is disabled by default. Requires `exiftool` to be installed on the host.

**Comment by ctrlcctrlv** [comment]
i agree with two folks above me even if i wouldn't have been quite so harsh about it

setting up vichan is hard enough as it is

**Comment by basedgentoo** [comment]
Fair enough. It'll stay the same.
Remember: It was a discussion.
