### ISSUE TITLE
Multiple Reports of Different Posts Causing Report Queue to Show Only Same Post Reported Twice(or more)

### ISSUE THREAD

**Issue by tunayuyar** [vichan-devel/vichan#567]
As in the subject, lets say someone reported post # 500 and another person reported # 550 

Report queue shows only # 500 reported 2 times, when dismissed, shows the # 550 report.

**Comment by basedgentoo** [comment]
Can I get the output of `git show` to see what you're running on?
Helps for testing.

**Comment by tunayuyar** [comment]
fatal: detected dubious ownership in repository at '/tahta'
To add an exception for this directory, call:

        git config --global --add safe.directory /tahta

**Comment by tunayuyar** [comment]
Dismiss button not the mass dismiss one.

**Comment by tunayuyar** [comment]
To provide further info on this see below screenshots, although this does not happen all the time, it happens. 

I saved last report in the report queue and there was 3 report showing. 1 was different remaining 2 was in the screenshot, when I dismissed 1 one of the same, the earlier different report appeared and second one of the same one disappared.

![image](https://github.com/vichan-devel/vichan/assets/4925001/de180432-fd83-4e3e-aed9-766c274c3097)

![image](https://github.com/vichan-devel/vichan/assets/4925001/a97a6c92-3513-4091-bf09-fdbf256ac1b7)

**Comment by tunayuyar** [comment]
No, not at all.

**Comment by RealAngeleno** [comment]
Honestly probably the number 1 bug that needs to be fixed currently. Have been looking into it (on php 8.2) and have not found why it is happening.

**Comment by RealAngeleno** [comment]
Added a print_r($reports); to debug and reports get fetched from the database just fine, but don't display properly still. That completely removes the possibility of it being from mod_reports().

**Comment by RealAngeleno** [comment]
It is an issue with twig. Reverted to 1.44.2 and it displays just fine. Not sure what is causing it.

**Comment by RealAngeleno** [comment]
I stand corrected. Used a mod_reports function from 2019 and it works just fine.

**Comment by RealAngeleno** [comment]
Changing
`	foreach ($reports as &$report) {`
to
`	foreach ($reports as $report) {`
fixes it.

**Comment by RealAngeleno** [comment]
It's been fixed via #610.
