### ISSUE TITLE
webm is an invalid image?

### ISSUE THREAD

**Issue by SevensRequiem** [vichan-devel/vichan#586]
Error information
Array
(
    [backtrace] => Array
        (
            [0] => Array
                (
                    [file] => /home/shutin/htdocs/vichan/post.php
                    [line] => 880
                    [function] => error
                    [args] => Array
                        (
                            [0] => Invalid image.
                        )

                )

        )

)

**Comment by RealAngeleno** [comment]
That problem arises if you do not have the proper dependencies, specifically FFMPEG. Some documentation can be found at inc/lib/webm/README.md.


Installation
------------

Add these lines to inc/secrets.php:

    $config['allowed_ext_files'][] = 'webm';
    $config['additional_javascript'][] = 'js/webm-settings.js';
    $config['additional_javascript'][] = 'js/expand-video.js';

If you have an [FFmpeg](https://www.ffmpeg.org/) binary on your server and you wish to generate real thumbnails (the webm thumbnails created with the original implementation reportedly cause users' browsers to crash), add the following to inc/secrets.php as well:

    $config['webm']['use_ffmpeg'] = true;



You probably won't need to set these, but if you do...
    // If your ffmpeg binary isn't in your path you need to set these options
    // as well.

    $config['webm']['ffmpeg_path'] = '/path/to/ffmeg';
    $config['webm']['ffprobe_path'] = '/path/to/ffprobe';
