### ISSUE TITLE
Original filename shown in player.php

### ISSUE THREAD

**Issue by crazy4cars69** [vichan-devel/vichan#594]
If show_filename is disabled and if user clicks webm/mp4 video, it will use player.php and the original filename will be shown in the title and in the url.
https://github.com/vichan-devel/vichan/blob/master/player.php#L4
https://github.com/vichan-devel/vichan/blob/master/player.php#L12

**Comment by RealAngeleno** [comment]
Alright. Made #596, which sets t to the post filename instead when the setting is changed.

**Comment by RealAngeleno** [comment]
Also @perdedora, do you have an IRC or telegram?
