### ISSUE TITLE
Maintainer has disappeared (again) (Vichan is Pakistan confirmed)

### ISSUE THREAD

**Issue by ctrlcctrlv** [vichan-devel/vichan#602]
I feel like I've seen this show before:

- #266 
- #394 
- #474 
- #543 

This time it's @basedgentoo being an absolute disappointment to the community, myself, and ultimately themselves.

- @perdedora has been sent an invite. Once again, if they manage to not disappear for one year, they'll be promoted to Owner.
- @basedgentoo should not bother appealing.
- @RealAngeleno's fate is up to @perdedora.

Thanks for reading my blog.

**Comment by veruc4** [comment]
The top national Conspiracy Theorists have formulated that ctrlcctrlv is really basedgentoo, and is working for the Russian Mafia. It makes perfect sense. This solves the mystery entirely.

**Comment by ctrlcctrlv** [comment]
lol. but then who is @perdedora?

**Comment by tr0lland** [comment]
Vichan Died

**Comment by l29utp0** [comment]
just let it die already, it had a good life
you're only prolonging the suffering

**Comment by ChessLogical** [comment]
Yeah, many have abandoned php for go or rust or node, but i must say, the nvme drive on my (DO) server makes php code load as fast as node or go code loads other sites, i literally can not tell the difference. Of course under heavy loads it would likely slow down, but honestly, i have a new respect for php when it is on nvme drives with lots of ram, it is incredibly fast. Just a few years ago one could definitely tell that php apps were super slow, on my test site php apps run just as fast as anything else!

**Comment by ChessLogical** [comment]
also of note, any php app that can run on the latest ver of php is not dead at all. I got a few vichan instances up with php 8.2 nginx and ubuntu 22 and did not encounter any probs yet. Granted, like Fred has been saying for years, vichan is for nerds lol and is not exactly the go to thing, but it is still nice for what it is.

**Comment by bigbullyist** [comment]
I've pretty much switched to TinyIB by now. Idk why vichan's dev history is like this. I think a more accurate comparison is Peru, since neither can maintain a proper leader.

**Comment by zizuke** [comment]
Why don't you take care of it brennan? You're pretty much the guy needed. Can't write php, rather go for learning javascript if I wanted to learn a web programming lang...

**Comment by ctrlcctrlv** [comment]
@zizuke 

https://github.com/vichan-devel/vichan/assets/838783/c1cbc592-39a0-427d-955e-2bad73ec1a78
