### ISSUE TITLE
IRC channel

### ISSUE THREAD

**Issue by crazy4cars69** [vichan-devel/vichan#604]
Maintainers should make IRC channel on rizon

**Comment by RealAngeleno** [comment]
We did have one for a while. During kuz, we had one at #vichan on KNIRC. After Kolyma dissolved, basedgentoo put one at #vichan-devel, although he's inactive and the channel is basically gone. There was never much activity from non-devs.

**Comment by ctrlcctrlv** [comment]
I registered #vichan on Rizon.
