### ISSUE TITLE
nginx setup for vichan

### ISSUE THREAD

**Issue by shoei1944** [vichan-devel/vichan#614]
How to set up NGINX for vichan? On such 

server {
        listen 80;
        #listen [::]:80 default_server;
        include realip;
        root /var/www/vichan;
        index  index.html index.htm index.php;
        server_name b.site.org;
        location / {
        }
        location ~ /\. {
                deny all; # запрет для скрытых файлов
        }
        location ~ \.php$ {
                include snippets/fastcgi-php.conf;
                fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        }
}

settings I get a 403 error.

**Comment by RealAngeleno** [comment]
Where are you getting the 403 error? Am assuming you're still installing it? Do install.php and mod.php load fine?

**Comment by shoei1944** [comment]
install.php and mod.php loaded fine
(for check https://b.shoeii.ru/mod.php)

**Comment by shoei1944** [comment]
i uses php7.4

**Comment by RealAngeleno** [comment]
I see what's going on. Vichan doesn't come with a homepage by default. If you log into to mod.php, then go to "manage themes," there is a theme for a homepage or one for recent posts.
