### ISSUE TITLE
inc/secrets.php file missing

### ISSUE THREAD

**Issue by amuradbegovic** [vichan-devel/vichan#619]
I installed vichan as instructed by running `composer install` in the installation directory. Then I opened install.php in my browser but I was met with some error messages! Apparently the file `inc/secrets.php` is missing. Is it supposed to be generated or created manually? 

```
Warning: file_get_contents(inc/secrets.php): Failed to open stream: No such file or directory in /usr/local/www/vichan/inc/functions.php on line 125

Fatal error: Uncaught Error: Call to undefined function _setlocale() in /usr/local/www/vichan/inc/functions.php:31 Stack trace: #0 /usr/local/www/vichan/inc/functions.php(142): init_locale('en', 'error') #1 /usr/local/www/vichan/inc/functions.php(20): loadConfig() #2 /usr/local/www/vichan/vendor/composer/autoload_real.php(69): require('/usr/local/www/...') #3 /usr/local/www/vichan/vendor/composer/autoload_real.php(59): composerRequired28ecb97301d2e368c6590c9b7595edc('02f2f8ab1676a4f...', '/usr/local/www/...') #4 /usr/local/www/vichan/vendor/autoload.php(7): ComposerAutoloaderInitd28ecb97301d2e368c6590c9b7595edc::getLoader() #5 /usr/local/www/vichan/inc/bootstrap.php(3): require_once('/usr/local/www/...') #6 /usr/local/www/vichan/install.php(5): require('/usr/local/www/...') #7 {main} thrown in /usr/local/www/vichan/inc/functions.php on line 31

Warning: Undefined array key "syslog" in /usr/local/www/vichan/inc/display.php on line 77

Warning: Undefined array key "debug" in /usr/local/www/vichan/inc/display.php on line 89

Warning: Undefined array key "debug" in /usr/local/www/vichan/inc/display.php on line 93

Warning: Cannot modify header information - headers already sent by (output started at /usr/local/www/vichan/inc/functions.php:125) in /usr/local/www/vichan/inc/display.php on line 104

Warning: Undefined array key "password" in /usr/local/www/vichan/inc/display.php on line 107

Warning: Undefined array key "file_page_template" in /usr/local/www/vichan/inc/display.php on line 119

Fatal error: Uncaught Error: Call to undefined function _() in /usr/local/www/vichan/inc/display.php:121 Stack trace: #0 /usr/local/www/vichan/inc/functions.php(350): error('Caught fatal er...', 3) #1 [internal function]: fatal_error_handler() #2 {main} thrown in /usr/local/www/vichan/inc/display.php on line 121
``` 

As you can see there are some other error messages as well, but sadly I am not a PHP programmer so I wouldn't know how to resolve that and I plan on figuring out what to do with the missing secrets file first. 

If it helps, I'm running Apache 2.4.57_1, MySQL 8.0.32_3 and PHP 8.1.20 on FreeBSD 13.2-RELEASE-p2.
If someone encountered a similar problem please share your experience. Perhaps I'm just missing something and I need some guide to get this right.

**Comment by RealAngeleno** [comment]
That's definitely a good thought. You usually have to make it yourself and set the permissions, which can definitely be a hassle if you install vichan a bunch.

**Comment by amuradbegovic** [comment]
Thank you for clarifying. Is there a certain syntax/format I should follow?
It mentions something in the file `inc/config.php`...

```
 *  This is the default configuration. You can copy values from here and use them in
 *  your secrets.php
 ```
 
 Which values? All of them or only the part with database credentials?

**Comment by amuradbegovic** [comment]
I simply copied config.php to secrets.php and it is working (hopefully that didn't harm security?). I should've looked more closely at the comments in the source code. My suggestion would be to make it more clear in the documentation that users might have to manually create secrets.php before installing.

**Comment by RealAngeleno** [comment]
Not at all. You don't need to add anything to secrets.php as that is all done automatically.
