### ISSUE TITLE
Individual board locking problem

### ISSUE THREAD

**Issue by crazy4cars69** [vichan-devel/vichan#623]
It has come to my attention that it's impossible to lock a single board, and if you lock a single board while others are open the board won't be locked.

**Comment by nemurenaidesu** [comment]
I did a clean install like 10 mins ago, it is working fine.

>it's impossible to lock a single board

You are probably changing the global configuration file, you should create a `config.php` file for that board and set `$config['board_locked'] = true` if you want to lock that board only. (as @perdedora said :) )

![locked](https://github.com/vichan-devel/vichan/assets/144841647/f3841547-5e02-4219-a904-430c69808155)

**Comment by 4chess** [comment]
make a file called config.php  see the pic. Put that file in the main directory of a board, such as /b   it now locks that board. 
![locked](https://github.com/vichan-devel/vichan/assets/128197007/a98ca0df-8d95-4870-963f-689ded537de1)

**Comment by 4chess** [comment]
![bbbb](https://github.com/vichan-devel/vichan/assets/128197007/c6a84d5c-9239-4817-a314-0c13127a0dfe)
Here, you can see that i put the one line config.php file into the b directory. It then locks the board fine.

**Comment by 4chess** [comment]
![locked1](https://github.com/vichan-devel/vichan/assets/128197007/fa8d95af-6184-4b9b-963b-12aa342ea175)
this is what it looks like when i try to post on my locked board

**Comment by 4chess** [comment]
![instance-config](https://github.com/vichan-devel/vichan/assets/128197007/de79a474-2259-40fe-88ca-f0f8f41da59c)
and if you want  boards that looks like that, here is the whole instance-config.php that goes in /inc Notice that mod.php is now moda.php, you can change that to anything you want and rename mod.php.  Also that is how you get the form look and functions that i have. even the [create new thread] link. 
vichan is still a decent option, do not let the negative azzholes tell you different. :)

**Comment by 4chess** [comment]
Its safe to say that this question should be marked as solved lol

**Comment by ctrlcctrlv** [comment]
>here is the whole instance-config.php that goes in /inc
what are you expecting people to do, OCR your screenshot?

**Comment by 4chess** [comment]
Mr Wheels- it was more help than i ever got when i was figuring it out, but good point :)


`<?php
    $config['db']['type']		= 'mysql';
	$config['db']['server']		= 'localhost';
	$config['db']['user']		= '';
	$config['db']['password']	= '';
	$config['db']['database']	= '';
	@include('inc/secrets.php');
	
	
$config['syslog'] = true;
$config['force_image_op'] = false;
$config['field_disable_email'] = true;
$config['field_disable_reply_subject'] = true;
$config['field_disable_password'] = true;
$config['threads_per_page'] = 10;
$config['max_pages'] = 10;	
$config['threads_preview'] = 5;	
$config['threads_preview_sticky'] = 1;
$config['post_date'] = '%m/%d/%y';
$config['button_newtopic'] = _('Send');
$config['button_reply'] = _('Reply');
$config['stylesheets']['Yotsuba B'] = ''; // Default; there is no additional/custom stylesheet for this.
$config['stylesheets']['Yotsuba'] = 'yotsuba.css';
$config['stylesheets']['Miku'] = 'miku.css';
$config['stylesheets']['Dark'] = 'dark.css';

$config['boards'] = array(
		array('a', 'b'),
	 	array('c', 'd', 'e', 'f', 'g'),
		array('h', 'i', 'j'),
		array('k', array('l', 'm')),
 	array('Home' => '../')
	);

$config['enable_embedding'] = true;
$config['file_mod'] = 'moda.php';	
	
$config['embedding'] = array();
$config['embedding'][0] = array('/^https?:\/\/(\w+\.)?(?:youtube\.com\/watch\?v=|youtu\.be\/)([a-zA-Z0-9\-_]{10,11})(&.+)?$/i', $config['youtube_js_html']);
$config['additional_javascript'][] = 'js/jquery.min.js';
$config['additional_javascript'][] = 'js/options.js';
$config['additional_javascript'][] = 'js/style-select.js';
$config['additional_javascript'][] = 'js/options/general.js';
$config['additional_javascript'][] = 'js/ajax.js';
$config['additional_javascript'][] = 'js/file-selector.js';
$config['additional_javascript'][] = 'js/upload-selection.js';
$config['additional_javascript'][] = 'js/hide-form.js';
$config['additional_javascript'][] = 'js/youtube.js';
?>
`

**Comment by 4chess** [comment]
raw form the above did not format right

 <?php
    $config['db']['type']		= 'mysql';
	$config['db']['server']		= 'localhost';
	$config['db']['user']		= '';
	$config['db']['password']	= '';
	$config['db']['database']	= '';
	@include('inc/secrets.php');
	
	
$config['syslog'] = true;
$config['force_image_op'] = false;
$config['field_disable_email'] = true;
$config['field_disable_reply_subject'] = true;
$config['field_disable_password'] = true;
$config['threads_per_page'] = 10;
$config['max_pages'] = 10;	
$config['threads_preview'] = 5;	
$config['threads_preview_sticky'] = 1;
$config['post_date'] = '%m/%d/%y';
$config['button_newtopic'] = _('Send');
$config['button_reply'] = _('Reply');
$config['stylesheets']['Yotsuba B'] = ''; // Default; there is no additional/custom stylesheet for this.
$config['stylesheets']['Yotsuba'] = 'yotsuba.css';
$config['stylesheets']['Miku'] = 'miku.css';
$config['stylesheets']['Dark'] = 'dark.css';

$config['boards'] = array(
		array('a', 'b'),
	 	array('c', 'd', 'e', 'f', 'g'),
		array('h', 'i', 'j'),
		array('k', array('l', 'm')),
 	array('Home' => '../')
	);

$config['enable_embedding'] = true;
$config['file_mod'] = 'moda.php';	
	
$config['embedding'] = array();
$config['embedding'][0] = array('/^https?:\/\/(\w+\.)?(?:youtube\.com\/watch\?v=|youtu\.be\/)([a-zA-Z0-9\-_]{10,11})(&.+)?$/i', $config['youtube_js_html']);
$config['additional_javascript'][] = 'js/jquery.min.js';
$config['additional_javascript'][] = 'js/options.js';
$config['additional_javascript'][] = 'js/style-select.js';
$config['additional_javascript'][] = 'js/options/general.js';
$config['additional_javascript'][] = 'js/ajax.js';
$config['additional_javascript'][] = 'js/file-selector.js';
$config['additional_javascript'][] = 'js/upload-selection.js';
$config['additional_javascript'][] = 'js/hide-form.js';
$config['additional_javascript'][] = 'js/youtube.js';
?>

**Comment by 4chess** [comment]
<?php
    $config['db']['type']		= 'mysql';
	$config['db']['server']		= 'localhost';
	$config['db']['user']		= '';
	$config['db']['password']	= '';
	$config['db']['database']	= '';
	@include('inc/secrets.php');
	
	
$config['syslog'] = true;
$config['force_image_op'] = false;
$config['field_disable_email'] = true;
$config['field_disable_reply_subject'] = true;
$config['field_disable_password'] = true;
$config['threads_per_page'] = 10;
$config['max_pages'] = 10;	
$config['threads_preview'] = 5;	
$config['threads_preview_sticky'] = 1;
$config['post_date'] = '%m/%d/%y';
$config['button_newtopic'] = _('Send');
$config['button_reply'] = _('Reply');
$config['stylesheets']['Yotsuba B'] = ''; // Default; there is no additional/custom stylesheet for this.
$config['stylesheets']['Yotsuba'] = 'yotsuba.css';
$config['stylesheets']['Miku'] = 'miku.css';
$config['stylesheets']['Dark'] = 'dark.css';

$config['boards'] = array(
		array('a', 'b'),
	 	array('c', 'd', 'e', 'f', 'g'),
		array('h', 'i', 'j'),
		array('k', array('l', 'm')),
 	array('Home' => '../')
	);

$config['enable_embedding'] = true;
$config['file_mod'] = 'moda.php';	
	
$config['embedding'] = array();
$config['embedding'][0] = array('/^https?:\/\/(\w+\.)?(?:youtube\.com\/watch\?v=|youtu\.be\/)([a-zA-Z0-9\-_]{10,11})(&.+)?$/i', $config['youtube_js_html']);
$config['additional_javascript'][] = 'js/jquery.min.js';
$config['additional_javascript'][] = 'js/options.js';
$config['additional_javascript'][] = 'js/style-select.js';
$config['additional_javascript'][] = 'js/options/general.js';
$config['additional_javascript'][] = 'js/ajax.js';
$config['additional_javascript'][] = 'js/file-selector.js';
$config['additional_javascript'][] = 'js/upload-selection.js';
$config['additional_javascript'][] = 'js/hide-form.js';
$config['additional_javascript'][] = 'js/youtube.js';
?>

**Comment by 4chess** [comment]
> > here is the whole instance-config.php that goes in /inc
> 
> what are you expecting people to do, OCR your screenshot?

good point. here is a link to the text  https://github.com/4chess/instance-config

**Comment by 4chess** [comment]
annnnd if i may.... a quick story. Lynxchan kept saying it crashed. I guess the new changes to ubuntu 22.04 and lynxchan do not mix. That was absurd. Worked half the time, crashed the other half. So i went back to vichan a couple hours ago. Of note, BUN is going to be way better than node.js, im not touching another node.js ib ever. It will take a long time for someone to code a ib in bun or rust or go (an ib that is well maintained). The WHOLE time tho, the php board has been here, and it works. It may not be the newest tech, but ya know what? At least it works.

**Comment by ctrlcctrlv** [comment]
meow

![image](https://github.com/vichan-devel/vichan/assets/838783/4beb32b0-ce16-42b0-a61d-91b0e2fa59fd)
