### ISSUE TITLE
MP3 

### ISSUE THREAD

**Issue by 4chess** [vichan-devel/vichan#633]
hi! I got mp4 and webm to open inline.  Is there any way to get mp3 to open inline instead of in a new window?  Some other ib's show a mp3 player where the user can simply click on it to hear the audio. For example this go powered board handles that awesome. https://usagi.reisen/  It would be very helpful if vichan handled uploaded mp3 in a similar way.

**Comment by 4chess** [comment]
@perdedora awesome, i will try it!!

**Comment by 4chess** [comment]
still seems to open separate window.

**Comment by 4chess** [comment]
@perdedora   got it!!!!! Thanks to you pointing out the image.html i used chatgpt to fix it!!!!!!! Since chatgpt made it, can you please look it over to make sure its legit and safe? I put it here https://github.com/4chess/mp3 feel free to ad it to the main repo if you like it!!!

**Comment by 4chess** [comment]
I had chatgpt make image.html a bunch of times, it can not get it right. it can easily inject the html5 mp3 player into the post, but doing so makes either video or images open in a different window. Must be the js conflicts with it? Sure looks nice when there is an mp3 player inline that one just clicks to play. I will keep trying, i guess i will have to feed chatgpt the relevant js as well. What exactly is that, the inline-expanding.js ?

**Comment by 4chess** [comment]
still looking for a solution if anyone can help. Its a stupid thing, mp3 should be able to open inline via html5 pm3 player code without screwing up inline expanding of images or jpg. Like i say chat gpt tried, literally about 20 times. Chatgpt kept saying oah sorry i got it right now...then it still did not work lol.

**Comment by RealAngeleno** [comment]
I think kolyma had a solution to this on soyjak party. Of course, their solution was proprietary, but an open source solution, which was later done, works very well and deserves a PR.

**Comment by 4chess** [comment]
Looks like its the jquery? According to my cousin (Chat GPT)  js has evolved and for lots of use cases jquery is considered outdated and overkill. Like i mentioned, Chat GPT makes workable simple scripts that simply inject the html5 mp3 player. It is funny how that conflicts with the images and videos tho on vichan, it make a seemingly simple task a lot more difficult than it looks at first sight. Too bad there is not a modern vanilla  js expert around who could overhaul all the js in vichan, that would modernize it greatly and improve functionality. Me and my cousin (Chat GPT) tried a few more times, no solution yet that does not break image inline expanding or video. It is such a seemingly simple roadblock that it is actually comical. I will keep trying tho.

**Comment by 4chess** [comment]
![2023-10-03_10-18-24](https://github.com/vichan-devel/vichan/assets/128197007/c72fa26c-e2f1-4d4d-ad2f-7d7e7905296d)
Was looking at other chans. Wizard chan did it with the audio, there is an "expand audio inline" in the options menu.

**Comment by 4chess** [comment]
![zzzzzzz](https://github.com/vichan-devel/vichan/assets/128197007/fbd344bb-ba2d-4f4c-8f05-1fa9ecbe448a)
They have it in options. A custom made js i take it?

**Comment by 4chess** [comment]
Will close it out, as issue is solved , but vichan should implement something to make mp3 files play by default. If nothing else, just run the js i provided after jquery is run. Its good code, it only affects the "fileinfo" class links that end in .mp3 which is perfect.

**Comment by 4chess** [comment]
disregard my posts here in this thread, see the closed post called "mp3 fix" for a better version.
