### ISSUE TITLE
Boardlist doesn't show up ontop

### ISSUE THREAD

**Issue by BiohazardMaker** [vichan-devel/vichan#635]
I've read somewhere here a supposed solution to replace some code, but it didn't work for me. Can anybody guess what could it be?

**Comment by 4chess** [comment]
the code is in config.php  it is commented out. put this in instance-config.php and edit it to match your board 
 $config['boards'] = array(
		array('advice'),
	      array('articles'),
            array('b'),
             array('mods'),
		array('orgs'),
            array('stfu'),
            array('Home' => '../')
	);

**Comment by BiohazardMaker** [comment]
Thank you very much 4chess! God bless!

**Comment by 4chess** [comment]
If you got it all figured out, its prolly nice to close out this question. It is usually up to the asker to close it out when they get the issues resolved.
