### ISSUE TITLE
tor false flagged 

### ISSUE THREAD

**Issue by 4chess** [vichan-devel/vichan#637]
A general fyi since vichan ppl often use tor. 
Yesterday, Windows Defender started to falsely claim tor has Trojan:Win32/Malgent!MTB virus. You can look it up easily, google it. Windows defender and Norton and the like ALWAYS happen to say competitors have "virus" in them, total bullshit. Tor prevents them from tracking so they like to encourage others to not use it. I set my defender to ignore that warning, and norton which is better than defender never says tor is a virus. Its all bullshit. Its like a far left snowflake calling anyone who does not agree with delusional concepts a racist. In the same way. leftist microsoft defefender calls tor a "virus" because tor prohibits advertisers from tracking you.In a while, microsoft defender will make an excuse like they always do,,, admit tor does not have a virus, and say, oah, it had a similar pattern or some bullshit. Truth is they directly lied in order to try and screw with a competitor (tor) in an illegal way.

**Comment by 4chess** [comment]
and yes i am aware ms own git lol

**Comment by ctrlcctrlv** [comment]
this is not a forum
