### ISSUE TITLE
Password field is not hidden

### ISSUE THREAD

**Issue by chanadmins** [vichan-devel/vichan#641]
In post form, the password field should be hidden behind the dots ******* instead of showing the full password. This would prevent it from leaking when user for example shares a screenshot. I saw this fixed on some vichan fork, but the main branch still has this problem.

**Comment by 4chess** [comment]
https://www.dofactory.com/html/input/password  look at the html template that makes the form, that is where you change any form look that is not specified in the config files.

**Comment by 4chess** [comment]
Alternatively, before taking a screen shot, just put in no or a false password. Or, after taking the screen shot, edit out the password.

**Comment by chanadmins** [comment]
> https://www.dofactory.com/html/input/password look at the html template that makes the form, that is where you change any form look that is not specified in the config files.

You're right, I just needed to change <input type="text" name="password" to <input type="password" name="password" in post_form.html

**Comment by 4chess** [comment]
yes, html5 has come a long way from what html used to be. in vichan you can control the look and feel a lot with simple css as well!
