### ISSUE TITLE
Catalog logs moderator off

### ISSUE THREAD

**Issue by chanadmins** [vichan-devel/vichan#648]
When logged in as moderator (/mod.php?/), clicking on the Catalog link (catalog.html) logs the moderator out. Is there any way to fix this issue? The same problem occurs when navigating to the Homepage (index.html).

**Comment by RealAngeleno** [comment]
I made a script a long time ago to fix that. I'll PR it.

**Comment by RealAngeleno** [comment]
There was a fix for that a little while ago. Are you using the current version of vichan?

https://github.com/vichan-devel/vichan/blob/master/js/catalog-link.js

**Comment by chanadmins** [comment]
I updated catalog-link.js to current version but it just redirects to Page not found (/mod.php?/b/catalog.html). What else do I need to update?

**Comment by chanadmins** [comment]
Yeah some files are even from 2019, but I can't exactly update everything because it was changed. The entire antibot thing is removed so the quick reply can work on index.html without opening the thread like on kissu.moe/magalichan.
