### ISSUE TITLE
Fatal error when trying to ban & delete

### ISSUE THREAD

**Issue by frozenpandaman** [vichan-devel/vichan#649]
Got this message using the B&D option on a post:

```
Caught fatal error: Uncaught PDOException: SQLSTATE
[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column `ib`.`bans`.`expires` at row 1 in /path/to/inc/bans.php:302
Stack trace:
#0 /path/to/inc/bans.php(302): PDOStatement->execute()
#1 /path/to/inc/mod/pages.php(1597): Bans::new_ban('THE_IP_ADDRESS', '', false, false, 1, false)
#2 /path/to/mod.php(196): mod_ban_post('boardname', '', '123')
#3 {main} thrown in /path/to/inc/bans.php on line 302
```

I had to delete the post and then separately deny access to the IP via .htaccess (I'm not sure how to manually add a ban, and can't figure out adding a row to the SQL `bans` table from phpMyAdmin because the `ipstart` value seems to be in hexidecimal…)

**Comment by frozenpandaman** [comment]
@virtuelles I left it empty, as the default, which should make the ban permanent

**Comment by frozenpandaman** [comment]
@virtuelles I'll try that when I get home. Is the only way to access the ban(&delete) interface via the `mod.php?/boardname/ban/postnumber/` URL? Do I just have to click a "[B]" icon on any random post – and that won't affect anything related to that post or poster itself, as long as I change the IP? It seems like a generic `/boardname/ban/` URL endpoint doesn't exist, so I need to click on _some_ post (i.e. with the post number in the URL) to get to that screen.

I'll try it on an example IP just to make sure the regex parsing works when specifying the ban length, but null is supposed to default to forever (i.e. does not expire), right? Is there a way to explicitly type or specify this? What's weird is permabans were definitely working before, as recently as a couple weeks ago, and I didn't change or upgrade anything.

Instead of outputting `null` on line 285, should it directly spit out the int `0` i.e. no expiry? Since the real issue seems to be in `pages.php` where it's expecting an int, not a(n empty) string.

**Comment by virtuelles** [comment]
'mod.php?/IP/[IP]' has the ban interface, and so does 'mod.php?/ban'.
> that won't affect anything related to that post or poster itself, as long as I change the IP?

In my rough testing, the answer is yes.

> Is there a way to explicitly type or specify this?

I did send a permanent ban after entering null.

> permabans were definitely working before

Try reboot and check again?

> should it directly spit out the int 0 i.e. no expiry?

I think using 0 as the command for permaban might not work because the ban duration check seems to verify if the input is an integer first.

```php
if ($length) {
	if (is_int($length) || ctype_digit($length)) {
		$length = time() + $length;
	} else {
		$length = self::parse_time($length);
	}
	$query->bindValue(':expires', $length);
} else {
	$query->bindValue(':expires', null, PDO::PARAM_NULL);
}
```

**Comment by frozenpandaman** [comment]
> and so does `mod.php?/ban`

Thanks! That's the URL I was looking for. I don't think it's linked anywhere on the mod dashboard, but maybe I'm just missing something?

I also think I might have just been being veeeery stupid/tired and accidentally typing in the ban reason into the ban length box – I tried that out, now on purpose, and it seems to produce the same error…
Anyway, having that handled a bit more nicely would be, well, nice, but it's not a priority by any means! I think I can safely close this now.
