### ISSUE TITLE
Support syntax highlighting

### ISSUE THREAD

**Issue by mgrabovsky** [vichan-devel/vichan#67]
It would be nice to have at least a basic support for highlighting code, i.e., some kind of polyglot, catch-all that would highlight the most frequently used keywords, string and number literals, symbols, etc.

A more robust option would be to use a third-party highlighting library with either (a) supplying the language in the markup (e.g. `[code lang=ruby]puts "hello world"[/code]`), or (b) employing a probabilistic language recognition algorithm. This may not go well with the current light-weight, few-dependencies philosophy, though.

**Comment by czaks** [comment]
The problem with that is that we still don't have a proper parser, just a bunch for regular expressions. I have a workaround in mind.

For example, let's suppose that ```[b]...[/b]``` means bold text and ```[code=Lisp]...[/code]``` means code markup. Not that i'm suggesting those, let's take it for granted.

How about such a code:

    [code=Lisp][b]LOL DONGS[/b][/code]

What would our current “parser” do? It would probably encode it as:

    <code><font color='red'>&lt;b&gt;LOL DONGS&lt;/b&gt;</font></code>

...if markup was run first, or:

    <code><font color='red'><b>LOL DONGS</b></font></code>

...if the regexp things were run first.

@ctrlcctrlv how do you solve it in infinity?

**Comment by czaks** [comment]
Ok, one of the recent commits introduced one of the syntaxes: triple backquote, like github and [code], to be manually enabled by board admin. We still don't have a code highlighting solution, but it should be easy.
