### ISSUE TITLE
Switch to Zend_Translate (which supports existing gettext files)

### ISSUE THREAD

**Issue by ctrlcctrlv** [vichan-devel/vichan#68]
The reasons for this are many:

* gettext.php is under GNU GPL, not even legal to be used in Tinyboard or vichan
* Gettext does not officially support a locale we have, eo (Esperanto)
* If locales are not installed gettext doesn't even work silently, leading to many unneeded support requests
* Most shared hosting providers do not allow you to edit php.ini and thus disable gettext.so

**Comment by czaks** [comment]
WONTFIX, at least not now
