### ISSUE TITLE
Versioning and merging PRs faster

### ISSUE THREAD

**Issue by RealAngeleno** [vichan-devel/vichan#703]
I'm thinking of merging PRs to a dev branch first, then pulling those into main with a new version number each time that happens. It'll fix the slowness that some talk about, mostly coming from being busy with school/work (overworked and underpaid, you know) and the co-maintainer being MIA.
It'll help streamline a bunch of things.

**Comment by Zankaria** [comment]
I fully support this👍
Tell me to which branch retarget my PRs to and I'll do it

**Comment by RealAngeleno** [comment]
utilize the dev branch

**Comment by Zankaria** [comment]
I retargeted #668 #677 and #711

**Comment by RealAngeleno** [comment]
Thank you. Merged #677 and #711. Not 668 since vichan.info is now being used for that.

**Comment by flake-spec** [comment]
angy leeno
