### ISSUE TITLE
expand.js - Mentionlinks do not show up when there's 1 or 2 replies omitted

### ISSUE THREAD

**Issue by chanadmins** [vichan-devel/vichan#747]
After expanding thread from page view, some mentionlinks are missing.

<img width="541" alt="jj8" src="https://github.com/vichan-devel/vichan/assets/147612174/6aa115f6-2741-471e-a6da-e052d72127a3">

Here, there should be >>58866 next to first reply.

Any idea how to fix that?

EDIT: Happens on every vichan imageboard it seems, when you are expanding thread with just 2 or 1 replies omitted. When there's a lot replies, it works just fine.

<img width="541" alt="jsj8" src="https://i.imgur.com/8rBYLvy.png">

**Comment by Zankaria** [comment]
Not really relevant to the issue, but what board is that?

**Comment by chanadmins** [comment]
> Not really relevant to the issue, but what board is that?

[polish altchan](https://ziemniachan.altervista.org/int/)

**Comment by perdedora** [comment]
sent a pr
