### ISSUE TITLE
Demo website

### ISSUE THREAD

**Issue by catamphetamine** [vichan-devel/vichan#756]
Hi. I was just passing by to see if there was any activity in the repo and I've noticed that you've created a website at [vichan.info](https://vichan.info/index.php?title=Main_Page)
I can see that it's a Wiki, although when clicking that link I expected something different — a live demo website.
Since you're already hosting a PHP wiki, why not host a `vichan` instance itself? It could just be a couple of boards: `/test` and, say, `/support`.
* `/test` would have a maximum threads limit of, say, 10, and could be auto-wiped every 15 min or so. That would work around the spammers.
* `/support` would be read-only for anyone and only admins could post there.

The rationale: if someone finds the repo, before installing the engine, they'd have to "demo" it somehow. An analogy would be bying shoes. I mean, there're even no screenshots in the docs. And no "showcase" video. If a user can't see what `vichan` is, they won't bother installing it. The most user-friendly demo would be having a demo website running on `vichan` engine itself.

P.S. GitHub seems to have a pretty usable Wiki in the "Wiki" tab (no custom hosting required).

Offtopic: I was also developing an "alternative" javascript-based client for engines like `vichan`: https://anychans.github.io/lainchan/%CE%BB
I was thinking about finishing the "posting" part. If you create a "demo" website and you'd like to host this alternative GUI on that website, I could assist in that, in which case you could ping me in this issue.

You can also close this issue if you have already planned on rolling out a "live demo" instance of `vichan`.

**Comment by RealAngeleno** [comment]
I do for now, kind of: https://dev.vichan.info, though this is more of a test of vichan 5.2.0. It's definitely something I am thinking about. Though if I did a demo, it would allow users to log into the admin portal, though some changes like not being able to change your own password, cloaking ips, etc.

**Comment by catamphetamine** [comment]
> I do for now, kind of: https://dev.vichan.info/, though this is more of a test of vichan 5.2.0

Oh, I see. So you do have a "stealth" demo deployment. Cool. You could add this link to the README then somewhere at the top. Otherwise, people that stumble upon the repo won't even know how "vichan" looks like.

> Though if I did a demo, it would allow users to log into the admin portal, though some changes like not being able to change your own password, cloaking ips, etc.

I see, you're planning to deploy a full admin-access-level demo. That sounds like it would make sense. In that case, you could create some kind of a "cron" job that would reset any settings every N minutes or so. Ok then, that's out of the scope of the original comment though.
