### ISSUE TITLE
"Show relative time" checkbox option is broken

### ISSUE THREAD

**Issue by Taikuree** [vichan-devel/vichan#808]
Checkbox option for "Show relative time" in user options does not work. Checking or unchecking the box does nothing.
The issue is replicated on the demo site at dev.vichan.info
![5jag](https://github.com/user-attachments/assets/1f26c175-5013-489e-bc56-4a798782ae6c)

I can disable relative time by reverting these changes https://github.com/vichan-devel/vichan/commit/c21eeff6057a50230b4ba3574ba19757995b3546, but it also somehow makes the checkbox option disappear.

**Comment by chanadmins** [comment]
works for me, maybe you have local-time.js too low or too high in JS list? or you have to configure the time zone

**Comment by Taikuree** [comment]
> maybe you have local-time.js too low or too high in JS list? 

Thanks, that was it.
_js/options.js_ needs to load before _js/local-time.js_.
