### ISSUE TITLE
Blank page when I try to post?

### ISSUE THREAD

**Issue by edensy0** [vichan-devel/vichan#830]
I set up a basic install of vichan and everything works fine except posts can't actually be made. any time i attempt to post it just redirects to post.php and gets stuck on a blank white page. not sure what i did wrong i tried to restart the server, php, everything and it doesn't seem to help. I'm running the server on debian with php 7.3. Maybe I'm just being stupid but I'd love some help. Thank you.

**Comment by edensy0** [comment]
> check permissions and correct php version and other packages, check php error log

I looked at the error log and encountered this message which mentions post.php 

`FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected '|', expecting ';' or '{' in /var/www/chan/inc/bans.php on line 145" while reading response header from upst$  upstream, client: (my ip), server: chan.xyz, request: "POST /post.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "chan.xyz", referrer: "https://chan.xyz/b/"`

I'm not much of a programmer but the | in line 145 of post.php seems totally synthx correct? what could this mean? thanks for the help

**Comment by Zankaria** [comment]
What channel where you using? `master`, `dev` or the 5.1.5 release?

**Comment by Zankaria** [comment]
>FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected '|', expecting ';' or '{' in /var/www/chan/inc/bans.php on line 145" while reading response header from upst$  upstream, client: (my ip), server: chan.xyz, request: "POST /post.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/**php7.2-fpm.sock**:", host: "chan.xyz", referrer: "https://chan.xyz/b/"

Are you using php 7.2? If so, that may be a contributing factor. The oldest supported PHP version is PHP 7.4 according to the readme

**Comment by edensy0** [comment]
> What channel where you using? `master`, `dev` or the 5.1.5 release?

master. upgraded to php 7.4.3 and having the same issue... thank you

**Comment by Zankaria** [comment]
Ok found the issue: I forgot that PHP 7.4 does not support multiple return types when I made the PR. The quick fix is to upgrade to PHP 8.0, otherwise I'll be making a patch to solve it and you'll have to wait a bit more

**Comment by edensy0** [comment]
> Ok found the issue: I forgot that PHP 7.4 does not support multiple return types when I made the PR. The quick fix is to upgrade to PHP 8.0, otherwise I'll be making a patch to solve it and you'll have to wait a bit more

thank you sm for the help. i tried reinstalling everything but now install.php gives a white screen of death with the following error:

`[error] 44333#44333: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  require_once(vendor/autoload.php): failed to open stream: No such file or directory in /var/www/chan/inc/bootstrap.php on line 3PHP message: PHP Fatal error:  require_once(): Failed opening required 'vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/chan/inc/bootstrap.php on line 3" while reading response header from upstream, client: (my ip), server: chan.xyz, request: "GET /install.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "chan.xyz`

I'll try seeing if I can update my php 8.0, not sure if my VPS can even run it but if there's no way of getting it working with 7.4...

**Comment by Zankaria** [comment]
> > Ok found the issue: I forgot that PHP 7.4 does not support multiple return types when I made the PR. The quick fix is to upgrade to PHP 8.0, otherwise I'll be making a patch to solve it and you'll have to wait a bit more
> 
> thank you sm for the help. i tried reinstalling everything but now install.php gives a white screen of death with the following error:
> 
> `[error] 44333#44333: *1 FastCGI sent in stderr: "PHP message: PHP Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory in /var/www/chan/inc/bootstrap.php on line 3PHP message: PHP Fatal error: require_once(): Failed opening required 'vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/chan/inc/bootstrap.php on line 3" while reading response header from upstream, client: (my ip), server: chan.xyz, request: "GET /install.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "chan.xyz`
> 
> I'll try seeing if I can update my php to 8.0, not sure if my VPS can even run that but if there's no way of getting it working with 7.4...

Have you installed the dependencies with composer?
https://github.com/vichan-devel/vichan?tab=readme-ov-file#installation
Point 2

**Comment by edensy0** [comment]
Finally works 

> > > Ok found the issue: I forgot that PHP 7.4 does not support multiple return types when I made the PR. The quick fix is to upgrade to PHP 8.0, otherwise I'll be making a patch to solve it and you'll have to wait a bit more
> > 
> > 
> > thank you sm for the help. i tried reinstalling everything but now install.php gives a white screen of death with the following error:
> > `[error] 44333#44333: *1 FastCGI sent in stderr: "PHP message: PHP Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory in /var/www/chan/inc/bootstrap.php on line 3PHP message: PHP Fatal error: require_once(): Failed opening required 'vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/chan/inc/bootstrap.php on line 3" while reading response header from upstream, client: (my ip), server: chan.xyz, request: "GET /install.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "chan.xyz`
> > I'll try seeing if I can update my php to 8.0, not sure if my VPS can even run that but if there's no way of getting it working with 7.4...
> 
> Have you installed the dependencies with composer? https://github.com/vichan-devel/vichan?tab=readme-ov-file#installation Point 2

Finally works :) ty for your help
