### ISSUE TITLE
Feature Request: User Edit

### ISSUE THREAD

**Issue by seisatsu** [vichan-devel/vichan#88]
Three years ago, I inherited the imageboard Uboachan.net from its previous owner when he retired. At the time, the site was running Wakaba+Desuchan, which had a nifty little feature that let you edit a post you had made previously by using your delete password.

Unfortunately, Wakaba+Desuchan was not public software, and our version had been mucked up by a bunch of spaghetti modifications from the last owner, such that I had to edit files in 6 places just to change the server directory the board was hosted in. Unable to make sense of it, I switched to Tinyboard at that time (and am now running Tinyboard+Vichan).

Since three years ago my users have been constantly asking me to bring back the user edit feature. Is this planned? Could it be? Everyone loved it and I think it would be a great optional feature for the software. The edit dialog already exists for the moderation interface, could this be repurposed?

**Comment by MrUke** [comment]
Up!
